export type SitemapXmlGeneratorMessages = Readonly<{
  meta: {
    name: string
    description: string
  }
  modeLabel: string
  modeDescription: string
  urlsetModeLabel: string
  sitemapIndexModeLabel: string
  baseUrlLabel: string
  baseUrlDescription: string
  baseUrlPlaceholder: string
  autoJoinLabel: string
  autoJoinDescription: string
  presetsLabel: string
  presetsDescription: string
  standardPresetLabel: string
  contentPresetLabel: string
  indexPresetLabel: string
  urlEntriesLabel: string
  urlEntriesDescription: string
  urlEntryLabel: string
  addUrlEntryLabel: string
  sitemapEntriesLabel: string
  sitemapEntriesDescription: string
  sitemapEntryLabel: string
  addSitemapEntryLabel: string
  removeEntryLabel: string
  locationLabel: string
  pathPlaceholder: string
  lastModifiedLabel: string
  lastModifiedPlaceholder: string
  changeFrequencyLabel: string
  changeFrequencyPlaceholder: string
  priorityLabel: string
  priorityPlaceholder: string
  outputLabel: string
  outputDescription: string
  outputEmptyDescription: string
  outputErrorTitle: string
  invalidBaseUrlMessage: string
  invalidUrlLocationMessage: string
  invalidSitemapLocationMessage: string
  invalidLastmodMessage: string
  invalidPriorityMessage: string
  generatedUrlCountLabel: string
  generatedSitemapCountLabel: string
  copyXmlLabel: string
  copiedLabel: string
  downloadXmlLabel: string
}>
