import {
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest"

import MarkdownToHtmlConverterClient from "./client"

const messages = {
  meta: {
    name: "Markdown to HTML Converter",
    description: "Convert Markdown into HTML.",
  },
  markdownLabel: "Markdown",
  markdownDescription: "Draft Markdown and import text files.",
  markdownPlaceholder: "Enter Markdown here...",
  importFromFileLabel: "Import from file",
  loadSampleLabel: "Load sample",
  resetLabel: "Reset",
  outputLabel: "Rendered HTML",
  outputDescription: "Preview the rendered fragment and inspect the source.",
  sanitizeLabel: "Sanitize output",
  sanitizeDescription: "Remove unsafe tags and attributes before export.",
  previewLabel: "Preview",
  previewDescription: "Sandboxed preview of the generated fragment.",
  sourceLabel: "HTML source",
  sourceDescription: "Exact fragment generated by the converter.",
  emptyTitle: "No HTML yet",
  emptyDescription: "Type or import Markdown to generate output.",
  charactersLabel: "Chars",
  linesLabel: "Lines",
  copyHtmlLabel: "Copy HTML",
  copiedLabel: "Copied",
  downloadHtmlLabel: "Download HTML",
  printHtmlLabel: "Print HTML",
} as const

describe("MarkdownToHtmlConverterClient", () => {
  beforeEach(() => {
    window.localStorage.clear()
  })

  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
  })

  test("shows an empty state before markdown is entered", () => {
    render(<MarkdownToHtmlConverterClient messages={messages} />)

    expect(screen.getByText("No HTML yet")).toBeDefined()

    const downloadButton = screen.getByRole("button", {
      name: "Download HTML",
    }) as HTMLButtonElement
    expect(downloadButton.disabled).toBe(true)
  })

  test("loads the sample markdown and generates downloadable html", async () => {
    render(<MarkdownToHtmlConverterClient messages={messages} />)

    fireEvent.click(screen.getByRole("button", { name: "Load sample" }))

    await waitFor(() => {
      expect(screen.getByText("HTML source")).toBeDefined()
      expect(
        (
          screen.getByRole("textbox", {
            name: "Markdown",
          }) as HTMLTextAreaElement
        ).value
      ).toContain("# Launch notes")
    })

    const downloadLink = screen.getByRole("link", { name: "Download HTML" })
    expect(downloadLink.getAttribute("download")).toBe("markdown.html")
    expect(downloadLink.getAttribute("href")).toMatch(/^blob:/)
  })

  test("sanitizes html by default and exposes raw html when toggled off", async () => {
    render(<MarkdownToHtmlConverterClient messages={messages} />)

    fireEvent.change(screen.getByRole("textbox", { name: "Markdown" }), {
      target: {
        value: '# Heading\n\n<img src="x" onerror="alert(1)">',
      },
    })

    await waitFor(() => {
      const htmlSource = document.querySelector("pre code")
      expect(htmlSource?.textContent?.includes("onerror")).toBe(false)
    })

    fireEvent.click(screen.getByRole("switch", { name: "Sanitize output" }))

    await waitFor(() => {
      const htmlSource = document.querySelector("pre code")
      expect(htmlSource?.textContent?.includes("onerror")).toBe(true)
    })
  })

  test("imports markdown from a file", async () => {
    render(<MarkdownToHtmlConverterClient messages={messages} />)

    const file = new File(["# Imported"], "notes.md", {
      type: "text/markdown",
    })

    fireEvent.change(screen.getByLabelText("Import from file"), {
      target: { files: [file] },
    })

    await waitFor(() => {
      expect(
        (
          screen.getByRole("textbox", {
            name: "Markdown",
          }) as HTMLTextAreaElement
        ).value
      ).toBe("# Imported")
    })
  })

  test("prints the preview document when requested", async () => {
    render(<MarkdownToHtmlConverterClient messages={messages} />)

    fireEvent.change(screen.getByRole("textbox", { name: "Markdown" }), {
      target: { value: "# Print me" },
    })

    const loadHandlers: Array<() => void> = []
    const printWindow = {
      document: {
        open: vi.fn(),
        write: vi.fn(),
        close: vi.fn(),
      },
      focus: vi.fn(),
      print: vi.fn(),
      close: vi.fn(),
      addEventListener: vi.fn((event: string, handler: () => void) => {
        if (event === "load") {
          loadHandlers.push(handler)
        }
      }),
      onafterprint: null as null | (() => void),
    }

    vi.spyOn(window, "open").mockReturnValue(printWindow as unknown as Window)

    fireEvent.click(screen.getByRole("button", { name: "Print HTML" }))

    await waitFor(() => {
      expect(printWindow.document.write).toHaveBeenCalled()
    })

    expect(printWindow.document.write).toHaveBeenCalledWith(
      expect.stringContaining("<h1>Print me</h1>")
    )

    loadHandlers.forEach((handler) => handler())
    expect(printWindow.print).toHaveBeenCalled()

    printWindow.onafterprint?.()
    expect(printWindow.close).toHaveBeenCalled()
  })
})
