import { load as yamlLoad } from "js-yaml"

// Use the tool-local dependency path so Vite resolves this package from the
// workspace package that owns it, not from the monorepo root.
// @ts-expect-error openapi-typescript does not publish stable types for this
// browser-safe internal entrypoint.
import transformSchemaImport from "../node_modules/openapi-typescript/dist/transform/index.mjs"
// @ts-expect-error openapi-typescript does not publish stable types for this
// internal printer entrypoint.
import * as tsModuleImport from "../node_modules/openapi-typescript/dist/lib/ts.mjs"
// @ts-expect-error openapi-typescript does not publish stable types for these
// internal helpers.
import * as utilsModuleImport from "../node_modules/openapi-typescript/dist/lib/utils.mjs"

type TransformSchema = (schema: unknown, ctx: unknown) => unknown[]
type AstToString = (ast: unknown) => string
type ResolveRef = (
  schema: unknown,
  ref: string,
  options?: { silent?: boolean; visited?: string[] }
) => unknown
type ScanDiscriminators = (
  schema: unknown,
  options: { silent?: boolean }
) => {
  objects: Record<string, unknown>
  refsHandled: string[]
}

const transformSchema = transformSchemaImport as TransformSchema
const astToString = tsModuleImport.astToString as AstToString
const resolveRef = utilsModuleImport.resolveRef as ResolveRef
const scanDiscriminators =
  utilsModuleImport.scanDiscriminators as ScanDiscriminators

type OpenApiDocument = Record<string, unknown> & { openapi: string }

type OpenApiParseErrorCode =
  | "empty"
  | "invalid"
  | "not-object"
  | "unsupported-version"

type OpenApiParseResult =
  | {
      ok: true
      document: OpenApiDocument
      externalRefs: string[]
    }
  | {
      ok: false
      code: OpenApiParseErrorCode
      message?: string
    }

type OpenApiTypegenOptions = {
  additionalProperties: boolean
  defaultNonNullable: boolean
  propertiesRequiredByDefault: boolean
  exportType: boolean
  enum: boolean
  pathParamsAsTypes: boolean
  rootTypes: boolean
  makePathsEnum: boolean
  generatePathParams: boolean
  immutable: boolean
  excludeDeprecated: boolean
  includeHeader: boolean
}

const DEFAULT_OPENAPI_TYPEGEN_OPTIONS: OpenApiTypegenOptions = {
  additionalProperties: false,
  defaultNonNullable: true,
  propertiesRequiredByDefault: false,
  exportType: false,
  enum: false,
  pathParamsAsTypes: false,
  rootTypes: false,
  makePathsEnum: false,
  generatePathParams: false,
  immutable: false,
  excludeDeprecated: false,
  includeHeader: true,
}

const HEADER_COMMENT = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`

function parseOpenApiDocument(source: string): OpenApiParseResult {
  const trimmed = source.trim()

  if (trimmed === "") {
    return { ok: false, code: "empty" }
  }

  const parsed = parseDocumentSource(trimmed)

  if ("error" in parsed) {
    return {
      ok: false,
      code: "invalid",
      message: parsed.error,
    }
  }

  if (
    !parsed.value ||
    typeof parsed.value !== "object" ||
    Array.isArray(parsed.value)
  ) {
    return { ok: false, code: "not-object" }
  }

  const version = (parsed.value as { openapi?: unknown }).openapi

  if (typeof version !== "string" || !version.startsWith("3.")) {
    return { ok: false, code: "unsupported-version" }
  }

  return {
    ok: true,
    document: parsed.value as OpenApiDocument,
    externalRefs: collectExternalRefs(parsed.value),
  }
}

function parseDocumentSource(
  trimmed: string
): { value: unknown } | { error: string } {
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    try {
      return { value: JSON.parse(trimmed) }
    } catch (jsonError) {
      try {
        return { value: yamlLoad(trimmed) }
      } catch (yamlError) {
        return {
          error:
            (jsonError instanceof Error
              ? jsonError.message
              : String(jsonError)) ||
            (yamlError instanceof Error
              ? yamlError.message
              : String(yamlError)),
        }
      }
    }
  }

  try {
    return { value: yamlLoad(trimmed) }
  } catch (error) {
    return {
      error: error instanceof Error ? error.message : String(error),
    }
  }
}

function collectExternalRefs(value: unknown): string[] {
  const refs = new Set<string>()

  function visit(node: unknown) {
    if (!node) {
      return
    }

    if (Array.isArray(node)) {
      node.forEach(visit)
      return
    }

    if (typeof node !== "object") {
      return
    }

    for (const [key, entry] of Object.entries(node)) {
      if (key === "$ref" && typeof entry === "string") {
        if (!entry.startsWith("#")) {
          refs.add(entry)
        }
        continue
      }

      visit(entry)
    }
  }

  visit(value)

  return Array.from(refs)
}

function generateOpenApiTypes(
  document: OpenApiDocument,
  options: OpenApiTypegenOptions = DEFAULT_OPENAPI_TYPEGEN_OPTIONS
): string {
  const mergedOptions = {
    ...DEFAULT_OPENAPI_TYPEGEN_OPTIONS,
    ...options,
  }

  const context = {
    additionalProperties: mergedOptions.additionalProperties,
    alphabetize: false,
    arrayLength: false,
    defaultNonNullable: mergedOptions.defaultNonNullable,
    discriminators: scanDiscriminators(document, { silent: true }),
    emptyObjectsUnknown: false,
    enum: mergedOptions.enum,
    enumValues: false,
    dedupeEnums: false,
    excludeDeprecated: mergedOptions.excludeDeprecated,
    exportType: mergedOptions.exportType,
    immutable: mergedOptions.immutable,
    rootTypes: mergedOptions.rootTypes,
    rootTypesNoSchemaPrefix: false,
    injectFooter: [] as unknown[],
    pathParamsAsTypes: mergedOptions.pathParamsAsTypes,
    propertiesRequiredByDefault: mergedOptions.propertiesRequiredByDefault,
    silent: true,
    inject: undefined as string | undefined,
    transform: undefined as unknown,
    transformProperty: undefined as unknown,
    postTransform: undefined as unknown,
    makePathsEnum: mergedOptions.makePathsEnum,
    generatePathParams: mergedOptions.generatePathParams,
    resolve: (ref: string) => resolveRef(document, ref, { silent: true }),
  }

  const ast = transformSchema(document, context)
  const content = astToString(ast)

  if (!mergedOptions.includeHeader) {
    return content
  }

  return `${HEADER_COMMENT}${content}`
}

export {
  DEFAULT_OPENAPI_TYPEGEN_OPTIONS,
  generateOpenApiTypes,
  parseOpenApiDocument,
  collectExternalRefs,
}
export type { OpenApiTypegenOptions }
