<template>
  <DescriptionMarkdown
    :title="t('what-is-blake3')"
    :description="t('what-is-blake3-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-blake3": "What is BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 is a modern cryptographic hash function derived from BLAKE2. It is designed for very high performance and parallelism while maintaining strong security. It produces a default 256-bit hash and supports extendable output length (XOF).\n\n**Key characteristics:**\n- **Extendable output length**: Can produce hashes of any length\n- **High performance**: Fast and parallelizable on modern CPUs\n- **Deterministic**: The same input always produces the same hash\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n- **Keyed hashing**: Supports an optional 32-byte key for MAC functionality\n- **Key derivation**: Can derive subkeys from key material and context\n\n**Common uses:**\n- File integrity verification\n- Content-addressed storage and deduplication\n- Digital signatures and certificates\n- Password storage and authentication\n- Cryptographic protocols and systems"
  },
  "zh": {
    "what-is-blake3": "什么是 BLAKE3？",
    "what-is-blake3-description-markdown": "BLAKE3 是一种现代加密散列函数，源自 BLAKE2。它在保持强安全性的同时，强调极高性能与并行处理。它默认输出 256 位哈希，并支持可扩展输出长度（XOF）。\n\n**主要特征：**\n- **可扩展输出长度**：可产生任意长度的哈希\n- **高性能**：在现代 CPU 上速度快且可并行\n- **确定性**：相同输入总是产生相同哈希\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从哈希反推原始输入在计算上不可行\n- **抗碰撞**：很难找到产生相同哈希的两个不同输入\n- **密钥散列**：支持可选的 32 字节密钥用于 MAC 功能\n- **密钥派生**：可从密钥材料与上下文派生子密钥\n\n**常见用途：**\n- 文件完整性验证\n- 内容寻址存储与去重\n- 数字签名和证书\n- 密码存储和身份验证\n- 加密协议和系统"
  },
  "zh-CN": {
    "what-is-blake3": "什么是 BLAKE3？",
    "what-is-blake3-description-markdown": "BLAKE3 是一种现代加密散列函数，源自 BLAKE2。它在保持强安全性的同时，强调极高性能与并行处理。它默认输出 256 位哈希，并支持可扩展输出长度（XOF）。\n\n**主要特征：**\n- **可扩展输出长度**：可产生任意长度的哈希\n- **高性能**：在现代 CPU 上速度快且可并行\n- **确定性**：相同输入总是产生相同哈希\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从哈希反推原始输入在计算上不可行\n- **抗碰撞**：很难找到产生相同哈希的两个不同输入\n- **密钥散列**：支持可选的 32 字节密钥用于 MAC 功能\n- **密钥派生**：可从密钥材料与上下文派生子密钥\n\n**常见用途：**\n- 文件完整性验证\n- 内容寻址存储与去重\n- 数字签名和证书\n- 密码存储和身份验证\n- 加密协议和系统"
  },
  "zh-TW": {
    "what-is-blake3": "什麼是 BLAKE3？",
    "what-is-blake3-description-markdown": "BLAKE3 是一種現代加密雜湊函數，源自 BLAKE2。它在維持高安全性的同時，強調極高效能與平行處理。它預設輸出 256 位元雜湊，並支援可延展輸出長度（XOF）。\n\n**主要特徵：**\n- **可延展輸出長度**：可產生任意長度的雜湊\n- **高效能**：在現代 CPU 上速度快且可平行化\n- **確定性**：相同輸入總是產生相同雜湊\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上不可行\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n- **金鑰雜湊**：支援可選的 32 位元組金鑰以提供 MAC 功能\n- **金鑰派生**：可從金鑰材料與上下文派生子金鑰\n\n**常見用途：**\n- 檔案完整性驗證\n- 內容尋址儲存與去重\n- 數位簽章和憑證\n- 密碼儲存和身份驗證\n- 加密協定和系統"
  },
  "zh-HK": {
    "what-is-blake3": "什麼是 BLAKE3？",
    "what-is-blake3-description-markdown": "BLAKE3 是一種現代加密雜湊函數，源自 BLAKE2。它在保持高安全性的同時，強調極高效能與並行處理。它預設輸出 256 位元雜湊，並支援可延展輸出長度（XOF）。\n\n**主要特徵：**\n- **可延展輸出長度**：可產生任意長度的雜湊\n- **高效能**：在現代 CPU 上速度快且可並行\n- **確定性**：相同輸入總是產生相同雜湊\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上不可行\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n- **金鑰雜湊**：支援可選的 32 位元組金鑰用於 MAC 功能\n- **金鑰派生**：可從金鑰材料與上下文派生子金鑰\n\n**常見用途：**\n- 檔案完整性驗證\n- 內容尋址儲存與去重\n- 數碼簽署和證書\n- 密碼儲存和身份驗證\n- 加密協定和系統"
  },
  "es": {
    "what-is-blake3": "¿Qué es BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 es una función hash criptográfica moderna derivada de BLAKE2. Está diseñada para un rendimiento muy alto y paralelismo manteniendo una seguridad sólida. Produce un hash de 256 bits por defecto y admite longitud de salida extendible (XOF).\n\n**Características clave:**\n- **Longitud de salida extendible**: Puede producir hashes de cualquier longitud\n- **Alto rendimiento**: Rápido y paralelizable en CPUs modernas\n- **Determinístico**: La misma entrada siempre produce el mismo hash\n- **Efecto avalancha**: Pequeños cambios en la entrada producen salidas drásticamente diferentes\n- **Irreversible**: Es computacionalmente inviable revertir el hash para encontrar la entrada original\n- **Resistente a colisiones**: Muy difícil encontrar dos entradas diferentes que produzcan el mismo hash\n- **Hash con clave**: Admite una clave opcional de 32 bytes para funcionalidad MAC\n- **Derivación de claves**: Puede derivar subclaves a partir de material de clave y contexto\n\n**Usos comunes:**\n- Verificación de integridad de archivos\n- Almacenamiento direccionado por contenido y deduplicación\n- Firmas digitales y certificados\n- Almacenamiento y autenticación de contraseñas\n- Protocolos y sistemas criptográficos"
  },
  "fr": {
    "what-is-blake3": "Qu'est-ce que BLAKE3 ?",
    "what-is-blake3-description-markdown": "BLAKE3 est une fonction de hachage cryptographique moderne dérivée de BLAKE2. Elle est conçue pour des performances très élevées et le parallélisme tout en maintenant une sécurité robuste. Elle produit un hash de 256 bits par défaut et prend en charge une longueur de sortie extensible (XOF).\n\n**Caractéristiques clés :**\n- **Longueur de sortie extensible** : Peut produire des hachages de n'importe quelle longueur\n- **Haute performance** : Rapide et parallélisable sur les CPU modernes\n- **Déterministe** : La même entrée produit toujours le même hachage\n- **Effet d'avalanche** : De petits changements dans l'entrée produisent des sorties drastiquement différentes\n- **Irréversible** : Il est informatiquement impossible d'inverser le hachage pour retrouver l'entrée originale\n- **Résistant aux collisions** : Très difficile de trouver deux entrées différentes produisant le même hachage\n- **Hachage avec clé** : Prend en charge une clé optionnelle de 32 octets pour la fonctionnalité MAC\n- **Dérivation de clés** : Peut dériver des sous-clés à partir de matériel de clé et de contexte\n\n**Utilisations courantes :**\n- Vérification d'intégrité de fichiers\n- Stockage adressé par contenu et déduplication\n- Signatures numériques et certificats\n- Stockage et authentification de mots de passe\n- Protocoles et systèmes cryptographiques"
  },
  "de": {
    "what-is-blake3": "Was ist BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 ist eine moderne kryptographische Hash-Funktion, die von BLAKE2 abgeleitet ist. Sie ist für sehr hohe Leistung und Parallelität ausgelegt und bietet dabei starke Sicherheit. Sie erzeugt standardmäßig einen 256-Bit-Hash und unterstützt eine erweiterbare Ausgabelänge (XOF).\n\n**Hauptmerkmale:**\n- **Erweiterbare Ausgabelänge**: Kann Hashes beliebiger Länge erzeugen\n- **Hohe Leistung**: Schnell und auf modernen CPUs parallelisierbar\n- **Deterministisch**: Dieselbe Eingabe erzeugt immer denselben Hash\n- **Lawineneffekt**: Kleine Änderungen in der Eingabe erzeugen drastisch unterschiedliche Ausgaben\n- **Irreversibel**: Rechnerisch nicht machbar, den Hash umzukehren, um die ursprüngliche Eingabe zu finden\n- **Kollisionsresistent**: Sehr schwierig, zwei unterschiedliche Eingaben mit demselben Hash zu finden\n- **Schlüssel-Hash**: Unterstützt einen optionalen 32-Byte-Schlüssel für MAC-Funktionalität\n- **Schlüsselableitung**: Kann Unterschlüssel aus Schlüsselmaterial und Kontext ableiten\n\n**Häufige Verwendungen:**\n- Datei-Integritätsprüfung\n- Inhaltsadressierte Speicherung und Deduplizierung\n- Digitale Signaturen und Zertifikate\n- Passwortspeicherung und Authentifizierung\n- Kryptographische Protokolle und Systeme"
  },
  "it": {
    "what-is-blake3": "Cos'è BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 è una funzione hash crittografica moderna derivata da BLAKE2. È progettata per prestazioni molto elevate e parallelismo mantenendo una sicurezza robusta. Produce un hash a 256 bit per impostazione predefinita e supporta una lunghezza di output estendibile (XOF).\n\n**Caratteristiche chiave:**\n- **Lunghezza di output estendibile**: Può produrre hash di qualsiasi lunghezza\n- **Alte prestazioni**: Veloce e parallelizzabile su CPU moderne\n- **Deterministico**: Lo stesso input produce sempre lo stesso hash\n- **Effetto valanga**: Piccoli cambiamenti nell'input producono output drasticamente diversi\n- **Irreversibile**: Computazionalmente impossibile invertire l'hash per trovare l'input originale\n- **Resistente alle collisioni**: Molto difficile trovare due input diversi che producano lo stesso hash\n- **Hash con chiave**: Supporta una chiave opzionale di 32 byte per la funzionalità MAC\n- **Derivazione delle chiavi**: Può derivare sottochiavi da materiale di chiave e contesto\n\n**Usi comuni:**\n- Verifica dell'integrità dei file\n- Archiviazione indirizzata al contenuto e deduplicazione\n- Firme digitali e certificati\n- Archiviazione e autenticazione password\n- Protocolli e sistemi crittografici"
  },
  "ja": {
    "what-is-blake3": "BLAKE3とは？",
    "what-is-blake3-description-markdown": "BLAKE3はBLAKE2から派生した最新の暗号学的ハッシュ関数です。高い安全性を保ちながら、非常に高い性能と並列処理を重視しています。デフォルトで256ビットのハッシュを生成し、可拡張出力長（XOF）をサポートします。\n\n**主な特徴：**\n- **可拡張出力長**：任意の長さのハッシュを生成可能\n- **高性能**：最新CPUで高速かつ並列化可能\n- **決定論的**：同じ入力は常に同じハッシュを生成\n- **雪崩効果**：入力の小さな変化が大きく異なる出力を生む\n- **不可逆**：ハッシュを逆算して元の入力を見つけることは計算上不可能\n- **衝突耐性**：同じハッシュを生成する2つの異なる入力を見つけることは非常に困難\n- **キー付きハッシュ**：MAC機能のためのオプションの32バイトキーをサポート\n- **キー導出**：鍵材料とコンテキストからサブキーを導出可能\n\n**一般的な用途：**\n- ファイル整合性検証\n- コンテンツアドレス型ストレージと重複排除\n- デジタル署名と証明書\n- パスワード保存と認証\n- 暗号プロトコルとシステム"
  },
  "ko": {
    "what-is-blake3": "BLAKE3란?",
    "what-is-blake3-description-markdown": "BLAKE3는 BLAKE2에서 파생된 최신 암호화 해시 함수입니다. 높은 보안을 유지하면서 매우 높은 성능과 병렬 처리를 목표로 설계되었습니다. 기본적으로 256비트 해시를 생성하며 확장 가능한 출력 길이(XOF)를 지원합니다.\n\n**주요 특징:**\n- **확장 가능한 출력 길이**: 임의 길이의 해시를 생성할 수 있음\n- **고성능**: 최신 CPU에서 빠르고 병렬화 가능\n- **결정론적**: 동일한 입력은 항상 동일한 해시를 생성\n- **눈사태 효과**: 입력의 작은 변화가 크게 다른 출력을 생성\n- **비가역적**: 해시를 역산해 원본 입력을 찾는 것은 계산적으로 불가능\n- **충돌 저항성**: 동일한 해시를 생성하는 두 개의 다른 입력을 찾기 매우 어려움\n- **키 해싱**: MAC 기능을 위한 선택적 32바이트 키 지원\n- **키 파생**: 키 재료와 컨텍스트에서 하위 키를 파생 가능\n\n**일반적인 용도:**\n- 파일 무결성 검증\n- 콘텐츠 주소 지정 저장 및 중복 제거\n- 디지털 서명 및 인증서\n- 비밀번호 저장 및 인증\n- 암호화 프로토콜 및 시스템"
  },
  "ru": {
    "what-is-blake3": "Что такое BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 — это современная криптографическая хеш-функция, производная от BLAKE2. Она разработана для очень высокой производительности и параллелизма при сохранении надежной безопасности. Она по умолчанию выдаёт 256-битный хеш и поддерживает расширяемую длину вывода (XOF).\n\n**Ключевые характеристики:**\n- **Расширяемая длина вывода**: Может производить хеши любой длины\n- **Высокая производительность**: Быстрая и параллелизуемая на современных CPU\n- **Детерминированность**: Одинаковый ввод всегда производит одинаковый хеш\n- **Эффект лавины**: Небольшие изменения во вводе приводят к резко отличающимся выводам\n- **Необратимость**: Вычислительно невозможно обратить хеш, чтобы найти исходный ввод\n- **Устойчивость к коллизиям**: Очень сложно найти два разных ввода с одинаковым хешем\n- **Хеширование с ключом**: Поддерживает опциональный 32-байтовый ключ для функциональности MAC\n- **Вывод ключей**: Может выводить под-ключи из ключевого материала и контекста\n\n**Обычные применения:**\n- Проверка целостности файлов\n- Хранение с адресацией по содержимому и дедупликация\n- Цифровые подписи и сертификаты\n- Хранение и аутентификация паролей\n- Криптографические протоколы и системы"
  },
  "pt": {
    "what-is-blake3": "O que é BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 é uma função hash criptográfica moderna derivada do BLAKE2. Ela foi projetada para desempenho muito alto e paralelismo mantendo segurança robusta. Produz um hash padrão de 256 bits e suporta comprimento de saída extensível (XOF).\n\n**Principais características:**\n- **Comprimento de saída extensível**: Pode produzir hashes de qualquer comprimento\n- **Alto desempenho**: Rápida e paralelizável em CPUs modernas\n- **Determinístico**: A mesma entrada sempre produz o mesmo hash\n- **Efeito avalanche**: Pequenas mudanças na entrada produzem saídas drasticamente diferentes\n- **Irreversível**: Computacionalmente inviável reverter o hash para encontrar a entrada original\n- **Resistente a colisões**: Muito difícil encontrar duas entradas diferentes que produzam o mesmo hash\n- **Hash com chave**: Suporta uma chave opcional de 32 bytes para funcionalidade MAC\n- **Derivação de chaves**: Pode derivar subchaves a partir de material de chave e contexto\n\n**Usos comuns:**\n- Verificação de integridade de arquivos\n- Armazenamento endereçado por conteúdo e deduplicação\n- Assinaturas digitais e certificados\n- Armazenamento e autenticação de senhas\n- Protocolos e sistemas criptográficos"
  },
  "ar": {
    "what-is-blake3": "ما هو BLAKE3؟",
    "what-is-blake3-description-markdown": "BLAKE3 هو دالة تجزئة تشفيرية حديثة مشتقة من BLAKE2. صُممت لأداء عالٍ جداً وللعمل المتوازي مع الحفاظ على أمان قوي. تنتج افتراضياً تجزئة بطول 256 بت وتدعم طول مخرجات قابل للتمديد (XOF).\n\n**الخصائص الرئيسية:**\n- **طول مخرجات قابل للتمديد**: يمكنه إنتاج تجزئات بأي طول\n- **أداء عالٍ**: سريع وقابل للتوازي على المعالجات الحديثة\n- **حتمي**: الإدخال نفسه ينتج دائماً التجزئة نفسها\n- **تأثير الانهيار**: التغييرات الصغيرة في الإدخال تنتج مخرجات مختلفة جذرياً\n- **غير قابل للعكس**: من غير العملي حسابياً عكس التجزئة للعثور على الإدخال الأصلي\n- **مقاوم للتصادمات**: من الصعب جداً إيجاد إدخالين مختلفين ينتجان التجزئة نفسها\n- **تجزئة بمفتاح**: يدعم مفتاحاً اختيارياً بطول 32 بايت لوظيفة MAC\n- **اشتقاق المفاتيح**: يمكنه اشتقاق مفاتيح فرعية من مادة المفتاح والسياق\n\n**الاستخدامات الشائعة:**\n- التحقق من سلامة الملفات\n- التخزين المعنون بالمحتوى وإزالة التكرار\n- التواقيع الرقمية والشهادات\n- تخزين كلمات المرور والمصادقة\n- البروتوكولات والأنظمة التشفيرية"
  },
  "hi": {
    "what-is-blake3": "BLAKE3 क्या है?",
    "what-is-blake3-description-markdown": "BLAKE3 एक आधुनिक क्रिप्टोग्राफ़िक हैश फ़ंक्शन है जो BLAKE2 से व्युत्पन्न है। इसे बहुत उच्च प्रदर्शन और समानांतरता के लिए डिजाइन किया गया है, जबकि मजबूत सुरक्षा बनी रहती है। यह डिफ़ॉल्ट रूप से 256-बिट हैश उत्पन्न करता है और विस्तारणीय आउटपुट लंबाई (XOF) का समर्थन करता है।\n\n**मुख्य विशेषताएँ:**\n- **विस्तारणीय आउटपुट लंबाई**: किसी भी लंबाई के हैश उत्पन्न कर सकता है\n- **उच्च प्रदर्शन**: आधुनिक CPU पर तेज़ और समानांतर किया जा सकता है\n- **नियतात्मक**: समान इनपुट हमेशा समान हैश उत्पन्न करता है\n- **हिमस्खलन प्रभाव**: इनपुट में छोटे बदलाव से आउटपुट बहुत अलग हो जाता है\n- **अपरिवर्तनीय**: हैश को उलटकर मूल इनपुट ढूंढना गणनात्मक रूप से असंभव\n- **टक्कर प्रतिरोधी**: समान हैश उत्पन्न करने वाले दो अलग इनपुट ढूंढना बहुत कठिन\n- **कुंजी हैशिंग**: MAC कार्यक्षमता के लिए वैकल्पिक 32-बाइट कुंजी का समर्थन\n- **कुंजी व्युत्पत्ति**: कुंजी सामग्री और संदर्भ से उप-कुंजियाँ व्युत्पन्न कर सकता है\n\n**सामान्य उपयोग:**\n- फ़ाइल अखंडता सत्यापन\n- सामग्री-पता संचयन और डिडुप्लीकेशन\n- डिजिटल हस्ताक्षर और प्रमाणपत्र\n- पासवर्ड भंडारण और प्रमाणीकरण\n- क्रिप्टोग्राफ़िक प्रोटोकॉल और सिस्टम"
  },
  "tr": {
    "what-is-blake3": "BLAKE3 nedir?",
    "what-is-blake3-description-markdown": "BLAKE3, BLAKE2'den türetilmiş modern bir kriptografik hash fonksiyonudur. Güçlü güvenliği korurken çok yüksek performans ve paralellik için tasarlanmıştır. Varsayılan olarak 256 bitlik hash üretir ve genişletilebilir çıktı uzunluğunu (XOF) destekler.\n\n**Temel özellikler:**\n- **Genişletilebilir çıktı uzunluğu**: Herhangi bir uzunlukta hash üretebilir\n- **Yüksek performans**: Modern CPU'larda hızlı ve paralelleştirilebilir\n- **Deterministik**: Aynı girdi her zaman aynı hash'i üretir\n- **Çığ etkisi**: Girdideki küçük değişiklikler dramatik şekilde farklı çıktılar üretir\n- **Geri döndürülemez**: Hash'i tersine çevirerek orijinal girdiyi bulmak hesaplamalı olarak mümkün değildir\n- **Çarpışma dirençli**: Aynı hash'i üreten iki farklı girdi bulmak çok zordur\n- **Anahtarlı hash**: MAC işlevi için isteğe bağlı 32 bayt anahtarı destekler\n- **Anahtar türetme**: Anahtar malzemesi ve bağlamdan alt anahtarlar türetebilir\n\n**Yaygın kullanımlar:**\n- Dosya bütünlüğü doğrulama\n- İçerik adresli depolama ve yineleme kaldırma\n- Dijital imzalar ve sertifikalar\n- Şifre depolama ve kimlik doğrulama\n- Kriptografik protokoller ve sistemler"
  },
  "nl": {
    "what-is-blake3": "Wat is BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 is een moderne cryptografische hashfunctie die is afgeleid van BLAKE2. Het is ontworpen voor zeer hoge prestaties en parallelisme terwijl sterke veiligheid behouden blijft. Het produceert standaard een 256-bit hash en ondersteunt een uitbreidbare uitvoerlengte (XOF).\n\n**Belangrijkste kenmerken:**\n- **Uitbreidbare uitvoerlengte**: Kan hashes van elke lengte produceren\n- **Hoge prestaties**: Snel en paralleliseerbaar op moderne CPU's\n- **Deterministisch**: Dezelfde invoer produceert altijd dezelfde hash\n- **Lawine-effect**: Kleine veranderingen in de invoer produceren drastisch verschillende uitvoer\n- **Onomkeerbaar**: Computationeel onhaalbaar om de hash om te keren om de oorspronkelijke invoer te vinden\n- **Botsingsbestendig**: Zeer moeilijk om twee verschillende invoeren te vinden die dezelfde hash produceren\n- **Sleutel-hashing**: Ondersteunt een optionele 32-byte sleutel voor MAC-functionaliteit\n- **Sleutelafleiding**: Kan subsleutels afleiden uit sleutelmaterialen en context\n\n**Veelvoorkomende toepassingen:**\n- Bestandsintegriteitsverificatie\n- Content-adressering opslag en deduplicatie\n- Digitale handtekeningen en certificaten\n- Wachtwoordopslag en authenticatie\n- Cryptografische protocollen en systemen"
  },
  "sv": {
    "what-is-blake3": "Vad är BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 är en modern kryptografisk hashfunktion som härstammar från BLAKE2. Den är utformad för mycket hög prestanda och parallellism samtidigt som säkerheten är stark. Den producerar som standard en 256-bitars hash och stöder utbyggbar utdatalängd (XOF).\n\n**Nyckelegenskaper:**\n- **Utbyggbar utdatalängd**: Kan producera hasher av valfri längd\n- **Hög prestanda**: Snabb och parallelliserbar på moderna CPU:er\n- **Deterministisk**: Samma inmatning producerar alltid samma hash\n- **Lavineffekt**: Små förändringar i inmatningen ger drastiskt olika utdata\n- **Irreversibel**: Beräkningsmässigt omöjligt att vända hashen för att hitta den ursprungliga inmatningen\n- **Kollisionsresistent**: Mycket svårt att hitta två olika inmatningar som producerar samma hash\n- **Nyckel-hashing**: Stöder en valfri 32-byte-nyckel för MAC-funktionalitet\n- **Nyckelhärledning**: Kan härleda delnycklar från nyckelmaterial och kontext\n\n**Vanliga användningar:**\n- Filintegritetsverifiering\n- Innehållsadresserad lagring och deduplicering\n- Digitala signaturer och certifikat\n- Lösenordslagring och autentisering\n- Kryptografiska protokoll och system"
  },
  "pl": {
    "what-is-blake3": "Czym jest BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 to nowoczesna funkcja skrótu kryptograficznego wywodząca się z BLAKE2. Została zaprojektowana z myślą o bardzo wysokiej wydajności i równoległości przy zachowaniu silnego bezpieczeństwa. Domyślnie generuje skrót 256-bitowy i obsługuje rozszerzalną długość wyjścia (XOF).\n\n**Kluczowe cechy:**\n- **Rozszerzalna długość wyjścia**: Może generować skróty o dowolnej długości\n- **Wysoka wydajność**: Szybka i możliwa do równoleglenia na nowoczesnych CPU\n- **Deterministyczna**: To samo wejście zawsze generuje ten sam skrót\n- **Efekt lawiny**: Małe zmiany w wejściu powodują drastycznie różne wyjścia\n- **Nieodwracalna**: Obliczeniowo niemożliwe jest odwrócenie skrótu w celu znalezienia oryginalnego wejścia\n- **Odporna na kolizje**: Bardzo trudno znaleźć dwa różne wejścia dające ten sam skrót\n- **Hashing z kluczem**: Obsługuje opcjonalny 32-bajtowy klucz dla funkcji MAC\n- **Wyprowadzanie kluczy**: Może wyprowadzać podklucze z materiału klucza i kontekstu\n\n**Powszechne zastosowania:**\n- Weryfikacja integralności plików\n- Przechowywanie adresowane treścią i deduplikacja\n- Podpisy cyfrowe i certyfikaty\n- Przechowywanie i uwierzytelnianie haseł\n- Protokoły i systemy kryptograficzne"
  },
  "vi": {
    "what-is-blake3": "BLAKE3 là gì?",
    "what-is-blake3-description-markdown": "BLAKE3 là hàm băm mật mã hiện đại được dẫn xuất từ BLAKE2. Nó được thiết kế để đạt hiệu năng rất cao và hỗ trợ song song trong khi vẫn duy trì mức độ bảo mật mạnh. Nó tạo băm 256 bit theo mặc định và hỗ trợ độ dài đầu ra có thể mở rộng (XOF).\n\n**Đặc điểm chính:**\n- **Độ dài đầu ra có thể mở rộng**: Có thể tạo băm với bất kỳ độ dài nào\n- **Hiệu suất cao**: Nhanh và có thể song song hóa trên CPU hiện đại\n- **Xác định**: Cùng một đầu vào luôn tạo ra cùng một băm\n- **Hiệu ứng tuyết lở**: Thay đổi nhỏ trong đầu vào tạo ra đầu ra rất khác biệt\n- **Không thể đảo ngược**: Về mặt tính toán, không thể đảo ngược băm để tìm đầu vào gốc\n- **Chống va chạm**: Rất khó tìm hai đầu vào khác nhau tạo ra cùng một băm\n- **Băm có khóa**: Hỗ trợ khóa tùy chọn 32 byte cho chức năng MAC\n- **Dẫn xuất khóa**: Có thể dẫn xuất khóa con từ vật liệu khóa và ngữ cảnh\n\n**Sử dụng phổ biến:**\n- Xác minh tính toàn vẹn tệp\n- Lưu trữ theo địa chỉ nội dung và khử trùng lặp\n- Chữ ký số và chứng chỉ\n- Lưu trữ và xác thực mật khẩu\n- Giao thức và hệ thống mật mã"
  },
  "th": {
    "what-is-blake3": "BLAKE3 คืออะไร?",
    "what-is-blake3-description-markdown": "BLAKE3 เป็นฟังก์ชันแฮชเข้ารหัสสมัยใหม่ที่พัฒนามาจาก BLAKE2 ออกแบบมาเพื่อประสิทธิภาพสูงมากและการประมวลผลแบบขนาน โดยยังคงความปลอดภัยที่แข็งแกร่ง สร้างแฮช 256 บิตเป็นค่าเริ่มต้น และรองรับความยาวเอาต์พุตที่ขยายได้ (XOF)\n\n**คุณลักษณะสำคัญ:**\n- **ความยาวเอาต์พุตที่ขยายได้**: สามารถสร้างแฮชได้ทุกความยาว\n- **ประสิทธิภาพสูง**: รวดเร็วและสามารถทำงานแบบขนานบน CPU สมัยใหม่\n- **กำหนดได้**: อินพุตเดียวกันจะสร้างแฮชเดียวกันเสมอ\n- **เอฟเฟกต์หิมะถล่ม**: การเปลี่ยนแปลงเล็กน้อยในอินพุตทำให้เอาต์พุตต่างกันอย่างมาก\n- **ไม่สามารถย้อนกลับได้**: เป็นไปไม่ได้ในเชิงคำนวณที่จะย้อนแฮชเพื่อหาอินพุตเดิม\n- **ต้านทานการชน**: ยากมากที่จะหาสองอินพุตที่แตกต่างแต่ให้แฮชเดียวกัน\n- **แฮชแบบมีคีย์**: รองรับคีย์ 32 ไบต์แบบเลือกได้สำหรับฟังก์ชัน MAC\n- **การสกัดกุญแจ**: สามารถสกัดกุญแจย่อยจากวัสดุกุญแจและบริบท\n\n**การใช้งานทั่วไป:**\n- การตรวจสอบความสมบูรณ์ของไฟล์\n- การจัดเก็บแบบอ้างอิงเนื้อหาและการลบข้อมูลซ้ำ\n- ลายเซ็นดิจิทัลและใบรับรอง\n- การจัดเก็บและการรับรองรหัสผ่าน\n- โปรโตคอลและระบบเข้ารหัส"
  },
  "id": {
    "what-is-blake3": "Apa itu BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 adalah fungsi hash kriptografi modern yang diturunkan dari BLAKE2. Dirancang untuk performa sangat tinggi dan paralelisme sambil mempertahankan keamanan yang kuat. Ini menghasilkan hash 256-bit secara default dan mendukung panjang output yang dapat diperluas (XOF).\n\n**Karakteristik utama:**\n- **Panjang output yang dapat diperluas**: Dapat menghasilkan hash dengan panjang apa pun\n- **Performa tinggi**: Cepat dan dapat diparalelkan pada CPU modern\n- **Deterministik**: Input yang sama selalu menghasilkan hash yang sama\n- **Efek longsor**: Perubahan kecil pada input menghasilkan output yang sangat berbeda\n- **Tidak dapat dibalik**: Secara komputasi tidak mungkin membalik hash untuk menemukan input asli\n- **Tahan collision**: Sangat sulit menemukan dua input berbeda yang menghasilkan hash yang sama\n- **Hash berkunci**: Mendukung kunci opsional 32 byte untuk fungsionalitas MAC\n- **Derivasi kunci**: Dapat menurunkan subkunci dari material kunci dan konteks\n\n**Penggunaan umum:**\n- Verifikasi integritas file\n- Penyimpanan beralamat konten dan deduplikasi\n- Tanda tangan digital dan sertifikat\n- Penyimpanan dan otentikasi kata sandi\n- Protokol dan sistem kriptografi"
  },
  "he": {
    "what-is-blake3": "מה זה BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 היא פונקציית גיבוב קריפטוגרפית מודרנית שמבוססת על BLAKE2. היא תוכננה לביצועים גבוהים במיוחד ולמקביליות תוך שמירה על אבטחה חזקה. היא מפיקה כברירת מחדל גיבוב של 256 סיביות ותומכת באורך פלט ניתן להרחבה (XOF).\n\n**מאפיינים עיקריים:**\n- **אורך פלט ניתן להרחבה**: ניתן להפיק גיבובים בכל אורך\n- **ביצועים גבוהים**: מהירה וניתנת למקביליות במעבדים מודרניים\n- **דטרמיניסטית**: אותו קלט תמיד מפיק אותו גיבוב\n- **אפקט מפולת**: שינויים קטנים בקלט מפיקים פלטים שונים בתכלית\n- **בלתי הפיך**: בלתי אפשרי חישובית להפוך את הגיבוב כדי למצוא את הקלט המקורי\n- **עמיד להתנגשויות**: קשה מאוד למצוא שני קלטים שונים שמפיקים אותו גיבוב\n- **גיבוב עם מפתח**: תומך במפתח אופציונלי של 32 בתים עבור פונקציונליות MAC\n- **גזירת מפתחות**: יכול לגזור תתי-מפתחות מחומר מפתח ומהקשר\n\n**שימושים נפוצים:**\n- אימות תקינות קבצים\n- אחסון ממוען-תוכן ודדופליקציה\n- חתימות דיגיטליות ותעודות\n- אחסון ואימות סיסמאות\n- פרוטוקולים ומערכות קריפטוגרפיות"
  },
  "ms": {
    "what-is-blake3": "Apakah BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 ialah fungsi hash kriptografi moden yang terbit daripada BLAKE2. Ia direka untuk prestasi yang sangat tinggi dan selarian sambil mengekalkan keselamatan yang kukuh. Ia menghasilkan hash 256-bit secara lalai dan menyokong panjang output boleh diperluas (XOF).\n\n**Ciri-ciri utama:**\n- **Panjang output boleh diperluas**: Boleh menghasilkan hash dengan sebarang panjang\n- **Prestasi tinggi**: Pantas dan boleh diselari pada CPU moden\n- **Deterministik**: Input yang sama sentiasa menghasilkan hash yang sama\n- **Kesan runtuhan salji**: Perubahan kecil pada input menghasilkan output yang sangat berbeza\n- **Tidak boleh dibalik**: Mustahil secara pengiraan untuk membalikkan hash bagi mendapatkan input asal\n- **Tahan perlanggaran**: Sangat sukar mencari dua input berbeza yang menghasilkan hash yang sama\n- **Hash berkunci**: Menyokong kunci pilihan 32 bait untuk fungsi MAC\n- **Penerbitan kunci**: Boleh menerbitkan subkunci daripada bahan kunci dan konteks\n\n**Kegunaan biasa:**\n- Pengesahan integriti fail\n- Penyimpanan beralamat kandungan dan penyahpenduaan\n- Tandatangan digital dan sijil\n- Penyimpanan dan pengesahan kata laluan\n- Protokol dan sistem kriptografi"
  },
  "no": {
    "what-is-blake3": "Hva er BLAKE3?",
    "what-is-blake3-description-markdown": "BLAKE3 er en moderne kryptografisk hash-funksjon avledet fra BLAKE2. Den er designet for svært høy ytelse og parallellisme samtidig som sikkerheten er sterk. Den gir som standard en 256-bits hash og støtter utvidbar utdatalengde (XOF).\n\n**Nøkkelegenskaper:**\n- **Utvidbar utdatalengde**: Kan produsere hasher av hvilken som helst lengde\n- **Høy ytelse**: Rask og parallelliserbar på moderne CPU-er\n- **Deterministisk**: Samme inndata produserer alltid samme hash\n- **Snøskredeffekt**: Små endringer i inndata gir drastisk ulike utdata\n- **Irreversibel**: Beregningsmessig umulig å reversere hashen for å finne opprinnelig inndata\n- **Kollisjonsresistent**: Svært vanskelig å finne to ulike inndata som produserer samme hash\n- **Nøkkel-hashing**: Støtter en valgfri 32-byte-nøkkel for MAC-funksjonalitet\n- **Nøkkelavledning**: Kan avlede undernøkler fra nøkkelmateriale og kontekst\n\n**Vanlige bruksområder:**\n- Filintegritetsverifisering\n- Innholdsadressert lagring og deduplisering\n- Digitale signaturer og sertifikater\n- Passordlagring og autentisering\n- Kryptografiske protokoller og systemer"
  }
}
</i18n>
