<template>
  <ToolSectionHeader>{{ t('title') }}</ToolSectionHeader>

  <PDFWatermarkUploadSection
    :title="t('uploadTitle')"
    :choose-file-label="t('chooseFile')"
    :replace-file-label="t('replaceFile')"
    :clear-file-label="t('clearFile')"
    :privacy-hint="t('privacyHint')"
    :file-name-text="fileNameText"
    :page-count-text="pageCountText"
    :file-error-message="fileErrorMessage"
    :file="file"
    :is-loading-document="isLoadingDocument"
    :is-generating="isGenerating"
    @upload="handleUpload"
    @clear-file="clearFile"
  />

  <template v-if="file">
    <PDFWatermarkSettingsSection
      :title="t('settingsTitle')"
      :mode-label="t('modeLabel')"
      :text-mode-label="t('textMode')"
      :image-mode-label="t('imageMode')"
      :text-content-label="t('textContent')"
      :image-content-label="t('imageContent')"
      :text-placeholder="t('textPlaceholder')"
      :upload-image-label="t('uploadImage')"
      :replace-image-label="t('replaceImage')"
      :clear-image-label="t('clearImage')"
      :image-hint="t('imageHint')"
      :page-ranges-label="t('pageRanges')"
      :page-ranges-placeholder="t('pageRangesPlaceholder')"
      :position-label="t('position')"
      :font-family-label="t('fontFamily')"
      :font-size-label="t('fontSize')"
      :color-label="t('color')"
      :opacity-label="t('opacity')"
      :rotation-label="t('rotation')"
      :offset-x-label="t('offsetX')"
      :offset-y-label="t('offsetY')"
      :image-scale-label="t('imageScale')"
      :preview-title="t('previewTitle')"
      :preview-hint="t('previewHint')"
      :preview-load-failed="t('previewLoadFailed')"
      :range-error-message="rangeErrorMessage"
      :image-error-message="imageErrorMessage"
      :text-presets="textPresets"
      :font-family-options="fontFamilyOptions"
      :position-options="positionOptions"
      :file="file"
      :page-count="pageCount"
      :image-file="imageFile"
      :mode="mode"
      :range-input="rangeInput"
      :range-error-code="rangeErrorCode"
      :text="text"
      :font-family="fontFamily"
      :font-size="fontSize"
      :color="color"
      :opacity="opacity"
      :rotation="rotation"
      :position="position"
      :offset-x="offsetX"
      :offset-y="offsetY"
      :image-scale="imageScale"
      :is-generating="isGenerating"
      @update-mode="setMode"
      @update-range-input="setRangeInput"
      @update-text="setText"
      @preset-text="setTextPreset"
      @upload-image="handleImageUpload"
      @clear-image="clearImage"
      @update-position="setPosition"
      @update-font-family="setFontFamily"
      @update-font-size="setFontSize"
      @update-color="setColor"
      @update-opacity="setOpacity"
      @update-rotation="setRotation"
      @update-offset-x="setOffsetX"
      @update-offset-y="setOffsetY"
      @update-image-scale="setImageScale"
    />

    <PDFWatermarkGenerateSection
      :title="t('generateTitle')"
      :generate-label="t('generate')"
      :generating-label="t('generating')"
      :result-ready-label="t('resultReady')"
      :download-label="t('download')"
      :generate-error-message="generateErrorMessage"
      :is-generating="isGenerating"
      :can-generate="canGenerate"
      :has-result="hasResult"
      :result-url="resultUrl ?? null"
      :result-filename="resultFilename"
      @generate="generate"
    />
  </template>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { SelectOption } from 'naive-ui'
import { ToolSectionHeader } from '@shared/ui/tool'
import { PDF_ERROR } from '../pdf-errors'
import { PAGE_RANGE_ERROR } from '../utils/page-range'
import { usePdfWatermarkAdder } from './usePdfWatermarkAdder'
import PDFWatermarkGenerateSection from './PDFWatermarkGenerateSection.vue'
import PDFWatermarkSettingsSection from './PDFWatermarkSettingsSection.vue'
import PDFWatermarkUploadSection from './PDFWatermarkUploadSection.vue'

const { t } = useI18n({ useScope: 'local' })

const {
  file,
  pageCount,
  imageFile,
  mode,
  rangeInput,
  text,
  fontFamily,
  fontSize,
  color,
  opacity,
  rotation,
  position,
  offsetX,
  offsetY,
  imageScale,
  isLoadingDocument,
  isGenerating,
  fileErrorCode,
  imageErrorCode,
  rangeErrorCode,
  generateErrorCode,
  resultFilename,
  resultUrl,
  canGenerate,
  hasResult,
  setMode,
  setRangeInput,
  setText,
  setTextPreset,
  setFontFamily,
  setFontSize,
  setColor,
  setOpacity,
  setRotation,
  setPosition,
  setOffsetX,
  setOffsetY,
  setImageScale,
  clearFile,
  clearImage,
  handleUpload,
  handleImageUpload,
  generate,
} = usePdfWatermarkAdder()

const textPresets = ['CONFIDENTIAL', 'DRAFT', 'INTERNAL']

const fileNameText = computed(() =>
  file.value ? t('fileNameLine', { name: file.value.name }) : '',
)
const pageCountText = computed(() =>
  file.value ? t('pageCountLine', { pages: pageCount.value }) : '',
)

const fileErrorMessage = computed(() => {
  if (!fileErrorCode.value) {
    return ''
  }

  if (fileErrorCode.value === PDF_ERROR.Encrypted) {
    return t('encryptedPdfError')
  }

  return t('invalidPdfError')
})

const imageErrorMessage = computed(() => {
  if (!imageErrorCode.value) {
    return ''
  }

  return t('invalidImageError')
})

const rangeErrorMessage = computed(() => {
  if (!rangeErrorCode.value) {
    return ''
  }

  if (rangeErrorCode.value === PAGE_RANGE_ERROR.OutOfBounds) {
    return t('pageRangeOutOfBounds')
  }

  if (rangeErrorCode.value === PAGE_RANGE_ERROR.DescendingRange) {
    return t('pageRangeDescending')
  }

  if (rangeErrorCode.value === PAGE_RANGE_ERROR.DuplicatePage) {
    return t('pageRangeDuplicate')
  }

  return t('pageRangeInvalid')
})

const generateErrorMessage = computed(() => {
  if (!generateErrorCode.value) {
    return ''
  }

  if (generateErrorCode.value === PDF_ERROR.WorkerUnsupported) {
    return t('workerUnsupported')
  }

  if (generateErrorCode.value === PDF_ERROR.Encrypted) {
    return t('encryptedPdfError')
  }

  if (generateErrorCode.value === PDF_ERROR.InvalidImage) {
    return t('invalidImageError')
  }

  return t('generateFailed')
})

const fontFamilyOptions = computed<SelectOption[]>(() => [
  { label: t('fontFamilySans'), value: 'sans-serif' },
  { label: t('fontFamilySerif'), value: 'serif' },
])

const positionOptions = computed<SelectOption[]>(() => [
  { label: `↖ ${t('positionTopLeft')}`, value: 'top-left' },
  { label: `↑ ${t('positionTopCenter')}`, value: 'top-center' },
  { label: `↗ ${t('positionTopRight')}`, value: 'top-right' },
  { label: `← ${t('positionCenterLeft')}`, value: 'center-left' },
  { label: `◎ ${t('positionCenter')}`, value: 'center' },
  { label: `→ ${t('positionCenterRight')}`, value: 'center-right' },
  { label: `↙ ${t('positionBottomLeft')}`, value: 'bottom-left' },
  { label: `↓ ${t('positionBottomCenter')}`, value: 'bottom-center' },
  { label: `↘ ${t('positionBottomRight')}`, value: 'bottom-right' },
])
</script>

<!-- prettier-ignore -->
<i18n lang="json">
{
  "en":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "zh":{"title":"PDF 水印添加器","uploadTitle":"上传 PDF","chooseFile":"上传 PDF","replaceFile":"上传新的文件","clearFile":"清空 PDF","privacyHint":"文件仅在浏览器本地处理，不会上传到服务器。","fileNameLine":"文件名: {name}","pageCountLine":"页数: {pages}","invalidPdfError":"读取 PDF 文件失败，请上传有效的 PDF。","encryptedPdfError":"检测到加密 PDF，请先移除权限密码。","settingsTitle":"水印设置","modeLabel":"水印类型","textMode":"文字","imageMode":"图片","textContent":"水印文字","imageContent":"水印图片","textPlaceholder":"输入水印文字，可使用多行。","uploadImage":"上传图片","replaceImage":"替换图片","clearImage":"清空图片","imageHint":"水印图片支持 PNG 和 JPG。","pageRanges":"页面范围","pageRangesPlaceholder":"示例: 1-3,5,8-10","position":"位置","fontFamily":"字体","fontFamilySans":"无衬线 (Helvetica)","fontFamilySerif":"衬线 (Times Roman)","fontSize":"字号","color":"颜色","opacity":"透明度 (%)","rotation":"旋转角度","offsetX":"水平偏移","offsetY":"垂直偏移","imageScale":"图片宽度（占页面 %）","previewTitle":"实时预览","previewHint":"基于你上传的 PDF 实时渲染当前水印效果。","previewLoadFailed":"该 PDF 暂时无法预览。","generateTitle":"生成结果","generate":"生成带水印 PDF","generating":"生成中...","resultReady":"结果已生成：","download":"下载","workerUnsupported":"当前浏览器不支持 Web Worker。","generateFailed":"生成带水印 PDF 失败。","invalidImageError":"请上传有效的 PNG 或 JPG 水印图片。","pageRangeInvalid":"页面范围格式无效。","pageRangeOutOfBounds":"页面范围超出了 PDF 页数。","pageRangeDescending":"页面范围必须从小页码写到大页码。","pageRangeDuplicate":"每个页面只能选择一次。","positionTopLeft":"左上","positionTopCenter":"顶部居中","positionTopRight":"右上","positionCenterLeft":"左侧居中","positionCenter":"居中","positionCenterRight":"右侧居中","positionBottomLeft":"左下","positionBottomCenter":"底部居中","positionBottomRight":"右下"},
  "zh-CN":{"title":"PDF 水印添加器","uploadTitle":"上传 PDF","chooseFile":"上传 PDF","replaceFile":"上传新的文件","clearFile":"清空 PDF","privacyHint":"文件仅在浏览器本地处理，不会上传到服务器。","fileNameLine":"文件名: {name}","pageCountLine":"页数: {pages}","invalidPdfError":"读取 PDF 文件失败，请上传有效的 PDF。","encryptedPdfError":"检测到加密 PDF，请先移除权限密码。","settingsTitle":"水印设置","modeLabel":"水印类型","textMode":"文字","imageMode":"图片","textContent":"水印文字","imageContent":"水印图片","textPlaceholder":"输入水印文字，可使用多行。","uploadImage":"上传图片","replaceImage":"替换图片","clearImage":"清空图片","imageHint":"水印图片支持 PNG 和 JPG。","pageRanges":"页面范围","pageRangesPlaceholder":"示例: 1-3,5,8-10","position":"位置","fontFamily":"字体","fontFamilySans":"无衬线 (Helvetica)","fontFamilySerif":"衬线 (Times Roman)","fontSize":"字号","color":"颜色","opacity":"透明度 (%)","rotation":"旋转角度","offsetX":"水平偏移","offsetY":"垂直偏移","imageScale":"图片宽度（占页面 %）","previewTitle":"实时预览","previewHint":"基于你上传的 PDF 实时渲染当前水印效果。","previewLoadFailed":"该 PDF 暂时无法预览。","generateTitle":"生成结果","generate":"生成带水印 PDF","generating":"生成中...","resultReady":"结果已生成：","download":"下载","workerUnsupported":"当前浏览器不支持 Web Worker。","generateFailed":"生成带水印 PDF 失败。","invalidImageError":"请上传有效的 PNG 或 JPG 水印图片。","pageRangeInvalid":"页面范围格式无效。","pageRangeOutOfBounds":"页面范围超出了 PDF 页数。","pageRangeDescending":"页面范围必须从小页码写到大页码。","pageRangeDuplicate":"每个页面只能选择一次。","positionTopLeft":"左上","positionTopCenter":"顶部居中","positionTopRight":"右上","positionCenterLeft":"左侧居中","positionCenter":"居中","positionCenterRight":"右侧居中","positionBottomLeft":"左下","positionBottomCenter":"底部居中","positionBottomRight":"右下"},
  "zh-TW":{"title":"PDF 浮水印新增器","uploadTitle":"上傳 PDF","chooseFile":"上傳 PDF","replaceFile":"上傳新的檔案","clearFile":"清除 PDF","privacyHint":"檔案僅在瀏覽器本機處理，不會上傳到伺服器。","fileNameLine":"檔案名稱: {name}","pageCountLine":"頁數: {pages}","invalidPdfError":"讀取 PDF 檔案失敗，請上傳有效的 PDF。","encryptedPdfError":"偵測到加密 PDF，請先移除權限密碼。","settingsTitle":"浮水印設定","modeLabel":"浮水印類型","textMode":"文字","imageMode":"圖片","textContent":"浮水印文字","imageContent":"浮水印圖片","textPlaceholder":"輸入浮水印文字，可使用多行。","uploadImage":"上傳圖片","replaceImage":"替換圖片","clearImage":"清除圖片","imageHint":"浮水印圖片支援 PNG 和 JPG。","pageRanges":"頁面範圍","pageRangesPlaceholder":"範例: 1-3,5,8-10","position":"位置","fontFamily":"字體","fontFamilySans":"無襯線 (Helvetica)","fontFamilySerif":"襯線 (Times Roman)","fontSize":"字級","color":"顏色","opacity":"透明度 (%)","rotation":"旋轉角度","offsetX":"水平偏移","offsetY":"垂直偏移","imageScale":"圖片寬度（佔頁面 %）","previewTitle":"即時預覽","previewHint":"根據你上傳的 PDF 即時渲染目前浮水印效果。","previewLoadFailed":"此 PDF 目前無法預覽。","generateTitle":"產生結果","generate":"產生加上浮水印的 PDF","generating":"產生中...","resultReady":"結果已產生：","download":"下載","workerUnsupported":"目前瀏覽器不支援 Web Worker。","generateFailed":"產生加上浮水印的 PDF 失敗。","invalidImageError":"請上傳有效的 PNG 或 JPG 浮水印圖片。","pageRangeInvalid":"頁面範圍格式無效。","pageRangeOutOfBounds":"頁面範圍超出 PDF 頁數。","pageRangeDescending":"頁面範圍必須由小頁碼到大頁碼。","pageRangeDuplicate":"每個頁面只能選取一次。","positionTopLeft":"左上","positionTopCenter":"上方置中","positionTopRight":"右上","positionCenterLeft":"左側置中","positionCenter":"置中","positionCenterRight":"右側置中","positionBottomLeft":"左下","positionBottomCenter":"下方置中","positionBottomRight":"右下"},
  "zh-HK":{"title":"PDF 浮水印新增器","uploadTitle":"上傳 PDF","chooseFile":"上傳 PDF","replaceFile":"上傳新的檔案","clearFile":"清除 PDF","privacyHint":"檔案僅在瀏覽器本機處理，不會上傳到伺服器。","fileNameLine":"檔案名稱: {name}","pageCountLine":"頁數: {pages}","invalidPdfError":"讀取 PDF 檔案失敗，請上傳有效的 PDF。","encryptedPdfError":"偵測到加密 PDF，請先移除權限密碼。","settingsTitle":"浮水印設定","modeLabel":"浮水印類型","textMode":"文字","imageMode":"圖片","textContent":"浮水印文字","imageContent":"浮水印圖片","textPlaceholder":"輸入浮水印文字，可使用多行。","uploadImage":"上傳圖片","replaceImage":"替換圖片","clearImage":"清除圖片","imageHint":"浮水印圖片支援 PNG 和 JPG。","pageRanges":"頁面範圍","pageRangesPlaceholder":"範例: 1-3,5,8-10","position":"位置","fontFamily":"字體","fontFamilySans":"無襯線 (Helvetica)","fontFamilySerif":"襯線 (Times Roman)","fontSize":"字級","color":"顏色","opacity":"透明度 (%)","rotation":"旋轉角度","offsetX":"水平偏移","offsetY":"垂直偏移","imageScale":"圖片寬度（佔頁面 %）","previewTitle":"即時預覽","previewHint":"根據你上傳的 PDF 即時渲染目前浮水印效果。","previewLoadFailed":"此 PDF 目前無法預覽。","generateTitle":"產生結果","generate":"產生加上浮水印的 PDF","generating":"產生中...","resultReady":"結果已產生：","download":"下載","workerUnsupported":"目前瀏覽器不支援 Web Worker。","generateFailed":"產生加上浮水印的 PDF 失敗。","invalidImageError":"請上傳有效的 PNG 或 JPG 浮水印圖片。","pageRangeInvalid":"頁面範圍格式無效。","pageRangeOutOfBounds":"頁面範圍超出 PDF 頁數。","pageRangeDescending":"頁面範圍必須由小頁碼到大頁碼。","pageRangeDuplicate":"每個頁面只能選取一次。","positionTopLeft":"左上","positionTopCenter":"上方置中","positionTopRight":"右上","positionCenterLeft":"左側置中","positionCenter":"置中","positionCenterRight":"右側置中","positionBottomLeft":"左下","positionBottomCenter":"下方置中","positionBottomRight":"右下"},
  "es":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "fr":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "de":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "it":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "ja":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "ko":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "ru":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "pt":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "ar":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "hi":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "tr":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "nl":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "sv":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "pl":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "vi":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "th":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "id":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "he":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "ms":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"},
  "no":{"title":"PDF Watermark Adder","uploadTitle":"Upload PDF","chooseFile":"Upload PDF","replaceFile":"Upload a new one","clearFile":"Clear PDF","privacyHint":"Files stay in your browser. Nothing is uploaded to a server.","fileNameLine":"File name: {name}","pageCountLine":"Page count: {pages}","invalidPdfError":"Failed to read PDF file. Please upload a valid PDF.","encryptedPdfError":"Encrypted PDF detected. Please remove the owner password first.","settingsTitle":"Watermark Settings","modeLabel":"Watermark type","textMode":"Text","imageMode":"Image","textContent":"Watermark text","imageContent":"Watermark image","textPlaceholder":"Enter watermark text. You can use multiple lines.","uploadImage":"Upload image","replaceImage":"Replace image","clearImage":"Clear image","imageHint":"PNG and JPG are supported for watermark images.","pageRanges":"Page ranges","pageRangesPlaceholder":"Examples: 1-3,5,8-10","position":"Position","fontFamily":"Font family","fontFamilySans":"Sans serif (Helvetica)","fontFamilySerif":"Serif (Times Roman)","fontSize":"Font size","color":"Color","opacity":"Opacity (%)","rotation":"Rotation (deg)","offsetX":"Horizontal offset","offsetY":"Vertical offset","imageScale":"Image width (% of page)","previewTitle":"Live Preview","previewHint":"Rendered from your uploaded PDF with current watermark settings.","previewLoadFailed":"Preview unavailable for this PDF.","generateTitle":"Generate Result","generate":"Generate watermarked PDF","generating":"Generating...","resultReady":"Result ready:","download":"Download","workerUnsupported":"Your browser does not support Web Worker.","generateFailed":"Failed to generate the watermarked PDF.","invalidImageError":"Please upload a valid PNG or JPG watermark image.","pageRangeInvalid":"Invalid page range format.","pageRangeOutOfBounds":"Page range is outside the PDF page count.","pageRangeDescending":"Page ranges must go from smaller page numbers to larger ones.","pageRangeDuplicate":"Each page can only be selected once.","positionTopLeft":"Top left","positionTopCenter":"Top center","positionTopRight":"Top right","positionCenterLeft":"Center left","positionCenter":"Center","positionCenterRight":"Center right","positionBottomLeft":"Bottom left","positionBottomCenter":"Bottom center","positionBottomRight":"Bottom right"}
}
</i18n>
