<template>
  <ToolSectionHeader>{{ t('title') }}</ToolSectionHeader>
  <ToolSection>
    <n-text>{{ t('paragraph1') }}</n-text>
    <n-text style="margin-top: 8px; display: block">{{ t('paragraph2') }}</n-text>
    <n-text style="margin-top: 8px; display: block">{{ t('paragraph3') }}</n-text>
    <n-ul style="margin-top: 12px">
      <n-li>{{ t('bullet1') }}</n-li>
      <n-li>{{ t('bullet2') }}</n-li>
      <n-li>{{ t('bullet3') }}</n-li>
    </n-ul>
  </ToolSection>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { NText, NUl, NLi } from 'naive-ui'
import { ToolSection, ToolSectionHeader } from '@shared/ui/tool'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "title": "What is a CSS gradient?",
    "paragraph1": "A CSS gradient is an image generated by the browser from a smooth transition between colors. Because it is computed at render time, it scales to any size without pixelation and does not require image files.",
    "paragraph2": "Gradients come in three types: linear (direction or angle), radial (circle or ellipse from a center), and conic (a sweep around a center). Each gradient is defined by color stops; every stop can include a position and alpha to control how the colors blend.",
    "paragraph3": "Multiple gradients can be layered by separating them with commas in background-image, and you can combine them with background-blend-mode for richer textures. CSS also supports different interpolation color spaces, such as oklch, for smoother perceptual transitions.",
    "bullet1": "Linear gradients are great for lighting and directional depth.",
    "bullet2": "Radial and conic gradients are useful for spotlights, rings, and color wheels.",
    "bullet3": "Adjust stop positions to sharpen or soften transitions."
  },
  "zh": {
    "title": "什么是 CSS 渐变？",
    "paragraph1": "CSS 渐变是由浏览器根据颜色之间的平滑过渡生成的图像。由于在渲染时计算，它可以在任意尺寸下保持清晰，并且不需要图片文件。",
    "paragraph2": "渐变有三种类型：线性（方向或角度）、径向（从中心发散的圆或椭圆）以及圆锥（围绕中心旋转的扇形）。每个渐变由多个色标构成；每个色标可以包含位置和透明度来控制颜色混合。",
    "paragraph3": "多个渐变可以在 background-image 中用逗号分隔叠加，并通过 background-blend-mode 进行混合，形成更丰富的纹理。CSS 还支持不同的插值色彩空间，例如 oklch，以获得更平滑、符合感知的过渡。",
    "bullet1": "线性渐变适合表现光照和方向感。",
    "bullet2": "径向与圆锥渐变常用于聚光、光环和色轮效果。",
    "bullet3": "调整色标位置可以让过渡更清晰或更柔和。"
  },
  "zh-CN": {
    "title": "什么是 CSS 渐变？",
    "paragraph1": "CSS 渐变是由浏览器根据颜色之间的平滑过渡生成的图像。由于在渲染时计算，它可以在任意尺寸下保持清晰，并且不需要图片文件。",
    "paragraph2": "渐变有三种类型：线性（方向或角度）、径向（从中心发散的圆或椭圆）以及圆锥（围绕中心旋转的扇形）。每个渐变由多个色标构成；每个色标可以包含位置和透明度来控制颜色混合。",
    "paragraph3": "多个渐变可以在 background-image 中用逗号分隔叠加，并通过 background-blend-mode 进行混合，形成更丰富的纹理。CSS 还支持不同的插值色彩空间，例如 oklch，以获得更平滑、符合感知的过渡。",
    "bullet1": "线性渐变适合表现光照和方向感。",
    "bullet2": "径向与圆锥渐变常用于聚光、光环和色轮效果。",
    "bullet3": "调整色标位置可以让过渡更清晰或更柔和。"
  },
  "zh-TW": {
    "title": "什麼是 CSS 漸層？",
    "paragraph1": "CSS 漸層是由瀏覽器根據顏色之間的平滑過渡生成的影像。由於在渲染時計算，它可在任意尺寸下保持清晰，且不需要圖片檔案。",
    "paragraph2": "漸層有三種型態：線性（方向或角度）、放射（由中心發散的圓或橢圓）以及圓錐（繞中心旋轉的扇形）。每個漸層由多個色標構成；每個色標可包含位置與透明度來控制顏色混合。",
    "paragraph3": "多個漸層可在 background-image 中以逗號分隔堆疊，並透過 background-blend-mode 混合以形成更豐富的質感。CSS 也支援不同的插值色彩空間，例如 oklch，以獲得更平滑、符合感知的過渡。",
    "bullet1": "線性漸層適合表現光線與方向感。",
    "bullet2": "放射與圓錐漸層常用於聚光、光環與色輪效果。",
    "bullet3": "調整色標位置可讓過渡更銳利或更柔和。"
  },
  "zh-HK": {
    "title": "什麼是 CSS 漸層？",
    "paragraph1": "CSS 漸層是由瀏覽器根據顏色之間的平滑過渡生成的影像。由於在渲染時計算，它可在任意尺寸下保持清晰，且不需要圖片檔案。",
    "paragraph2": "漸層有三種型態：線性（方向或角度）、放射（由中心發散的圓或橢圓）以及圓錐（繞中心旋轉的扇形）。每個漸層由多個色標構成；每個色標可包含位置與透明度來控制顏色混合。",
    "paragraph3": "多個漸層可在 background-image 中以逗號分隔堆疊，並透過 background-blend-mode 混合以形成更豐富的質感。CSS 也支援不同的插值色彩空間，例如 oklch，以獲得更平滑、符合感知的過渡。",
    "bullet1": "線性漸層適合表現光線與方向感。",
    "bullet2": "放射與圓錐漸層常用於聚光、光環與色輪效果。",
    "bullet3": "調整色標位置可讓過渡更銳利或更柔和。"
  },
  "es": {
    "title": "¿Qué es un gradiente CSS?",
    "paragraph1": "Un gradiente CSS es una imagen generada por el navegador a partir de una transición suave entre colores. Como se calcula en tiempo de renderizado, escala a cualquier tamaño sin pixelarse y no requiere archivos de imagen.",
    "paragraph2": "Hay tres tipos: lineal (dirección o ángulo), radial (círculo o elipse desde un centro) y cónico (barrido alrededor de un centro). Cada gradiente se define con paradas de color; cada parada puede incluir posición y alfa para controlar la mezcla.",
    "paragraph3": "Se pueden apilar varios gradientes separándolos con comas en background-image y combinarlos con background-blend-mode para crear texturas más ricas. CSS también permite interpolación en espacios de color como oklch para transiciones perceptualmente más suaves.",
    "bullet1": "Los gradientes lineales son ideales para iluminación y profundidad direccional.",
    "bullet2": "Los gradientes radiales y cónicos sirven para focos, anillos y ruedas de color.",
    "bullet3": "Ajusta las posiciones de las paradas para transiciones más nítidas o más suaves."
  },
  "fr": {
    "title": "Qu'est-ce qu'un dégradé CSS ?",
    "paragraph1": "Un dégradé CSS est une image générée par le navigateur à partir d'une transition douce entre des couleurs. Comme il est calculé au rendu, il s'adapte à toute taille sans pixellisation et ne nécessite pas de fichiers image.",
    "paragraph2": "Il existe trois types : linéaire (direction ou angle), radial (cercle ou ellipse à partir d'un centre) et conique (balayage autour d'un centre). Chaque dégradé est défini par des points d'arrêt; chaque point peut inclure une position et une transparence pour contrôler le mélange.",
    "paragraph3": "On peut superposer plusieurs dégradés en les séparant par des virgules dans background-image et les combiner avec background-blend-mode pour obtenir des textures plus riches. CSS permet aussi l'interpolation dans des espaces colorimétriques comme oklch pour des transitions plus régulières.",
    "bullet1": "Les dégradés linéaires sont parfaits pour la lumière et la profondeur directionnelle.",
    "bullet2": "Les dégradés radiaux et coniques sont utiles pour des spots, des anneaux et des roues chromatiques.",
    "bullet3": "Ajustez la position des arrêts pour des transitions plus nettes ou plus douces."
  },
  "de": {
    "title": "Was ist ein CSS-Verlauf?",
    "paragraph1": "Ein CSS-Verlauf ist ein vom Browser erzeugtes Bild, das aus einem weichen Übergang zwischen Farben besteht. Da er zur Renderzeit berechnet wird, skaliert er ohne Pixelbildung in jede Größe und benötigt keine Bilddateien.",
    "paragraph2": "Es gibt drei Typen: linear (Richtung oder Winkel), radial (Kreis oder Ellipse von einem Zentrum) und konisch (eine Drehung um ein Zentrum). Jeder Verlauf wird durch Farbstopps definiert; jeder Stopp kann eine Position und Alpha enthalten, um das Mischen zu steuern.",
    "paragraph3": "Mehrere Verläufe lassen sich in background-image durch Kommas stapeln und mit background-blend-mode kombinieren, um reichere Texturen zu erzeugen. CSS unterstützt außerdem unterschiedliche Interpolationsfarbräume wie oklch für gleichmäßigere Übergänge.",
    "bullet1": "Lineare Verläufe eignen sich gut für Licht und gerichtete Tiefe.",
    "bullet2": "Radiale und konische Verläufe sind nützlich für Spotlights, Ringe und Farbräder.",
    "bullet3": "Passe Stopp-Positionen an, um Übergänge härter oder weicher zu machen."
  },
  "it": {
    "title": "Che cos'è un gradiente CSS?",
    "paragraph1": "Un gradiente CSS è un'immagine generata dal browser da una transizione morbida tra colori. Poiché viene calcolato al render, scala a qualsiasi dimensione senza pixelarsi e non richiede file immagine.",
    "paragraph2": "Esistono tre tipi: lineare (direzione o angolo), radiale (cerchio o ellisse da un centro) e conico (rotazione attorno a un centro). Ogni gradiente è definito da stop di colore; ogni stop può includere una posizione e l'alfa per controllare la miscelazione.",
    "paragraph3": "Più gradienti possono essere sovrapposti separandoli con virgole in background-image e combinati con background-blend-mode per ottenere texture più ricche. CSS supporta anche spazi colore di interpolazione come oklch per transizioni più uniformi.",
    "bullet1": "I gradienti lineari sono ideali per luce e profondità direzionale.",
    "bullet2": "I gradienti radiali e conici sono utili per riflettori, anelli e ruote dei colori.",
    "bullet3": "Regola le posizioni degli stop per transizioni più nette o più morbide."
  },
  "ja": {
    "title": "CSS グラデーションとは？",
    "paragraph1": "CSS グラデーションは、色の滑らかな変化からブラウザが生成する画像です。レンダリング時に計算されるため、どのサイズでも劣化せず、画像ファイルも不要です。",
    "paragraph2": "種類は 3 つあります。線形（方向や角度）、放射（中心から広がる円・楕円）、円錐（中心を回転する扇形）。各グラデーションは色のストップで定義され、ストップごとに位置とアルファを指定して混ざり方を調整できます。",
    "paragraph3": "複数のグラデーションは background-image にカンマ区切りで重ね、background-blend-mode で合成して質感を強化できます。CSS では oklch などの補間色空間も使えるため、知覚的に滑らかな変化が得られます。",
    "bullet1": "線形グラデーションは光の向きや奥行きの表現に最適です。",
    "bullet2": "放射・円錐グラデーションはスポットライト、リング、カラーホイールに便利です。",
    "bullet3": "ストップ位置を調整すると、境界をシャープにもソフトにもできます。"
  },
  "ko": {
    "title": "CSS 그라디언트란?",
    "paragraph1": "CSS 그라디언트는 색상 간의 부드러운 전환으로 브라우저가 생성하는 이미지입니다. 렌더링 시 계산되므로 어떤 크기에서도 깨지지 않으며 이미지 파일이 필요하지 않습니다.",
    "paragraph2": "세 가지 유형이 있습니다: 선형(방향/각도), 방사형(중심에서 퍼지는 원/타원), 원뿔형(중심을 기준으로 회전). 각 그라디언트는 컬러 스톱으로 정의되며, 스톱마다 위치와 알파를 지정해 색상 혼합을 제어할 수 있습니다.",
    "paragraph3": "background-image 에서 쉼표로 구분해 여러 그라디언트를 겹칠 수 있고, background-blend-mode 로 섞어 더 풍부한 질감을 만들 수 있습니다. CSS 는 oklch 같은 보간 색 공간도 지원해 시각적으로 더 부드러운 전환을 제공합니다.",
    "bullet1": "선형 그라디언트는 조명과 방향성 있는 깊이에 좋습니다.",
    "bullet2": "방사형과 원뿔형 그라디언트는 스포트라이트, 링, 색상 휠에 유용합니다.",
    "bullet3": "스톱 위치를 조정하면 전환을 더 선명하게 또는 부드럽게 만들 수 있습니다."
  },
  "ru": {
    "title": "Что такое CSS-градиент?",
    "paragraph1": "CSS-градиент — это изображение, которое браузер генерирует из плавного перехода между цветами. Оно вычисляется при рендеринге, поэтому масштабируется без пикселизации и не требует файлов изображений.",
    "paragraph2": "Есть три типа: линейный (направление или угол), радиальный (круг или эллипс от центра) и конический (вращение вокруг центра). Каждый градиент задаётся цветовым стопами; у каждого стопа можно указать позицию и альфу, чтобы управлять смешением.",
    "paragraph3": "Несколько градиентов можно накладывать, разделяя их запятыми в background-image, и смешивать через background-blend-mode для более богатых текстур. CSS также поддерживает интерполяцию в цветовых пространствах, например oklch, для более плавных переходов.",
    "bullet1": "Линейные градиенты хорошо подходят для света и направленной глубины.",
    "bullet2": "Радиальные и конические градиенты полезны для прожекторов, колец и цветовых кругов.",
    "bullet3": "Меняйте позиции стопов, чтобы сделать переходы резче или мягче."
  },
  "pt": {
    "title": "O que é um gradiente CSS?",
    "paragraph1": "Um gradiente CSS é uma imagem gerada pelo navegador a partir de uma transição suave entre cores. Como é calculado no momento do render, ele escala para qualquer tamanho sem pixelar e não precisa de arquivos de imagem.",
    "paragraph2": "Existem três tipos: linear (direção ou ângulo), radial (círculo ou elipse a partir de um centro) e cônico (varredura ao redor de um centro). Cada gradiente é definido por paradas de cor; cada parada pode incluir posição e alfa para controlar a mistura.",
    "paragraph3": "Vários gradientes podem ser empilhados separando-os por vírgulas em background-image e combinados com background-blend-mode para criar texturas mais ricas. O CSS também suporta interpolação em espaços de cor como oklch para transições mais suaves.",
    "bullet1": "Gradientes lineares são ótimos para iluminação e profundidade direcional.",
    "bullet2": "Gradientes radiais e cônicos são úteis para holofotes, anéis e rodas de cor.",
    "bullet3": "Ajuste as posições das paradas para transições mais nítidas ou mais suaves."
  },
  "ar": {
    "title": "ما هو تدرّج CSS؟",
    "paragraph1": "تدرّج CSS هو صورة ينشئها المتصفح من انتقال سلس بين الألوان. بما أنه يُحسب أثناء العرض، فإنه يتدرج بسلاسة لأي حجم دون تشوّه ولا يحتاج إلى ملفات صور.",
    "paragraph2": "هناك ثلاثة أنواع: خطي (اتجاه أو زاوية)، شعاعي (دائرة أو بيضوي من مركز)، ومخروطي (مسح حول مركز). يُعرَّف كل تدرّج بنقاط توقف لونية؛ ويمكن لكل نقطة تحديد الموضع والشفافية للتحكم في المزج.",
    "paragraph3": "يمكن تكديس عدة تدرجات بفصلها بفواصل في background-image، ودمجها عبر background-blend-mode للحصول على أنسجة أغنى. يدعم CSS أيضًا الاستيفاء في فضاءات لونية مثل oklch للحصول على انتقالات أكثر سلاسة إدراكيًا.",
    "bullet1": "التدرجات الخطية مناسبة للإضاءة والعمق الاتجاهي.",
    "bullet2": "التدرجات الشعاعية والمخروطية مفيدة للإضاءات الدائرية والحلقات وعجلات الألوان.",
    "bullet3": "اضبط مواضع نقاط التوقف لجعل الانتقال أكثر حدة أو نعومة."
  },
  "hi": {
    "title": "CSS ग्रेडिएंट क्या है?",
    "paragraph1": "CSS ग्रेडिएंट एक ऐसी छवि है जिसे ब्राउज़र रंगों के बीच स्मूथ ट्रांज़िशन से जनरेट करता है। यह रेंडर समय पर गणना होती है, इसलिए किसी भी आकार में बिना पिक्सेल हुए स्केल होती है और इमेज फ़ाइल की ज़रूरत नहीं पड़ती।",
    "paragraph2": "इसके तीन प्रकार हैं: लीनियर (दिशा या कोण), रेडियल (केंद्र से वृत्त या दीर्घवृत्त) और कोनिक (केंद्र के चारों ओर स्वीप)। हर ग्रेडिएंट रंग स्टॉप से परिभाषित होता है; हर स्टॉप में पोज़िशन और अल्फा देकर रंग मिश्रण नियंत्रित किया जा सकता है।",
    "paragraph3": "background-image में कॉमा से अलग करके कई ग्रेडिएंट परतों में जोड़े जा सकते हैं और background-blend-mode से मिलाकर अधिक समृद्ध टेक्सचर बनाया जा सकता है। CSS oklch जैसे कलर स्पेस में इंटरपोलेशन भी सपोर्ट करता है, जिससे ट्रांज़िशन ज़्यादा स्मूद दिखते हैं।",
    "bullet1": "लीनियर ग्रेडिएंट रोशनी और दिशा आधारित गहराई के लिए अच्छा है।",
    "bullet2": "रेडियल और कोनिक ग्रेडिएंट स्पॉटलाइट, रिंग और कलर व्हील के लिए उपयोगी हैं।",
    "bullet3": "स्टॉप पोज़िशन बदलकर ट्रांज़िशन को तेज़ या मुलायम बनाया जा सकता है।"
  },
  "tr": {
    "title": "CSS gradyanı nedir?",
    "paragraph1": "CSS gradyanı, renkler arasında yumuşak bir geçişten tarayıcı tarafından oluşturulan bir görüntüdür. Render sırasında hesaplandığı için her boyuta piksellenmeden ölçeklenir ve görüntü dosyası gerektirmez.",
    "paragraph2": "Üç tür vardır: doğrusal (yön veya açı), radyal (merkezden çıkan daire ya da elips) ve konik (merkez etrafında dönüş). Her gradyan renk duraklarıyla tanımlanır; her durakta konum ve alfa belirtilebilir.",
    "paragraph3": "Birden fazla gradyan background-image içinde virgülle ayrılarak katmanlanabilir ve background-blend-mode ile birleştirilerek daha zengin dokular elde edilebilir. CSS, oklch gibi renk uzaylarında enterpolasyon da sunar.",
    "bullet1": "Doğrusal gradyanlar ışık ve yönlü derinlik için idealdir.",
    "bullet2": "Radyal ve konik gradyanlar spot ışıkları, halkalar ve renk tekerlekleri için kullanışlıdır.",
    "bullet3": "Durak konumlarını ayarlayarak geçişleri daha keskin ya da yumuşak yapabilirsiniz."
  },
  "nl": {
    "title": "Wat is een CSS-gradient?",
    "paragraph1": "Een CSS-gradient is een door de browser gegenereerde afbeelding van een vloeiende overgang tussen kleuren. Omdat het tijdens het renderen wordt berekend, schaalt het naar elke grootte zonder te pixeleren en zijn er geen afbeeldingsbestanden nodig.",
    "paragraph2": "Er zijn drie typen: lineair (richting of hoek), radiaal (cirkel of ellips vanuit een centrum) en conisch (een veeg rondom een centrum). Elke gradient wordt gedefinieerd door kleurstops; elke stop kan een positie en alfa bevatten om het mengen te sturen.",
    "paragraph3": "Meerdere gradients kun je stapelen door ze met komma's te scheiden in background-image en combineren met background-blend-mode voor rijkere texturen. CSS ondersteunt ook interpolatie in kleurruimten zoals oklch voor vloeiendere overgangen.",
    "bullet1": "Lineaire gradients zijn ideaal voor licht en directionele diepte.",
    "bullet2": "Radiale en conische gradients zijn handig voor spotlights, ringen en kleurwielen.",
    "bullet3": "Pas stop-posities aan voor scherpere of zachtere overgangen."
  },
  "sv": {
    "title": "Vad är en CSS-gradient?",
    "paragraph1": "En CSS-gradient är en bild som webbläsaren skapar från en mjuk övergång mellan färger. Eftersom den beräknas vid rendering skalar den till alla storlekar utan att bli pixlig och kräver inga bildfiler.",
    "paragraph2": "Det finns tre typer: linjär (riktning eller vinkel), radiell (cirkel eller ellips från ett centrum) och konisk (svep runt ett centrum). Varje gradient definieras av färgstopp; varje stopp kan ange position och alfa för att styra blandningen.",
    "paragraph3": "Flera gradienter kan staplas genom att separera dem med kommatecken i background-image och kombineras med background-blend-mode för rikare texturer. CSS stödjer också interpolation i färgrymder som oklch för mjukare övergångar.",
    "bullet1": "Linjär gradient är bra för ljus och riktad djupkänsla.",
    "bullet2": "Radiella och koniska gradienter passar för spotlight, ringar och färghjul.",
    "bullet3": "Justera stoppens positioner för skarpare eller mjukare övergångar."
  },
  "pl": {
    "title": "Czym jest gradient CSS?",
    "paragraph1": "Gradient CSS to obraz generowany przez przeglądarkę z płynnego przejścia między kolorami. Ponieważ jest obliczany podczas renderowania, skaluje się do dowolnego rozmiaru bez pikselizacji i nie wymaga plików graficznych.",
    "paragraph2": "Są trzy typy: liniowy (kierunek lub kąt), radialny (okrąg lub elipsa z centrum) i stożkowy (obrót wokół centrum). Każdy gradient jest zdefiniowany przez przystanki kolorów; każdy przystanek może zawierać pozycję i alfa, aby kontrolować mieszanie.",
    "paragraph3": "Wiele gradientów można nakładać, oddzielając je przecinkami w background-image, i łączyć za pomocą background-blend-mode, aby uzyskać bogatsze tekstury. CSS obsługuje też interpolację w przestrzeniach barw, takich jak oklch, dla gładszych przejść.",
    "bullet1": "Gradienty liniowe świetnie nadają się do światła i kierunkowej głębi.",
    "bullet2": "Gradienty radialne i stożkowe są przydatne do reflektorów, pierścieni i kół barw.",
    "bullet3": "Przesuwaj pozycje przystanków, aby wyostrzyć lub zmiękczyć przejścia."
  },
  "vi": {
    "title": "CSS gradient là gì?",
    "paragraph1": "CSS gradient là một hình ảnh do trình duyệt tạo ra từ sự chuyển màu mượt mà giữa các màu. Vì được tính khi render nên nó có thể mở rộng đến mọi kích thước mà không bị vỡ và không cần tệp ảnh.",
    "paragraph2": "Có ba loại: tuyến tính (hướng hoặc góc), hướng tâm (vòng tròn hoặc elip từ tâm) và hình nón (quét quanh tâm). Mỗi gradient được định nghĩa bởi các điểm dừng màu; mỗi điểm có thể có vị trí và alpha để điều khiển việc hòa màu.",
    "paragraph3": "Bạn có thể xếp nhiều gradient bằng cách ngăn cách bằng dấu phẩy trong background-image và kết hợp bằng background-blend-mode để tạo chất liệu phong phú hơn. CSS cũng hỗ trợ nội suy trong các không gian màu như oklch để chuyển màu mượt hơn.",
    "bullet1": "Gradient tuyến tính phù hợp cho ánh sáng và chiều sâu theo hướng.",
    "bullet2": "Gradient hướng tâm và hình nón hữu ích cho đèn rọi, vòng tròn và bánh xe màu.",
    "bullet3": "Điều chỉnh vị trí điểm dừng để chuyển màu sắc nét hơn hoặc mềm hơn."
  },
  "th": {
    "title": "CSS Gradient คืออะไร?",
    "paragraph1": "CSS Gradient คือภาพที่เบราว์เซอร์สร้างจากการไล่สีอย่างนุ่มนวลระหว่างสีต่าง ๆ เนื่องจากคำนวณตอนเรนเดอร์ จึงย่อ-ขยายได้ทุกขนาดโดยไม่แตกและไม่ต้องมีไฟล์ภาพ",
    "paragraph2": "มี 3 ประเภทหลัก: แบบเชิงเส้น (ทิศทางหรือมุม), แบบรัศมี (วงกลมหรือวงรีจากจุดศูนย์กลาง) และแบบกรวย (กวาดรอบจุดศูนย์กลาง) แต่ละ gradient กำหนดด้วยจุดหยุดสี ซึ่งสามารถระบุตำแหน่งและค่าแอลฟาเพื่อควบคุมการผสมสีได้",
    "paragraph3": "สามารถซ้อนหลาย gradient ได้โดยคั่นด้วยเครื่องหมายจุลภาคใน background-image และผสมด้วย background-blend-mode เพื่อได้พื้นผิวที่ลึกขึ้น อีกทั้ง CSS ยังรองรับการอินเตอร์โพเลตในพื้นที่สีอย่าง oklch เพื่อให้การเปลี่ยนสีดูนุ่มนวลขึ้น",
    "bullet1": "Gradient เชิงเส้นเหมาะกับการแสดงแสงและความลึกตามทิศทาง",
    "bullet2": "Gradient แบบรัศมีและแบบกรวยเหมาะสำหรับสปอตไลต์ วงแหวน และวงล้อสี",
    "bullet3": "ปรับตำแหน่งจุดหยุดสีเพื่อให้การเปลี่ยนสีคมขึ้นหรือนุ่มขึ้น"
  },
  "id": {
    "title": "Apa itu gradien CSS?",
    "paragraph1": "Gradien CSS adalah gambar yang dihasilkan browser dari transisi warna yang halus. Karena dihitung saat render, ia dapat diskalakan ke ukuran apa pun tanpa pecah dan tidak memerlukan file gambar.",
    "paragraph2": "Ada tiga jenis: linear (arah atau sudut), radial (lingkaran atau elips dari pusat), dan konik (sapuan mengitari pusat). Setiap gradien ditentukan oleh titik henti warna; setiap titik dapat memiliki posisi dan alfa untuk mengatur perpaduan.",
    "paragraph3": "Beberapa gradien bisa ditumpuk dengan memisahkannya menggunakan koma di background-image dan digabung dengan background-blend-mode untuk tekstur yang lebih kaya. CSS juga mendukung interpolasi pada ruang warna seperti oklch untuk transisi yang lebih mulus.",
    "bullet1": "Gradien linear cocok untuk pencahayaan dan kedalaman terarah.",
    "bullet2": "Gradien radial dan konik berguna untuk spotlight, cincin, dan roda warna.",
    "bullet3": "Atur posisi titik henti untuk transisi yang lebih tajam atau lebih lembut."
  },
  "he": {
    "title": "מהו גרדיאנט ב-CSS?",
    "paragraph1": "גרדיאנט ב-CSS הוא תמונה שהדפדפן מייצר ממעבר חלק בין צבעים. מכיוון שהוא מחושב בזמן הרינדור, הוא מסתגל לכל גודל ללא פיקסול ואינו דורש קבצי תמונה.",
    "paragraph2": "יש שלושה סוגים: ליניארי (כיוון או זווית), רדיאלי (עיגול או אליפסה ממרכז), וקוני (סוויפ סביב מרכז). כל גרדיאנט מוגדר באמצעות נקודות עצירה של צבע; כל נקודה יכולה לכלול מיקום ו-alpha כדי לשלוט בערבוב.",
    "paragraph3": "אפשר לערום כמה גרדיאנטים על ידי הפרדה בפסיקים בתוך background-image ולשלב אותם עם background-blend-mode לטקסטורות עשירות יותר. CSS תומך גם באינטרפולציה במרחבי צבע כמו oklch לקבלת מעברים חלקים יותר מבחינה תפיסתית.",
    "bullet1": "גרדיאנטים ליניאריים מצוינים לאור ולעומק כיווני.",
    "bullet2": "גרדיאנטים רדיאליים וקוניים שימושיים לספוטים, טבעות וגלגלי צבע.",
    "bullet3": "שנו את מיקומי העצירות כדי לחדד או לרכך את המעבר."
  },
  "ms": {
    "title": "Apa itu gradien CSS?",
    "paragraph1": "Gradien CSS ialah imej yang dijana oleh pelayar daripada peralihan warna yang lembut. Kerana ia dikira semasa render, ia boleh diskalakan ke sebarang saiz tanpa piksel dan tidak memerlukan fail imej.",
    "paragraph2": "Terdapat tiga jenis: linear (arah atau sudut), radial (bulatan atau elips dari pusat), dan konik (sapuan mengelilingi pusat). Setiap gradien ditentukan oleh hentian warna; setiap hentian boleh menyertakan kedudukan dan alfa untuk mengawal campuran.",
    "paragraph3": "Berbilang gradien boleh disusun dengan memisahkannya menggunakan koma dalam background-image dan digabungkan dengan background-blend-mode untuk tekstur yang lebih kaya. CSS juga menyokong interpolasi dalam ruang warna seperti oklch untuk peralihan yang lebih licin.",
    "bullet1": "Gradien linear sesuai untuk pencahayaan dan kedalaman berarah.",
    "bullet2": "Gradien radial dan konik berguna untuk spotlight, cincin, dan roda warna.",
    "bullet3": "Laraskan kedudukan hentian untuk peralihan yang lebih tajam atau lebih lembut."
  },
  "no": {
    "title": "Hva er en CSS-gradient?",
    "paragraph1": "En CSS-gradient er et bilde som nettleseren genererer fra en myk overgang mellom farger. Siden den beregnes ved rendering, skalerer den til alle størrelser uten pikselering og trenger ingen bildefiler.",
    "paragraph2": "Det finnes tre typer: lineær (retning eller vinkel), radial (sirkel eller ellipse fra et sentrum) og konisk (sveip rundt et sentrum). Hver gradient defineres av fargestopp; hvert stopp kan inneholde posisjon og alfa for å styre blandingen.",
    "paragraph3": "Flere gradienter kan stables ved å skille dem med komma i background-image og kombineres med background-blend-mode for rikere teksturer. CSS støtter også interpolasjon i fargerom som oklch for jevnere overganger.",
    "bullet1": "Lineære gradienter er gode for lys og retningsbestemt dybde.",
    "bullet2": "Radiale og koniske gradienter er nyttige for spotlys, ringer og fargehjul.",
    "bullet3": "Juster stopp-posisjoner for skarpere eller mykere overganger."
  }
}
</i18n>
