DirectoryPath: apps/web/dist
CheckExternal: false
CheckInternal: true
CheckInternalHash: true
CheckImages: true
CheckScripts: true
CheckLinks: true
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreDirectoryMissingTrailingSlash: true
EnforceHTTPS: false
