packages:
  - packages/*
  - apps/*
  - tools/*
  - tools/**/*
  - shared/*
  - utils/*
  - registry/*

catalog:
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@commitlint/types': ^20.2.0
  '@guolao/vue-monaco-editor': ^1.6.0
  '@intlify/unplugin-vue-i18n': ^11.0.3
  '@jspawn/qpdf-wasm': ^0.0.2
  '@jsquash/oxipng': ^2.3.0
  '@playwright/test': ^1.57.0
  '@prettier/plugin-oxc': 0.1.3
  '@tsconfig/node22': ^22.0.5
  '@types/color-convert': ^2.0.4
  '@types/crypto-js': ^4.2.2
  '@types/emscripten': ^1.41.5
  '@types/js-yaml': ^4.0.9
  '@types/jsdom': ^27.0.0
  '@types/node': ^25.0.3
  '@types/papaparse': ^5.5.2
  '@types/punycode': ^2.1.4
  '@types/qrcode': ^1.5.6
  '@types/turndown': ^5.0.6
  '@types/validator': ^13.15.10
  '@unhead/vue': 2.1.1
  '@vicons/antd': ^0.13.0
  '@vicons/carbon': ^0.13.0
  '@vicons/fa': ^0.13.0
  '@vicons/fluent': ^0.13.0
  '@vicons/ionicons4': ^0.13.0
  '@vicons/ionicons5': ^0.13.0
  '@vicons/material': ^0.13.0
  '@vicons/tabler': ^0.13.0
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-istanbul': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/eslint-plugin': ^1.6.4
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': 14.1.0
  '@zip.js/zip.js': ^2.8.11
  bcrypt-ts: ^8.0.0
  bip39: ^3.1.0
  blakejs: ^1.2.1
  browser-fs-access: ^0.38.0
  buffer: ^6.0.3
  cidr-calc: ^1.0.4
  cidr-tools: ^11.0.3
  color-convert: ^3.1.3
  color-name: ^2.1.0
  comlink: ^4.4.2
  crc: ^4.3.2
  cron-parser: ^5.0.0
  cronstrue: ^3.9.0
  crypto-js: ^4.2.0
  dompurify: ^3.3.1
  eslint: ^9.39.2
  eslint-plugin-oxlint: ~1.36.0
  eslint-plugin-playwright: ^2.4.0
  eslint-plugin-vue: ~10.6.2
  filesize: ^11.0.13
  github-markdown-css: ^5.8.1
  happy-dom: ^20.0.11
  highlight.js: 11.11.1
  hono: ^4.11.3
  husky: ^9.1.7
  ip-bigint: ^8.2.2
  is-cidr: ^6.0.1
  is-ip: ^5.0.1
  jiti: ^2.6.1
  js-yaml: ^4.1.1
  jsbarcode: ^3.12.1
  jsdom: ^27.4.0
  lint-staged: ^16.2.7
  marked: ^17.0.1
  mime-types: ^3.0.2
  monaco-editor: ^0.55.1
  naive-ui: ^2.43.2
  npm-run-all2: ^8.0.4
  oxlint: ~1.36.0
  papaparse: ^5.5.3
  pinia: 3.0.4
  prettier: 3.7.4
  punycode: ^2.3.1
  qrcode: ^1.5.4
  sitemap: ^9.0.0
  smol-toml: ^1.6.0
  svgo: ^4.0.0
  turndown: ^7.2.2
  typescript: ~5.9.3
  ulid: ^3.0.2
  uuid: ^13.0.0
  validator: ^13.15.26
  vite: ^7.3.0
  vite-node: ^5.2.0
  vite-plugin-pwa: ^1.2.0
  vite-plugin-vue-devtools: ^8.0.5
  vitest: ^4.0.16
  vue: 3.5.26
  vue-i18n: 11.2.7
  vue-router: ^4.6.4
  vue-tsc: ^3.2.1
  webrtc-ips: ^0.2.0
  wrangler: 4.54.0
  xml-js: ^1.6.11
  xxhash-wasm: ^1.1.0

onlyBuiltDependencies:
  - esbuild
  - vue-demi
