packages:
  - apps/*
  - packages/*
  - tools/**

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/vue': 5.1.3
  '@iconify-json/carbon': 1.2.15
  '@iconify-json/fluent': 1.2.36
  '@unocss/astro': 66.5.10
  '@unocss/reset': 66.5.10
  astro: 5.16.6
  typescript: ^5.7.2
  unocss: 66.5.10
  vue: 3.5.26
