<template>
  <ToolSection>
    <NUl>
      <NLi>
        <NText strong>{{ t('applicationTitle') }}</NText> {{ t('applicationDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('audioTitle') }}</NText> {{ t('audioDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('fontTitle') }}</NText> {{ t('fontDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('imageTitle') }}</NText> {{ t('imageDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('messageTitle') }}</NText> {{ t('messageDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('modelTitle') }}</NText> {{ t('modelDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('textTitle') }}</NText> {{ t('textDesc') }}
      </NLi>
      <NLi>
        <NText strong>{{ t('videoTitle') }}</NText> {{ t('videoDesc') }}
      </NLi>
    </NUl>
  </ToolSection>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { NText, NUl, NLi } from 'naive-ui'
import { ToolSection } from '@shared/ui/tool'

const { t } = useI18n({ useScope: 'local' })
</script>

<i18n lang="json">
{
  "en": {
    "applicationTitle": "Application:",
    "applicationDesc": "Application files include JSON, PDF, ZIP archives, and other binary or structured data formats.",
    "audioTitle": "Audio:",
    "audioDesc": "Audio formats include MP3, WAV, OGG, and other sound file formats.",
    "fontTitle": "Font:",
    "fontDesc": "Font files include TTF, OTF, WOFF, and other font formats used for web typography.",
    "imageTitle": "Image:",
    "imageDesc": "Image formats include JPEG, PNG, GIF, SVG, and other image file formats.",
    "messageTitle": "Message:",
    "messageDesc": "Message formats include email messages and other message-based protocols.",
    "modelTitle": "Model:",
    "modelDesc": "3D model formats include GLTF, OBJ, STL, and other 3D model file formats.",
    "textTitle": "Text:",
    "textDesc": "Text formats include HTML, CSS, JavaScript, plain text, CSV, and other text-based formats.",
    "videoTitle": "Video:",
    "videoDesc": "Video formats include MP4, WebM, AVI, and other video file formats."
  },
  "zh": {
    "applicationTitle": "应用程序：",
    "applicationDesc": "应用程序文件包括 JSON、PDF、ZIP 归档文件和其他二进制或结构化数据格式。",
    "audioTitle": "音频：",
    "audioDesc": "音频格式包括 MP3、WAV、OGG 和其他声音文件格式。",
    "fontTitle": "字体：",
    "fontDesc": "字体文件包括 TTF、OTF、WOFF 和其他用于网页排版的字体格式。",
    "imageTitle": "图像：",
    "imageDesc": "图像格式包括 JPEG、PNG、GIF、SVG 和其他图像文件格式。",
    "messageTitle": "消息：",
    "messageDesc": "消息格式包括电子邮件消息和其他基于消息的协议。",
    "modelTitle": "模型：",
    "modelDesc": "3D 模型格式包括 GLTF、OBJ、STL 和其他 3D 模型文件格式。",
    "textTitle": "文本：",
    "textDesc": "文本格式包括 HTML、CSS、JavaScript、纯文本、CSV 和其他基于文本的格式。",
    "videoTitle": "视频：",
    "videoDesc": "视频格式包括 MP4、WebM、AVI 和其他视频文件格式。"
  },
  "zh-CN": {
    "applicationTitle": "应用程序：",
    "applicationDesc": "应用程序文件包括 JSON、PDF、ZIP 归档文件和其他二进制或结构化数据格式。",
    "audioTitle": "音频：",
    "audioDesc": "音频格式包括 MP3、WAV、OGG 和其他声音文件格式。",
    "fontTitle": "字体：",
    "fontDesc": "字体文件包括 TTF、OTF、WOFF 和其他用于网页排版的字体格式。",
    "imageTitle": "图像：",
    "imageDesc": "图像格式包括 JPEG、PNG、GIF、SVG 和其他图像文件格式。",
    "messageTitle": "消息：",
    "messageDesc": "消息格式包括电子邮件消息和其他基于消息的协议。",
    "modelTitle": "模型：",
    "modelDesc": "3D 模型格式包括 GLTF、OBJ、STL 和其他 3D 模型文件格式。",
    "textTitle": "文本：",
    "textDesc": "文本格式包括 HTML、CSS、JavaScript、纯文本、CSV 和其他基于文本的格式。",
    "videoTitle": "视频：",
    "videoDesc": "视频格式包括 MP4、WebM、AVI 和其他视频文件格式。"
  },
  "zh-TW": {
    "applicationTitle": "應用程式：",
    "applicationDesc": "應用程式檔案包括 JSON、PDF、ZIP 壓縮檔和其他二進位或結構化資料格式。",
    "audioTitle": "音訊：",
    "audioDesc": "音訊格式包括 MP3、WAV、OGG 和其他聲音檔案格式。",
    "fontTitle": "字型：",
    "fontDesc": "字型檔案包括 TTF、OTF、WOFF 和其他用於網頁排版的字型格式。",
    "imageTitle": "影像：",
    "imageDesc": "影像格式包括 JPEG、PNG、GIF、SVG 和其他影像檔案格式。",
    "messageTitle": "訊息：",
    "messageDesc": "訊息格式包括電子郵件訊息和其他基於訊息的協定。",
    "modelTitle": "模型：",
    "modelDesc": "3D 模型格式包括 GLTF、OBJ、STL 和其他 3D 模型檔案格式。",
    "textTitle": "文字：",
    "textDesc": "文字格式包括 HTML、CSS、JavaScript、純文字、CSV 和其他基於文字的格式。",
    "videoTitle": "影片：",
    "videoDesc": "影片格式包括 MP4、WebM、AVI 和其他影片檔案格式。"
  },
  "zh-HK": {
    "applicationTitle": "應用程式：",
    "applicationDesc": "應用程式檔案包括 JSON、PDF、ZIP 壓縮檔和其他二進位或結構化資料格式。",
    "audioTitle": "音訊：",
    "audioDesc": "音訊格式包括 MP3、WAV、OGG 和其他聲音檔案格式。",
    "fontTitle": "字型：",
    "fontDesc": "字型檔案包括 TTF、OTF、WOFF 和其他用於網頁排版的字型格式。",
    "imageTitle": "影像：",
    "imageDesc": "影像格式包括 JPEG、PNG、GIF、SVG 和其他影像檔案格式。",
    "messageTitle": "訊息：",
    "messageDesc": "訊息格式包括電子郵件訊息和其他基於訊息的協定。",
    "modelTitle": "模型：",
    "modelDesc": "3D 模型格式包括 GLTF、OBJ、STL 和其他 3D 模型檔案格式。",
    "textTitle": "文字：",
    "textDesc": "文字格式包括 HTML、CSS、JavaScript、純文字、CSV 和其他基於文字的格式。",
    "videoTitle": "影片：",
    "videoDesc": "影片格式包括 MP4、WebM、AVI 和其他影片檔案格式。"
  },
  "es": {
    "applicationTitle": "Aplicación:",
    "applicationDesc": "Los archivos de aplicación incluyen JSON, PDF, archivos ZIP y otros formatos de datos binarios o estructurados.",
    "audioTitle": "Audio:",
    "audioDesc": "Los formatos de audio incluyen MP3, WAV, OGG y otros formatos de archivos de sonido.",
    "fontTitle": "Fuente:",
    "fontDesc": "Los archivos de fuente incluyen TTF, OTF, WOFF y otros formatos de fuente utilizados para tipografía web.",
    "imageTitle": "Imagen:",
    "imageDesc": "Los formatos de imagen incluyen JPEG, PNG, GIF, SVG y otros formatos de archivos de imagen.",
    "messageTitle": "Mensaje:",
    "messageDesc": "Los formatos de mensaje incluyen mensajes de correo electrónico y otros protocolos basados en mensajes.",
    "modelTitle": "Modelo:",
    "modelDesc": "Los formatos de modelo 3D incluyen GLTF, OBJ, STL y otros formatos de archivos de modelo 3D.",
    "textTitle": "Texto:",
    "textDesc": "Los formatos de texto incluyen HTML, CSS, JavaScript, texto plano, CSV y otros formatos basados en texto.",
    "videoTitle": "Video:",
    "videoDesc": "Los formatos de video incluyen MP4, WebM, AVI y otros formatos de archivos de video."
  },
  "fr": {
    "applicationTitle": "Application :",
    "applicationDesc": "Les fichiers d'application incluent JSON, PDF, archives ZIP et d'autres formats de données binaires ou structurés.",
    "audioTitle": "Audio :",
    "audioDesc": "Les format audio incluent MP3, WAV, OGG et d'autres formats de fichiers audio.",
    "fontTitle": "Police :",
    "fontDesc": "Les fichiers de police incluent TTF, OTF, WOFF et d'autres formats de police utilisés pour la typographie web.",
    "imageTitle": "Image :",
    "imageDesc": "Les formats d'image incluent JPEG, PNG, GIF, SVG et d'autres formats de fichiers image.",
    "messageTitle": "Message :",
    "messageDesc": "Les formats de message incluent les messages électroniques et d'autres protocoles basés sur les messages.",
    "modelTitle": "Modèle :",
    "modelDesc": "Les formats de modèle 3D incluent GLTF, OBJ, STL et d'autres formats de fichiers de modèle 3D.",
    "textTitle": "Texte :",
    "textDesc": "Les formats de texte incluent HTML, CSS, JavaScript, texte brut, CSV et d'autres formats basés sur le texte.",
    "videoTitle": "Vidéo :",
    "videoDesc": "Les formats vidéo incluent MP4, WebM, AVI et d'autres formats de fichiers vidéo."
  },
  "de": {
    "applicationTitle": "Anwendung:",
    "applicationDesc": "Anwendungsdateien umfassen JSON, PDF, ZIP-Archive und andere binäre oder strukturierte Datenformate.",
    "audioTitle": "Audio:",
    "audioDesc": "Audioformate umfassen MP3, WAV, OGG und andere Sounddateiformate.",
    "fontTitle": "Schriftart:",
    "fontDesc": "Schriftartdateien umfassen TTF, OTF, WOFF und andere Schriftartformate, die für Webtypografie verwendet werden.",
    "imageTitle": "Bild:",
    "imageDesc": "Bildformate umfassen JPEG, PNG, GIF, SVG und andere Bilddateiformate.",
    "messageTitle": "Nachricht:",
    "messageDesc": "Nachrichtenformate umfassen E-Mail-Nachrichten und andere nachrichtenbasierte Protokolle.",
    "modelTitle": "Modell:",
    "modelDesc": "3D-Modellformate umfassen GLTF, OBJ, STL und andere 3D-Modell-Dateiformate.",
    "textTitle": "Text:",
    "textDesc": "Textformate umfassen HTML, CSS, JavaScript, Klartext, CSV und andere textbasierte Formate.",
    "videoTitle": "Video:",
    "videoDesc": "Videoformate umfassen MP4, WebM, AVI und andere Videodateiformate."
  },
  "it": {
    "applicationTitle": "Applicazione:",
    "applicationDesc": "I file applicazione includono JSON, PDF, archivi ZIP e altri formati di dati binari o strutturati.",
    "audioTitle": "Audio:",
    "audioDesc": "I formati audio includono MP3, WAV, OGG e altri formati di file audio.",
    "fontTitle": "Carattere:",
    "fontDesc": "I file carattere includono TTF, OTF, WOFF e altri formati di carattere utilizzati per la tipografia web.",
    "imageTitle": "Immagine:",
    "imageDesc": "I formati immagine includono JPEG, PNG, GIF, SVG e altri formati di file immagine.",
    "messageTitle": "Messaggio:",
    "messageDesc": "I formati messaggio includono messaggi di posta elettronica e altri protocolli basati su messaggi.",
    "modelTitle": "Modello:",
    "modelDesc": "I formati modello 3D includono GLTF, OBJ, STL e altri formati di file modello 3D.",
    "textTitle": "Testo:",
    "textDesc": "I formati testo includono HTML, CSS, JavaScript, testo semplice, CSV e altri formati basati su testo.",
    "videoTitle": "Video:",
    "videoDesc": "I formati video includono MP4, WebM, AVI e altri formati di file video."
  },
  "ja": {
    "applicationTitle": "アプリケーション：",
    "applicationDesc": "アプリケーションファイルには、JSON、PDF、ZIP アーカイブ、その他のバイナリまたは構造化データ形式が含まれます。",
    "audioTitle": "オーディオ：",
    "audioDesc": "オーディオ形式には、MP3、WAV、OGG、その他の音声ファイル形式が含まれます。",
    "fontTitle": "フォント：",
    "fontDesc": "フォントファイルには、Web タイポグラフィに使用される TTF、OTF、WOFF、その他のフォント形式が含まれます。",
    "imageTitle": "画像：",
    "imageDesc": "画像形式には、JPEG、PNG、GIF、SVG、その他の画像ファイル形式が含まれます。",
    "messageTitle": "メッセージ：",
    "messageDesc": "メッセージ形式には、電子メールメッセージやその他のメッセージベースのプロトコルが含まれます。",
    "modelTitle": "モデル：",
    "modelDesc": "3D モデル形式には、GLTF、OBJ、STL、その他の 3D モデルファイル形式が含まれます。",
    "textTitle": "テキスト：",
    "textDesc": "テキスト形式には、HTML、CSS、JavaScript、プレーンテキスト、CSV、その他のテキストベースの形式が含まれます。",
    "videoTitle": "ビデオ：",
    "videoDesc": "ビデオ形式には、MP4、WebM、AVI、その他のビデオファイル形式が含まれます。"
  },
  "ko": {
    "applicationTitle": "애플리케이션:",
    "applicationDesc": "애플리케이션 파일에는 JSON, PDF, ZIP 아카이브 및 기타 이진 또는 구조화된 데이터 형식이 포함됩니다.",
    "audioTitle": "오디오:",
    "audioDesc": "오디오 형식에는 MP3, WAV, OGG 및 기타 사운드 파일 형식이 포함됩니다.",
    "fontTitle": "글꼴:",
    "fontDesc": "글꼴 파일에는 웹 타이포그래피에 사용되는 TTF, OTF, WOFF 및 기타 글꼴 형식이 포함됩니다.",
    "imageTitle": "이미지:",
    "imageDesc": "이미지 형식에는 JPEG, PNG, GIF, SVG 및 기타 이미지 파일 형식이 포함됩니다.",
    "messageTitle": "메시지:",
    "messageDesc": "메시지 형식에는 이메일 메시지 및 기타 메시지 기반 프로토콜이 포함됩니다.",
    "modelTitle": "모델:",
    "modelDesc": "3D 모델 형식에는 GLTF, OBJ, STL 및 기타 3D 모델 파일 형식이 포함됩니다.",
    "textTitle": "텍스트:",
    "textDesc": "텍스트 형식에는 HTML, CSS, JavaScript, 일반 텍스트, CSV 및 기타 텍스트 기반 형식이 포함됩니다.",
    "videoTitle": "비디오:",
    "videoDesc": "비디오 형식에는 MP4, WebM, AVI 및 기타 비디오 파일 형식이 포함됩니다."
  },
  "ru": {
    "applicationTitle": "Приложение:",
    "applicationDesc": "Файлы приложений включают JSON, PDF, ZIP-архивы и другие двоичные или структурированные форматы данных.",
    "audioTitle": "Аудио:",
    "audioDesc": "Аудиоформаты включают MP3, WAV, OGG и другие форматы звуковых файлов.",
    "fontTitle": "Шрифт:",
    "fontDesc": "Файлы шрифтов включают TTF, OTF, WOFF и другие форматы шрифтов, используемые для веб-типографики.",
    "imageTitle": "Изображение:",
    "imageDesc": "Форматы изображений включают JPEG, PNG, GIF, SVG и другие форматы файлов изображений.",
    "messageTitle": "Сообщение:",
    "messageDesc": "Форматы сообщений включают электронные письма и другие протоколы на основе сообщений.",
    "modelTitle": "Модель:",
    "modelDesc": "Форматы 3D-моделей включают GLTF, OBJ, STL и другие форматы файлов 3D-моделей.",
    "textTitle": "Текст:",
    "textDesc": "Текстовые форматы включают HTML, CSS, JavaScript, обычный текст, CSV и другие текстовые форматы.",
    "videoTitle": "Видео:",
    "videoDesc": "Видеоформаты включают MP4, WebM, AVI и другие форматы видеофайлов."
  },
  "pt": {
    "applicationTitle": "Aplicação:",
    "applicationDesc": "Os arquivos de aplicação incluem JSON, PDF, arquivos ZIP e outros formatos de dados binários ou estruturados.",
    "audioTitle": "Áudio:",
    "audioDesc": "Os formatos de áudio incluem MP3, WAV, OGG e outros formatos de arquivos de som.",
    "fontTitle": "Fonte:",
    "fontDesc": "Os arquivos de fonte incluem TTF, OTF, WOFF e outros formatos de fonte usados para tipografia web.",
    "imageTitle": "Imagem:",
    "imageDesc": "Os formatos de imagem incluem JPEG, PNG, GIF, SVG e outros formatos de arquivos de imagem.",
    "messageTitle": "Mensagem:",
    "messageDesc": "Os formatos de mensagem incluem mensagens de e-mail e outros protocolos baseados em mensagens.",
    "modelTitle": "Modelo:",
    "modelDesc": "Os formatos de modelo 3D incluem GLTF, OBJ, STL e outros formatos de arquivos de modelo 3D.",
    "textTitle": "Texto:",
    "textDesc": "Os formatos de texto incluem HTML, CSS, JavaScript, texto simples, CSV e outros formatos baseados em texto.",
    "videoTitle": "Vídeo:",
    "videoDesc": "Os formatos de vídeo incluem MP4, WebM, AVI e outros formatos de arquivos de vídeo."
  },
  "ar": {
    "applicationTitle": "التطبيق:",
    "applicationDesc": "تتضمن ملفات التطبيق JSON و PDF وأرشيفات ZIP وتنسيقات البيانات الثنائية أو المهيكلة الأخرى.",
    "audioTitle": "الصوت:",
    "audioDesc": "تتضمن تنسيقات الصوت MP3 و WAV و OGG وتنسيقات ملفات الصوت الأخرى.",
    "fontTitle": "الخط:",
    "fontDesc": "تتضمن ملفات الخط TTF و OTF و WOFF وتنسيقات الخطوط الأخرى المستخدمة في طباعة الويب.",
    "imageTitle": "الصورة:",
    "imageDesc": "تتضمن تنسيقات الصور JPEG و PNG و GIF و SVG وتنسيقات ملفات الصور الأخرى.",
    "messageTitle": "الرسالة:",
    "messageDesc": "تتضمن تنسيقات الرسائل رسائل البريد الإلكتروني والبروتوكولات الأخرى القائمة على الرسائل.",
    "modelTitle": "النموذج:",
    "modelDesc": "تتضمن تنسيقات النماذج ثلاثية الأبعاد GLTF و OBJ و STL وتنسيقات ملفات النماذج ثلاثية الأبعاد الأخرى.",
    "textTitle": "النص:",
    "textDesc": "تتضمن تنسيقات النص HTML و CSS و JavaScript والنص العادي و CSV والتنسيقات الأخرى القائمة على النص.",
    "videoTitle": "الفيديو:",
    "videoDesc": "تتضمن تنسيقات الفيديو MP4 و WebM و AVI وتنسيقات ملفات الفيديو الأخرى."
  },
  "hi": {
    "applicationTitle": "एप्लिकेशन:",
    "applicationDesc": "एप्लिकेशन फ़ाइलों में JSON, PDF, ZIP संग्रह और अन्य बाइनरी या संरचित डेटा प्रारूप शामिल हैं।",
    "audioTitle": "ऑडियो:",
    "audioDesc": "ऑडियो प्रारूपों में MP3, WAV, OGG और अन्य ध्वनि फ़ाइल प्रारूप शामिल हैं।",
    "fontTitle": "फ़ॉन्ट:",
    "fontDesc": "फ़ॉन्ट फ़ाइलों में TTF, OTF, WOFF और वेब टाइपोग्राफी के लिए उपयोग किए जाने वाले अन्य फ़ॉन्ट प्रारूप शामिल हैं।",
    "imageTitle": "छवि:",
    "imageDesc": "छवि प्रारूपों में JPEG, PNG, GIF, SVG और अन्य छवि फ़ाइल प्रारूप शामिल हैं।",
    "messageTitle": "संदेश:",
    "messageDesc": "संदेश प्रारूपों में ईमेल संदेश और अन्य संदेश-आधारित प्रोटोकॉल शामिल हैं।",
    "modelTitle": "मॉडल:",
    "modelDesc": "3D मॉडल प्रारूपों में GLTF, OBJ, STL और अन्य 3D मॉडल फ़ाइल प्रारूप शामिल हैं।",
    "textTitle": "पाठ:",
    "textDesc": "पाठ प्रारूपों में HTML, CSS, JavaScript, सादा पाठ, CSV और अन्य पाठ-आधारित प्रारूप शामिल हैं।",
    "videoTitle": "वीडियो:",
    "videoDesc": "वीडियो प्रारूपों में MP4, WebM, AVI और अन्य वीडियो फ़ाइल प्रारूप शामिल हैं।"
  },
  "tr": {
    "applicationTitle": "Uygulama:",
    "applicationDesc": "Uygulama dosyaları JSON, PDF, ZIP arşivleri ve diğer ikili veya yapılandırılmış veri biçimlerini içerir.",
    "audioTitle": "Ses:",
    "audioDesc": "Ses biçimleri MP3, WAV, OGG ve diğer ses dosyası biçimlerini içerir.",
    "fontTitle": "Yazı Tipi:",
    "fontDesc": "Yazı tipi dosyaları, web tipografisi için kullanılan TTF, OTF, WOFF ve diğer yazı tipi biçimlerini içerir.",
    "imageTitle": "Görüntü:",
    "imageDesc": "Görüntü biçimleri JPEG, PNG, GIF, SVG ve diğer görüntü dosyası biçimlerini içerir.",
    "messageTitle": "İleti:",
    "messageDesc": "İleti biçimleri e-posta iletileri ve diğer ileti tabanlı protokolleri içerir.",
    "modelTitle": "Model:",
    "modelDesc": "3D model biçimleri GLTF, OBJ, STL ve diğer 3D model dosyası biçimlerini içerir.",
    "textTitle": "Metin:",
    "textDesc": "Metin biçimleri HTML, CSS, JavaScript, düz metin, CSV ve diğer metin tabanlı biçimleri içerir.",
    "videoTitle": "Video:",
    "videoDesc": "Video biçimleri MP4, WebM, AVI ve diğer video dosyası biçimlerini içerir."
  },
  "nl": {
    "applicationTitle": "Applicatie:",
    "applicationDesc": "Applicatiebestanden omvatten JSON, PDF, ZIP-archieven en andere binaire of gestructureerde gegevensformaten.",
    "audioTitle": "Audio:",
    "audioDesc": "Audioformaten omvatten MP3, WAV, OGG en andere geluidsbestandsformaten.",
    "fontTitle": "Lettertype:",
    "fontDesc": "Lettertypebestanden omvatten TTF, OTF, WOFF en andere lettertypeformaten die worden gebruikt voor webtypografie.",
    "imageTitle": "Afbeelding:",
    "imageDesc": "Afbeeldingsformaten omvatten JPEG, PNG, GIF, SVG en andere afbeeldingsbestandsformaten.",
    "messageTitle": "Bericht:",
    "messageDesc": "Berichtformaten omvatten e-mailberichten en andere berichtgebaseerde protocollen.",
    "modelTitle": "Model:",
    "modelDesc": "3D-modelformaten omvatten GLTF, OBJ, STL en andere 3D-modelbestandsformaten.",
    "textTitle": "Tekst:",
    "textDesc": "Tekstformaten omvatten HTML, CSS, JavaScript, platte tekst, CSV en andere tekstgebaseerde formaten.",
    "videoTitle": "Video:",
    "videoDesc": "Videoformaten omvatten MP4, WebM, AVI en andere videobestandsformaten."
  },
  "sv": {
    "applicationTitle": "Applikation:",
    "applicationDesc": "Applikationsfiler inkluderar JSON, PDF, ZIP-arkiv och andra binära eller strukturerade dataformat.",
    "audioTitle": "Ljud:",
    "audioDesc": "Ljudformat inkluderar MP3, WAV, OGG och andra ljudfilformat.",
    "fontTitle": "Teckensnitt:",
    "fontDesc": "Teckensnittsfiler inkluderar TTF, OTF, WOFF och andra teckensnittsformat som används för webbtypografi.",
    "imageTitle": "Bild:",
    "imageDesc": "Bildformat inkluderar JPEG, PNG, GIF, SVG och andra bildfilformat.",
    "messageTitle": "Meddelande:",
    "messageDesc": "Meddelandeformat inkluderar e-postmeddelanden och andra meddelandebaserade protokoll.",
    "modelTitle": "Modell:",
    "modelDesc": "3D-modellformat inkluderar GLTF, OBJ, STL och andra 3D-modellfilformat.",
    "textTitle": "Text:",
    "textDesc": "Textformat inkluderar HTML, CSS, JavaScript, ren text, CSV och andra textbaserade format.",
    "videoTitle": "Video:",
    "videoDesc": "Videoformat inkluderar MP4, WebM, AVI och andra videofilformat."
  },
  "pl": {
    "applicationTitle": "Aplikacja:",
    "applicationDesc": "Pliki aplikacji obejmują JSON, PDF, archiwa ZIP i inne binarne lub strukturalne formaty danych.",
    "audioTitle": "Audio:",
    "audioDesc": "Formaty audio obejmują MP3, WAV, OGG i inne formaty plików dźwiękowych.",
    "fontTitle": "Czcionka:",
    "fontDesc": "Pliki czcionek obejmują TTF, OTF, WOFF i inne formaty czcionek używane do typografii internetowej.",
    "imageTitle": "Obraz:",
    "imageDesc": "Formaty obrazów obejmują JPEG, PNG, GIF, SVG i inne formaty plików obrazów.",
    "messageTitle": "Wiadomość:",
    "messageDesc": "Formaty wiadomości obejmują wiadomości e-mail i inne protokoły oparte na wiadomościach.",
    "modelTitle": "Model:",
    "modelDesc": "Formaty modeli 3D obejmują GLTF, OBJ, STL i inne formaty plików modeli 3D.",
    "textTitle": "Tekst:",
    "textDesc": "Formaty tekstowe obejmują HTML, CSS, JavaScript, zwykły tekst, CSV i inne formaty oparte na tekście.",
    "videoTitle": "Wideo:",
    "videoDesc": "Formaty wideo obejmują MP4, WebM, AVI i inne formaty plików wideo."
  },
  "vi": {
    "applicationTitle": "Ứng dụng:",
    "applicationDesc": "Tệp ứng dụng bao gồm JSON, PDF, kho lưu trữ ZIP và các định dạng dữ liệu nhị phân hoặc có cấu trúc khác.",
    "audioTitle": "Âm thanh:",
    "audioDesc": "Định dạng âm thanh bao gồm MP3, WAV, OGG và các định dạng tệp âm thanh khác.",
    "fontTitle": "Phông chữ:",
    "fontDesc": "Tệp phông chữ bao gồm TTF, OTF, WOFF và các định dạng phông chữ khác được sử dụng cho kiểu chữ web.",
    "imageTitle": "Hình ảnh:",
    "imageDesc": "Định dạng hình ảnh bao gồm JPEG, PNG, GIF, SVG và các định dạng tệp hình ảnh khác.",
    "messageTitle": "Tin nhắn:",
    "messageDesc": "Định dạng tin nhắn bao gồm tin nhắn email và các giao thức dựa trên tin nhắn khác.",
    "modelTitle": "Mô hình:",
    "modelDesc": "Định dạng mô hình 3D bao gồm GLTF, OBJ, STL và các định dạng tệp mô hình 3D khác.",
    "textTitle": "Văn bản:",
    "textDesc": "Định dạng văn bản bao gồm HTML, CSS, JavaScript, văn bản thuần túy, CSV và các định dạng dựa trên văn bản khác.",
    "videoTitle": "Video:",
    "videoDesc": "Định dạng video bao gồm MP4, WebM, AVI và các định dạng tệp video khác."
  },
  "th": {
    "applicationTitle": "แอปพลิเคชัน:",
    "applicationDesc": "ไฟล์แอปพลิเคชันรวมถึง JSON, PDF, ไฟล์ ZIP และรูปแบบข้อมูลไบนารีหรือมีโครงสร้างอื่นๆ",
    "audioTitle": "เสียง:",
    "audioDesc": "รูปแบบเสียงรวมถึง MP3, WAV, OGG และรูปแบบไฟล์เสียงอื่นๆ",
    "fontTitle": "ฟอนต์:",
    "fontDesc": "ไฟล์ฟอนต์รวมถึง TTF, OTF, WOFF และรูปแบบฟอนต์อื่นๆ ที่ใช้สำหรับการจัดรูปแบบตัวอักษรบนเว็บ",
    "imageTitle": "รูปภาพ:",
    "imageDesc": "รูปแบบรูปภาพรวมถึง JPEG, PNG, GIF, SVG และรูปแบบไฟล์รูปภาพอื่นๆ",
    "messageTitle": "ข้อความ:",
    "messageDesc": "รูปแบบข้อความรวมถึงข้อความอีเมลและโปรโตคอลอื่นๆ ที่ใช้ข้อความ",
    "modelTitle": "โมเดล:",
    "modelDesc": "รูปแบบโมเดล 3D รวมถึง GLTF, OBJ, STL และรูปแบบไฟล์โมเดล 3D อื่นๆ",
    "textTitle": "ข้อความ:",
    "textDesc": "รูปแบบข้อความรวมถึง HTML, CSS, JavaScript, ข้อความธรรมดา, CSV และรูปแบบอื่นๆ ที่ใช้ข้อความ",
    "videoTitle": "วิดีโอ:",
    "videoDesc": "รูปแบบวิดีโอรวมถึง MP4, WebM, AVI และรูปแบบไฟล์วิดีโออื่นๆ"
  },
  "id": {
    "applicationTitle": "Aplikasi:",
    "applicationDesc": "File aplikasi mencakup JSON, PDF, arsip ZIP, dan format data biner atau terstruktur lainnya.",
    "audioTitle": "Audio:",
    "audioDesc": "Format audio mencakup MP3, WAV, OGG, dan format file suara lainnya.",
    "fontTitle": "Font:",
    "fontDesc": "File font mencakup TTF, OTF, WOFF, dan format font lainnya yang digunakan untuk tipografi web.",
    "imageTitle": "Gambar:",
    "imageDesc": "Format gambar mencakup JPEG, PNG, GIF, SVG, dan format file gambar lainnya.",
    "messageTitle": "Pesan:",
    "messageDesc": "Format pesan mencakup pesan email dan protokol berbasis pesan lainnya.",
    "modelTitle": "Model:",
    "modelDesc": "Format model 3D mencakup GLTF, OBJ, STL, dan format file model 3D lainnya.",
    "textTitle": "Teks:",
    "textDesc": "Format teks mencakup HTML, CSS, JavaScript, teks biasa, CSV, dan format berbasis teks lainnya.",
    "videoTitle": "Video:",
    "videoDesc": "Format video mencakup MP4, WebM, AVI, dan format file video lainnya."
  },
  "he": {
    "applicationTitle": "יישום:",
    "applicationDesc": "קבצי יישום כוללים JSON, PDF, ארכיוני ZIP ופורמטי נתונים בינאריים או מובנים אחרים.",
    "audioTitle": "אודיו:",
    "audioDesc": "פורמטי אודיו כוללים MP3, WAV, OGG ופורמטי קבצי קול אחרים.",
    "fontTitle": "גופן:",
    "fontDesc": "קבצי גופן כוללים TTF, OTF, WOFF ופורמטי גופנים אחרים המשמשים לטיפוגרפיה באינטרנט.",
    "imageTitle": "תמונה:",
    "imageDesc": "פורמטי תמונות כוללים JPEG, PNG, GIF, SVG ופורמטי קבצי תמונות אחרים.",
    "messageTitle": "הודעה:",
    "messageDesc": "פורמטי הודעות כוללים הודעות דוא\"ל ופרוטוקולים אחרים המבוססים על הודעות.",
    "modelTitle": "מודל:",
    "modelDesc": "פורמטי מודלים תלת-ממדיים כוללים GLTF, OBJ, STL ופורמטי קבצי מודלים תלת-ממדיים אחרים.",
    "textTitle": "טקסט:",
    "textDesc": "פורמטי טקסט כוללים HTML, CSS, JavaScript, טקסט רגיל, CSV ופורמטים אחרים המבוססים על טקסט.",
    "videoTitle": "וידאו:",
    "videoDesc": "פורמטי וידאו כוללים MP4, WebM, AVI ופורמטי קבצי וידאו אחרים."
  },
  "ms": {
    "applicationTitle": "Aplikasi:",
    "applicationDesc": "Fail aplikasi termasuk JSON, PDF, arkib ZIP dan format data binari atau berstruktur lain.",
    "audioTitle": "Audio:",
    "audioDesc": "Format audio termasuk MP3, WAV, OGG dan format fail bunyi lain.",
    "fontTitle": "Fon:",
    "fontDesc": "Fail fon termasuk TTF, OTF, WOFF dan format fon lain yang digunakan untuk tipografi web.",
    "imageTitle": "Imej:",
    "imageDesc": "Format imej termasuk JPEG, PNG, GIF, SVG dan format fail imej lain.",
    "messageTitle": "Mesej:",
    "messageDesc": "Format mesej termasuk mesej e-mel dan protokol berasaskan mesej lain.",
    "modelTitle": "Model:",
    "modelDesc": "Format model 3D termasuk GLTF, OBJ, STL dan format fail model 3D lain.",
    "textTitle": "Teks:",
    "textDesc": "Format teks termasuk HTML, CSS, JavaScript, teks biasa, CSV dan format berasaskan teks lain.",
    "videoTitle": "Video:",
    "videoDesc": "Format video termasuk MP4, WebM, AVI dan format fail video lain."
  },
  "no": {
    "applicationTitle": "Applikasjon:",
    "applicationDesc": "Applikasjonsfiler inkluderer JSON, PDF, ZIP-arkiver og andre binære eller strukturerte dataformater.",
    "audioTitle": "Lyd:",
    "audioDesc": "Lydformater inkluderer MP3, WAV, OGG og andre lydfilformater.",
    "fontTitle": "Skrifttype:",
    "fontDesc": "Skrifttypefiler inkluderer TTF, OTF, WOFF og andre skrifttypeformater som brukes til webtypografi.",
    "imageTitle": "Bilde:",
    "imageDesc": "Bildeformater inkluderer JPEG, PNG, GIF, SVG og andre bildefilformater.",
    "messageTitle": "Melding:",
    "messageDesc": "Meldingsformater inkluderer e-postmeldinger og andre meldingsbaserte protokoller.",
    "modelTitle": "Modell:",
    "modelDesc": "3D-modellformater inkluderer GLTF, OBJ, STL og andre 3D-modellfilformater.",
    "textTitle": "Tekst:",
    "textDesc": "Tekstformater inkluderer HTML, CSS, JavaScript, ren tekst, CSV og andre tekstbaserte formater.",
    "videoTitle": "Video:",
    "videoDesc": "Videoformater inkluderer MP4, WebM, AVI og andre videofilformater."
  }
}
</i18n>
