const MESSAGE_CATALOG_B = {
  hi: {
    options: "एन्कोडिंग विकल्प",
    format: "प्रारूप",
    range: "सीमा",
    "format-named": "नामित (&lt;)",
    "format-decimal": "दशमलव (&#60;)",
    "format-hex": "हेक्साडेसिमल (&#x3C;)",
    "range-minimal": "न्यूनतम (HTML आवश्यक)",
    "range-non-ascii": "सभी गैर-ASCII",
    "range-all-special": "सभी विशेष वर्ण",
    "plain-text": "सादा पाठ",
    "plain-text-placeholder": "एन्कोड करने के लिए टेक्स्ट दर्ज करें...",
    "encoded-text": "एन्कोडेड टेक्स्ट",
    "encoded-text-placeholder": "डिकोड करने के लिए HTML एंटिटीज़ दर्ज करें...",
  },
  tr: {
    options: "Kodlama Seçenekleri",
    format: "Format",
    range: "Aralık",
    "format-named": "Adlandırılmış (&lt;)",
    "format-decimal": "Ondalık (&#60;)",
    "format-hex": "Onaltılık (&#x3C;)",
    "range-minimal": "Minimum (HTML gerekli)",
    "range-non-ascii": "Tüm ASCII olmayan",
    "range-all-special": "Tüm özel karakterler",
    "plain-text": "Düz Metin",
    "plain-text-placeholder": "Kodlanacak metni girin...",
    "encoded-text": "Kodlanmış Metin",
    "encoded-text-placeholder": "Çözülecek HTML varlıklarını girin...",
  },
  nl: {
    options: "Coderingsopties",
    format: "Formaat",
    range: "Bereik",
    "format-named": "Benoemd (&lt;)",
    "format-decimal": "Decimaal (&#60;)",
    "format-hex": "Hexadecimaal (&#x3C;)",
    "range-minimal": "Minimaal (HTML vereist)",
    "range-non-ascii": "Alle niet-ASCII",
    "range-all-special": "Alle speciale tekens",
    "plain-text": "Platte tekst",
    "plain-text-placeholder": "Voer tekst in om te coderen...",
    "encoded-text": "Gecodeerde tekst",
    "encoded-text-placeholder": "Voer HTML-entiteiten in om te decoderen...",
  },
  sv: {
    options: "Kodningsalternativ",
    format: "Format",
    range: "Intervall",
    "format-named": "Namngiven (&lt;)",
    "format-decimal": "Decimal (&#60;)",
    "format-hex": "Hexadecimal (&#x3C;)",
    "range-minimal": "Minimal (HTML krävs)",
    "range-non-ascii": "Alla icke-ASCII",
    "range-all-special": "Alla specialtecken",
    "plain-text": "Klartext",
    "plain-text-placeholder": "Ange text att koda...",
    "encoded-text": "Kodad text",
    "encoded-text-placeholder": "Ange HTML-entiteter att avkoda...",
  },
  pl: {
    options: "Opcje kodowania",
    format: "Format",
    range: "Zakres",
    "format-named": "Nazwana (&lt;)",
    "format-decimal": "Dziesiętna (&#60;)",
    "format-hex": "Szesnastkowa (&#x3C;)",
    "range-minimal": "Minimalna (wymagana przez HTML)",
    "range-non-ascii": "Wszystkie nie-ASCII",
    "range-all-special": "Wszystkie znaki specjalne",
    "plain-text": "Zwykły tekst",
    "plain-text-placeholder": "Wprowadź tekst do zakodowania...",
    "encoded-text": "Zakodowany tekst",
    "encoded-text-placeholder": "Wprowadź encje HTML do zdekodowania...",
  },
  vi: {
    options: "Tùy chọn mã hóa",
    format: "Định dạng",
    range: "Phạm vi",
    "format-named": "Đặt tên (&lt;)",
    "format-decimal": "Thập phân (&#60;)",
    "format-hex": "Thập lục phân (&#x3C;)",
    "range-minimal": "Tối thiểu (HTML bắt buộc)",
    "range-non-ascii": "Tất cả không phải ASCII",
    "range-all-special": "Tất cả ký tự đặc biệt",
    "plain-text": "Văn bản thuần",
    "plain-text-placeholder": "Nhập văn bản để mã hóa...",
    "encoded-text": "Văn bản đã mã hóa",
    "encoded-text-placeholder": "Nhập thực thể HTML để giải mã...",
  },
  th: {
    options: "ตัวเลือกการเข้ารหัส",
    format: "รูปแบบ",
    range: "ช่วง",
    "format-named": "ตั้งชื่อ (&lt;)",
    "format-decimal": "ทศนิยม (&#60;)",
    "format-hex": "เลขฐานสิบหก (&#x3C;)",
    "range-minimal": "น้อยที่สุด (HTML จำเป็น)",
    "range-non-ascii": "ทั้งหมดที่ไม่ใช่ ASCII",
    "range-all-special": "อักขระพิเศษทั้งหมด",
    "plain-text": "ข้อความธรรมดา",
    "plain-text-placeholder": "ป้อนข้อความเพื่อเข้ารหัส...",
    "encoded-text": "ข้อความที่เข้ารหัส",
    "encoded-text-placeholder": "ป้อนเอนทิตี HTML เพื่อถอดรหัส...",
  },
  id: {
    options: "Opsi Pengkodean",
    format: "Format",
    range: "Rentang",
    "format-named": "Bernama (&lt;)",
    "format-decimal": "Desimal (&#60;)",
    "format-hex": "Heksadesimal (&#x3C;)",
    "range-minimal": "Minimal (diperlukan HTML)",
    "range-non-ascii": "Semua non-ASCII",
    "range-all-special": "Semua karakter khusus",
    "plain-text": "Teks Biasa",
    "plain-text-placeholder": "Masukkan teks untuk dikodekan...",
    "encoded-text": "Teks Terkode",
    "encoded-text-placeholder": "Masukkan entitas HTML untuk didekodekan...",
  },
  he: {
    options: "אפשרויות קידוד",
    format: "פורמט",
    range: "טווח",
    "format-named": "בעלת שם (&lt;)",
    "format-decimal": "עשרונית (&#60;)",
    "format-hex": "הקסדצימלית (&#x3C;)",
    "range-minimal": "מינימלי (נדרש ל-HTML)",
    "range-non-ascii": "כל הלא-ASCII",
    "range-all-special": "כל התווים המיוחדים",
    "plain-text": "טקסט רגיל",
    "plain-text-placeholder": "הזן טקסט לקידוד...",
    "encoded-text": "טקסט מקודד",
    "encoded-text-placeholder": "הזן ישויות HTML לפענוח...",
  },
  ms: {
    options: "Pilihan Pengekodan",
    format: "Format",
    range: "Julat",
    "format-named": "Dinamakan (&lt;)",
    "format-decimal": "Perpuluhan (&#60;)",
    "format-hex": "Heksadesimal (&#x3C;)",
    "range-minimal": "Minimum (HTML diperlukan)",
    "range-non-ascii": "Semua bukan ASCII",
    "range-all-special": "Semua aksara khas",
    "plain-text": "Teks Biasa",
    "plain-text-placeholder": "Masukkan teks untuk dikodkan...",
    "encoded-text": "Teks Dikodkan",
    "encoded-text-placeholder": "Masukkan entiti HTML untuk dinyahkod...",
  },
  no: {
    options: "Kodingsalternativer",
    format: "Format",
    range: "Område",
    "format-named": "Navngitt (&lt;)",
    "format-decimal": "Desimal (&#60;)",
    "format-hex": "Heksadesimal (&#x3C;)",
    "range-minimal": "Minimal (HTML påkrevd)",
    "range-non-ascii": "Alle ikke-ASCII",
    "range-all-special": "Alle spesialtegn",
    "plain-text": "Ren tekst",
    "plain-text-placeholder": "Skriv inn tekst for koding...",
    "encoded-text": "Kodet tekst",
    "encoded-text-placeholder": "Skriv inn HTML-entiteter for dekoding...",
  },
} as const

export { MESSAGE_CATALOG_B }
