const MESSAGE_CATALOG_A = {
  en: {
    options: "Encoding Options",
    format: "Format",
    range: "Range",
    "format-named": "Named (&lt;)",
    "format-decimal": "Decimal (&#60;)",
    "format-hex": "Hexadecimal (&#x3C;)",
    "range-minimal": "Minimal (HTML required)",
    "range-non-ascii": "All Non-ASCII",
    "range-all-special": "All Special Characters",
    "plain-text": "Plain Text",
    "plain-text-placeholder": "Enter text to encode...",
    "encoded-text": "Encoded Text",
    "encoded-text-placeholder": "Enter HTML entities to decode...",
  },
  "zh-CN": {
    options: "编码选项",
    format: "格式",
    range: "范围",
    "format-named": "命名实体 (&lt;)",
    "format-decimal": "十进制 (&#60;)",
    "format-hex": "十六进制 (&#x3C;)",
    "range-minimal": "最小 (HTML 必需)",
    "range-non-ascii": "所有非 ASCII",
    "range-all-special": "所有特殊字符",
    "plain-text": "纯文本",
    "plain-text-placeholder": "输入要编码的文本...",
    "encoded-text": "编码文本",
    "encoded-text-placeholder": "输入要解码的 HTML 实体...",
  },
  "zh-TW": {
    options: "編碼選項",
    format: "格式",
    range: "範圍",
    "format-named": "命名實體 (&lt;)",
    "format-decimal": "十進位 (&#60;)",
    "format-hex": "十六進位 (&#x3C;)",
    "range-minimal": "最小 (HTML 必需)",
    "range-non-ascii": "所有非 ASCII",
    "range-all-special": "所有特殊字元",
    "plain-text": "純文字",
    "plain-text-placeholder": "輸入要編碼的文字...",
    "encoded-text": "編碼文字",
    "encoded-text-placeholder": "輸入要解碼的 HTML 實體...",
  },
  es: {
    options: "Opciones de codificación",
    format: "Formato",
    range: "Rango",
    "format-named": "Nombrada (&lt;)",
    "format-decimal": "Decimal (&#60;)",
    "format-hex": "Hexadecimal (&#x3C;)",
    "range-minimal": "Mínimo (requerido por HTML)",
    "range-non-ascii": "Todo no ASCII",
    "range-all-special": "Todos los caracteres especiales",
    "plain-text": "Texto plano",
    "plain-text-placeholder": "Ingrese texto para codificar...",
    "encoded-text": "Texto codificado",
    "encoded-text-placeholder": "Ingrese entidades HTML para decodificar...",
  },
  fr: {
    options: "Options d'encodage",
    format: "Format",
    range: "Plage",
    "format-named": "Nommée (&lt;)",
    "format-decimal": "Décimale (&#60;)",
    "format-hex": "Hexadécimale (&#x3C;)",
    "range-minimal": "Minimal (requis par HTML)",
    "range-non-ascii": "Tout non-ASCII",
    "range-all-special": "Tous les caractères spéciaux",
    "plain-text": "Texte brut",
    "plain-text-placeholder": "Entrez le texte à encoder...",
    "encoded-text": "Texte encodé",
    "encoded-text-placeholder": "Entrez les entités HTML à décoder...",
  },
  de: {
    options: "Kodierungsoptionen",
    format: "Format",
    range: "Bereich",
    "format-named": "Benannt (&lt;)",
    "format-decimal": "Dezimal (&#60;)",
    "format-hex": "Hexadezimal (&#x3C;)",
    "range-minimal": "Minimal (HTML-erforderlich)",
    "range-non-ascii": "Alle Nicht-ASCII",
    "range-all-special": "Alle Sonderzeichen",
    "plain-text": "Klartext",
    "plain-text-placeholder": "Text zum Kodieren eingeben...",
    "encoded-text": "Kodierter Text",
    "encoded-text-placeholder": "HTML-Entitäten zum Dekodieren eingeben...",
  },
  it: {
    options: "Opzioni di codifica",
    format: "Formato",
    range: "Intervallo",
    "format-named": "Nominata (&lt;)",
    "format-decimal": "Decimale (&#60;)",
    "format-hex": "Esadecimale (&#x3C;)",
    "range-minimal": "Minimo (richiesto da HTML)",
    "range-non-ascii": "Tutto non-ASCII",
    "range-all-special": "Tutti i caratteri speciali",
    "plain-text": "Testo normale",
    "plain-text-placeholder": "Inserisci il testo da codificare...",
    "encoded-text": "Testo codificato",
    "encoded-text-placeholder": "Inserisci entità HTML da decodificare...",
  },
  ja: {
    options: "エンコードオプション",
    format: "形式",
    range: "範囲",
    "format-named": "名前付き (&lt;)",
    "format-decimal": "10進数 (&#60;)",
    "format-hex": "16進数 (&#x3C;)",
    "range-minimal": "最小 (HTML 必須)",
    "range-non-ascii": "すべての非 ASCII",
    "range-all-special": "すべての特殊文字",
    "plain-text": "プレーンテキスト",
    "plain-text-placeholder": "エンコードするテキストを入力...",
    "encoded-text": "エンコード済みテキスト",
    "encoded-text-placeholder": "デコードする HTML エンティティを入力...",
  },
  ko: {
    options: "인코딩 옵션",
    format: "형식",
    range: "범위",
    "format-named": "명명됨 (&lt;)",
    "format-decimal": "10진수 (&#60;)",
    "format-hex": "16진수 (&#x3C;)",
    "range-minimal": "최소 (HTML 필수)",
    "range-non-ascii": "모든 비 ASCII",
    "range-all-special": "모든 특수 문자",
    "plain-text": "일반 텍스트",
    "plain-text-placeholder": "인코딩할 텍스트 입력...",
    "encoded-text": "인코딩된 텍스트",
    "encoded-text-placeholder": "디코딩할 HTML 엔티티 입력...",
  },
  ru: {
    options: "Параметры кодирования",
    format: "Формат",
    range: "Диапазон",
    "format-named": "Именованная (&lt;)",
    "format-decimal": "Десятичная (&#60;)",
    "format-hex": "Шестнадцатеричная (&#x3C;)",
    "range-minimal": "Минимум (требуется HTML)",
    "range-non-ascii": "Все не-ASCII",
    "range-all-special": "Все специальные символы",
    "plain-text": "Обычный текст",
    "plain-text-placeholder": "Введите текст для кодирования...",
    "encoded-text": "Закодированный текст",
    "encoded-text-placeholder": "Введите HTML-сущности для декодирования...",
  },
  pt: {
    options: "Opções de codificação",
    format: "Formato",
    range: "Intervalo",
    "format-named": "Nomeada (&lt;)",
    "format-decimal": "Decimal (&#60;)",
    "format-hex": "Hexadecimal (&#x3C;)",
    "range-minimal": "Mínimo (requerido por HTML)",
    "range-non-ascii": "Todos não-ASCII",
    "range-all-special": "Todos os caracteres especiais",
    "plain-text": "Texto simples",
    "plain-text-placeholder": "Digite o texto para codificar...",
    "encoded-text": "Texto codificado",
    "encoded-text-placeholder": "Digite entidades HTML para decodificar...",
  },
  ar: {
    options: "خيارات الترميز",
    format: "التنسيق",
    range: "النطاق",
    "format-named": "مسمى (&lt;)",
    "format-decimal": "عشري (&#60;)",
    "format-hex": "سداسي عشري (&#x3C;)",
    "range-minimal": "الحد الأدنى (مطلوب لـ HTML)",
    "range-non-ascii": "كل غير ASCII",
    "range-all-special": "جميع الأحرف الخاصة",
    "plain-text": "نص عادي",
    "plain-text-placeholder": "أدخل النص للترميز...",
    "encoded-text": "نص مرمز",
    "encoded-text-placeholder": "أدخل كيانات HTML لفك الترميز...",
  },
} as const

export { MESSAGE_CATALOG_A }
