import { describe, expect, it, vi } from 'vitest'

const { astToStringMock, resolveRefMock, scanDiscriminatorsMock, transformSchemaMock } = vi.hoisted(
  () => ({
    astToStringMock: vi.fn(),
    resolveRefMock: vi.fn(),
    scanDiscriminatorsMock: vi.fn(),
    transformSchemaMock: vi.fn(),
  }),
)

vi.mock('../node_modules/openapi-typescript/dist/transform/index.mjs', () => ({
  default: (...args: unknown[]) => transformSchemaMock(...args),
}))

vi.mock('../node_modules/openapi-typescript/dist/lib/ts.mjs', () => ({
  astToString: (...args: unknown[]) => astToStringMock(...args),
}))

vi.mock('../node_modules/openapi-typescript/dist/lib/utils.mjs', () => ({
  resolveRef: (...args: unknown[]) => resolveRefMock(...args),
  scanDiscriminators: (...args: unknown[]) => scanDiscriminatorsMock(...args),
}))

describe('generateOpenApiTypes context wiring', () => {
  it('uses the resolver callback and prepends the default header', async () => {
    transformSchemaMock.mockImplementation(
      (_schema: unknown, ctx: { resolve: (ref: string) => void }) => {
        ctx.resolve('external.yaml#/components/schemas/User')
        return ['ast']
      },
    )
    astToStringMock.mockReturnValue('export interface paths {}')
    resolveRefMock.mockReturnValue({})
    scanDiscriminatorsMock.mockReturnValue({ objects: {}, refsHandled: [] })

    const { generateOpenApiTypes } = await import('./index')
    const document = {
      openapi: '3.1.0',
      info: { title: 'Sample', version: '1.0.0' },
      paths: {},
    }

    const output = generateOpenApiTypes(document)

    expect(transformSchemaMock).toHaveBeenCalledTimes(1)
    expect(scanDiscriminatorsMock).toHaveBeenCalledWith(document, {})
    expect(resolveRefMock).toHaveBeenCalledWith(
      document,
      'external.yaml#/components/schemas/User',
      {
        silent: true,
      },
    )
    expect(output).toContain('This file was auto-generated by openapi-typescript.')
    expect(output).toContain('export interface paths {}')
  })
})
