import { describe, expect, it } from 'vitest'
import { collectExternalRefs, generateOpenApiTypes, parseOpenApiDocument } from './index'

const sampleOpenApi = `openapi: 3.1.0
info:
  title: Sample API
  version: '1.0.0'
paths:
  /users:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
`

describe('openapi types utils', () => {
  it('parses a valid OpenAPI document', () => {
    const result = parseOpenApiDocument(sampleOpenApi)
    expect(result.ok).toBe(true)
    if (!result.ok) return
    expect(result.document.openapi.startsWith('3.')).toBe(true)
    expect(result.externalRefs).toHaveLength(0)
  })

  it('rejects unsupported OpenAPI versions', () => {
    const result = parseOpenApiDocument('openapi: 2.0.0\ninfo: { title: X, version: 1 }')
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.code).toBe('unsupported-version')
  })

  it('rejects invalid YAML documents', () => {
    const result = parseOpenApiDocument('openapi: [3.1.0')
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.code).toBe('invalid')
    expect(result.message).toBeTruthy()
  })

  it('rejects parsed arrays as non-object OpenAPI documents', () => {
    const result = parseOpenApiDocument('[]')
    expect(result.ok).toBe(false)
    if (result.ok) return
    expect(result.code).toBe('not-object')
  })

  it('collects external $ref values from nested structures', () => {
    const refs = collectExternalRefs({
      components: {
        schemas: [
          { $ref: 'schemas/user.yaml' },
          { nested: { $ref: '#/components/schemas/LocalOnly' } },
          { $ref: 'schemas/account.yaml' },
        ],
      },
    })

    expect(refs.sort()).toEqual(['schemas/account.yaml', 'schemas/user.yaml'])
  })

  it('generates TypeScript output with and without the auto-generated header', () => {
    const result = parseOpenApiDocument(sampleOpenApi)
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const outputWithoutHeader = generateOpenApiTypes(result.document, { includeHeader: false })
    expect(outputWithoutHeader).toContain('export interface paths')
    expect(outputWithoutHeader).toContain('export interface components')

    const outputWithHeader = generateOpenApiTypes(result.document)
    expect(outputWithHeader).toContain('This file was auto-generated by openapi-typescript.')
    expect(outputWithHeader).toContain('export interface paths')
  })
})
