import type { HashTool } from "../types"

const CRYPTOGRAPHIC_HASH_TOOLS = [
  {
    slug: "blake2b-hash-text-or-file",
    label: "BLAKE2b",
    group: "cryptographic",
    kind: "textFile",
    tags: ["blake2", "blake2b", "digest", "modern"],
  },
  {
    slug: "blake2s-hash-text-or-file",
    label: "BLAKE2s",
    group: "cryptographic",
    kind: "textFile",
    tags: ["blake2", "blake2s", "digest", "modern"],
  },
  {
    slug: "blake3-hash-text-or-file",
    label: "BLAKE3",
    group: "cryptographic",
    kind: "textFile",
    tags: ["blake3", "digest", "modern", "fast"],
  },
  {
    slug: "keccak-hash-text-or-file",
    label: "Keccak",
    group: "cryptographic",
    kind: "textFile",
    tags: ["keccak", "sha3", "ethereum", "digest"],
  },
  {
    slug: "md4-hash-text-or-file",
    label: "MD4",
    group: "cryptographic",
    kind: "textFile",
    tags: ["md4", "legacy", "digest"],
  },
  {
    slug: "md5-hash-text-or-file",
    label: "MD5",
    group: "cryptographic",
    kind: "textFile",
    tags: ["md5", "legacy", "checksum", "digest"],
  },
  {
    slug: "ripemd128-hash-text-or-file",
    label: "RIPEMD-128",
    group: "cryptographic",
    kind: "textFile",
    tags: ["ripemd", "ripemd128", "legacy", "digest"],
  },
  {
    slug: "ripemd160-hash-text-or-file",
    label: "RIPEMD-160",
    group: "cryptographic",
    kind: "textFile",
    tags: ["ripemd", "ripemd160", "bitcoin", "digest"],
  },
  {
    slug: "ripemd256-hash-text-or-file",
    label: "RIPEMD-256",
    group: "cryptographic",
    kind: "textFile",
    tags: ["ripemd", "ripemd256", "digest"],
  },
  {
    slug: "ripemd320-hash-text-or-file",
    label: "RIPEMD-320",
    group: "cryptographic",
    kind: "textFile",
    tags: ["ripemd", "ripemd320", "digest"],
  },
  {
    slug: "sha1-hash-text-or-file",
    label: "SHA-1",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha1", "legacy", "digest"],
  },
  {
    slug: "sha224-hash-text-or-file",
    label: "SHA-224",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha224", "digest"],
  },
  {
    slug: "sha256-hash-text-or-file",
    label: "SHA-256",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha256", "digest", "checksum"],
  },
  {
    slug: "sha384-hash-text-or-file",
    label: "SHA-384",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha384", "digest"],
  },
  {
    slug: "sha512-hash-text-or-file",
    label: "SHA-512",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha512", "digest"],
  },
  {
    slug: "sha512-224-hash-text-or-file",
    label: "SHA-512/224",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha512-224", "digest"],
  },
  {
    slug: "sha512-256-hash-text-or-file",
    label: "SHA-512/256",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha2", "sha512-256", "digest"],
  },
  {
    slug: "sha3-224-hash-text-or-file",
    label: "SHA3-224",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha3", "sha3-224", "digest"],
  },
  {
    slug: "sha3-256-hash-text-or-file",
    label: "SHA3-256",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha3", "sha3-256", "digest"],
  },
  {
    slug: "sha3-384-hash-text-or-file",
    label: "SHA3-384",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha3", "sha3-384", "digest"],
  },
  {
    slug: "sha3-512-hash-text-or-file",
    label: "SHA3-512",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sha3", "sha3-512", "digest"],
  },
  {
    slug: "shake128-hash-text-or-file",
    label: "SHAKE128",
    group: "cryptographic",
    kind: "textFile",
    tags: ["shake", "shake128", "xof", "sha3"],
  },
  {
    slug: "shake256-hash-text-or-file",
    label: "SHAKE256",
    group: "cryptographic",
    kind: "textFile",
    tags: ["shake", "shake256", "xof", "sha3"],
  },
  {
    slug: "sm3-hash-text-or-file",
    label: "SM3",
    group: "cryptographic",
    kind: "textFile",
    tags: ["sm3", "gm", "digest"],
  },
  {
    slug: "whirlpool-hash-text-or-file",
    label: "Whirlpool",
    group: "cryptographic",
    kind: "textFile",
    tags: ["whirlpool", "digest"],
  },
] as const satisfies readonly HashTool[]

export { CRYPTOGRAPHIC_HASH_TOOLS }
