export const sqlDialects = [
  'sql',
  'bigquery',
  'clickhouse',
  'db2',
  'db2i',
  'hive',
  'mariadb',
  'mysql',
  'n1ql',
  'plsql',
  'postgresql',
  'redshift',
  'singlestoredb',
  'snowflake',
  'spark',
  'sqlite',
  'tidb',
  'trino',
  'tsql',
] as const

export type SqlDialect = (typeof sqlDialects)[number]

export const dialectLabels: Record<SqlDialect, string> = {
  sql: 'SQL (Generic)',
  bigquery: 'BigQuery',
  clickhouse: 'ClickHouse',
  db2: 'DB2',
  db2i: 'DB2i',
  hive: 'Hive',
  mariadb: 'MariaDB',
  mysql: 'MySQL',
  n1ql: 'N1QL',
  plsql: 'PL/SQL',
  postgresql: 'PostgreSQL',
  redshift: 'Redshift',
  singlestoredb: 'SingleStoreDB',
  snowflake: 'Snowflake',
  spark: 'Spark SQL',
  sqlite: 'SQLite',
  tidb: 'TiDB',
  trino: 'Trino',
  tsql: 'T-SQL',
}

export const fileExtensions = [
  '.sql',
  '.ddl',
  '.dml',
  '.mysql',
  '.pgsql',
  '.psql',
  '.sqlite',
  '.db2',
  '.hql',
  '.trino',
  '.tsql',
  '.txt',
]

export const extensionToDialect: Record<string, SqlDialect> = {
  sql: 'sql',
  ddl: 'sql',
  dml: 'sql',
  mysql: 'mysql',
  mariadb: 'mariadb',
  pgsql: 'postgresql',
  psql: 'postgresql',
  sqlite: 'sqlite',
  db2: 'db2',
  hql: 'hive',
  trino: 'trino',
  tsql: 'tsql',
}
