import { ColorProfile } from "@imagemagick/magick-wasm"

// Standard sRGB profile generated with LittleCMS via Pillow ImageCms.createProfile.
// Embedded locally so JPEG color conversion needs no network profile lookup.
const data =
  "AAACTGxjbXMEQAAAbW50clJHQiBYWVogB+oACgAKABAAIQAOYWNzcEFQUEwAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAAA2Y3BydAAAAUAA" +
  "AABMd3RwdAAAAYwAAAAUY2hhZAAAAaAAAAAsclhZWgAAAcwAAAAUYlhZWgAAAeAAAAAU" +
  "Z1hZWgAAAfQAAAAUclRSQwAAAggAAAAgZ1RSQwAAAggAAAAgYlRSQwAAAggAAAAgY2hy" +
  "bQAAAigAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMAAAAaAAAAHABzAFIARwBCACAAYgB1" +
  "AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAADAAAAAcAE4AbwAgAGMA" +
  "bwBwAHkAcgBpAGcAaAB0ACwAIAB1AHMAZQAgAGYAcgBlAGUAbAB5WFlaIAAAAAAAAPbW" +
  "AAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of///aIAAAPcAADA" +
  "blhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsNYWVogAAAAAAAA" +
  "YpcAALeHAAAY2XBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAA" +
  "AwAAAACj1wAAVHsAAEzNAACZmgAAJmYAAA9c"

export const srgbProfile = new ColorProfile(
  Uint8Array.from(atob(data), (character) => character.charCodeAt(0))
)
