import type {
  PrettierLanguageConfig,
  PrettierLanguageKey,
} from "./prettier-types"

const PRETTIER_LANGUAGE_CONFIGS: Record<
  PrettierLanguageKey,
  PrettierLanguageConfig
> = {
  javascript: {
    label: "JavaScript",
    parser: "babel",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "javascript",
    extensions: [".js", ".mjs", ".cjs"],
    sample:
      "const greeting = (name) => {\n  return { message: 'Hello ' + name, items: [1, 2, 3] }\n}\n",
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  jsx: {
    label: "JSX",
    parser: "babel",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "javascript",
    extensions: [".jsx"],
    sample:
      'export function App() {\n  return <main className="card">Hello</main>\n}\n',
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  typescript: {
    label: "TypeScript",
    parser: "typescript",
    pluginKeys: ["typescript", "estree"],
    highlightLanguage: "typescript",
    extensions: [".ts", ".cts", ".mts"],
    sample:
      "type User = { id: number; name: string }\n\nconst users: User[] = [{ id: 1, name: 'Ada' }]\n",
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  tsx: {
    label: "TSX",
    parser: "typescript",
    pluginKeys: ["typescript", "estree"],
    highlightLanguage: "typescript",
    extensions: [".tsx"],
    sample:
      "type Props = { title: string }\n\nexport function Card({ title }: Props) {\n  return <section>{title}</section>\n}\n",
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  flow: {
    label: "Flow",
    parser: "flow",
    pluginKeys: ["flow", "estree"],
    highlightLanguage: "javascript",
    extensions: [".js.flow"],
    sample:
      "/* @flow */\ntype User = { id: number, name: string }\n\nconst user: User = { id: 1, name: 'Ada' }\n",
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  json: {
    label: "JSON",
    parser: "json",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "json",
    extensions: [".json"],
    sample:
      '{\n  "name": "Example",\n  "items": [1, 2, 3],\n  "active": true\n}\n',
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  "json-stringify": {
    label: "JSON.stringify",
    parser: "json-stringify",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "json",
    extensions: [".importmap"],
    filenames: ["package.json", "package-lock.json", "composer.json"],
    outputExtension: ".json",
    sample:
      '{\n  "name": "prettier-demo",\n  "private": true,\n  "scripts": {\n    "format": "prettier --write ."\n  }\n}\n',
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  json5: {
    label: "JSON5",
    parser: "json5",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "json",
    extensions: [".json5"],
    sample:
      "{\n  // JSON5 supports comments\n  unquoted: 'value',\n  trailing: true,\n}\n",
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  jsonc: {
    label: "JSONC",
    parser: "jsonc",
    pluginKeys: ["babel", "estree"],
    highlightLanguage: "json",
    extensions: [".jsonc"],
    sample:
      '{\n  // JSON with comments\n  "name": "Example",\n  "enabled": true\n}\n',
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  html: {
    label: "HTML",
    parser: "html",
    pluginKeys: ["html"],
    highlightLanguage: "xml",
    extensions: [".html", ".htm", ".xhtml"],
    sample:
      '<div class="card"><h1>Hello</h1><p>Prettier formatting</p></div>\n',
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  angular: {
    label: "Angular",
    parser: "angular",
    pluginKeys: ["angular"],
    highlightLanguage: "xml",
    extensions: [".component.html"],
    outputExtension: ".html",
    sample: '<div *ngIf="isReady">{{ title }}</div>\n',
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  vue: {
    label: "Vue",
    parser: "vue",
    pluginKeys: ["html"],
    highlightLanguage: "xml",
    extensions: [".vue"],
    sample:
      '<template>\n  <div class="card">{{ message }}</div>\n</template>\n\n<script setup lang="ts">\nconst message = \'Hello\'\n<\\/script>\n',
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  lwc: {
    label: "LWC",
    parser: "lwc",
    pluginKeys: ["html"],
    highlightLanguage: "xml",
    extensions: [],
    outputExtension: ".html",
    sample:
      '<template>\n  <lightning-button label="Hello" onclick={handleClick}></lightning-button>\n</template>\n',
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  mjml: {
    label: "MJML",
    parser: "mjml",
    pluginKeys: ["html"],
    highlightLanguage: "xml",
    extensions: [".mjml"],
    sample:
      "<mjml><mj-body><mj-section><mj-column><mj-text>Hello</mj-text></mj-column></mj-section></mj-body></mjml>\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  handlebars: {
    label: "Handlebars",
    parser: "glimmer",
    pluginKeys: ["glimmer"],
    highlightLanguage: "handlebars",
    extensions: [".hbs", ".handlebars", ".mustache"],
    sample: "{{#if isReady}}\n  <span>{{title}}</span>\n{{/if}}\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  css: {
    label: "CSS",
    parser: "css",
    pluginKeys: ["postcss"],
    highlightLanguage: "css",
    extensions: [".css"],
    sample: ".card {\n  display: flex;\n  gap: 12px;\n}\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  postcss: {
    label: "PostCSS",
    parser: "postcss",
    pluginKeys: ["postcss"],
    highlightLanguage: "css",
    extensions: [".postcss", ".pcss"],
    sample:
      "@custom-media --small-screen (max-width: 40rem);\n\n.card {\n  color: rebeccapurple;\n}\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  scss: {
    label: "SCSS",
    parser: "scss",
    pluginKeys: ["postcss"],
    highlightLanguage: "scss",
    extensions: [".scss"],
    sample:
      "$primary: #2b4b6f;\n\n.card {\n  color: $primary;\n  &:hover {\n    opacity: 0.9;\n  }\n}\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  less: {
    label: "Less",
    parser: "less",
    pluginKeys: ["postcss"],
    highlightLanguage: "less",
    extensions: [".less"],
    sample:
      "@primary: #2b4b6f;\n\n.card {\n  color: @primary;\n  &:hover {\n    opacity: 0.9;\n  }\n}\n",
    supportsSemi: false,
    supportsSingleQuote: true,
    supportsTrailingComma: false,
  },
  markdown: {
    label: "Markdown",
    parser: "markdown",
    pluginKeys: ["markdown"],
    highlightLanguage: "markdown",
    extensions: [".md", ".markdown"],
    sample: "# Prettier Formatter\n\n- Paste your code\n- Adjust options\n",
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  mdx: {
    label: "MDX",
    parser: "mdx",
    pluginKeys: ["markdown"],
    highlightLanguage: "markdown",
    extensions: [".mdx"],
    sample: "# MDX Example\n\n<Alert>Hi</Alert>\n\nexport const answer = 42\n",
    supportsSemi: true,
    supportsSingleQuote: true,
    supportsTrailingComma: true,
  },
  yaml: {
    label: "YAML",
    parser: "yaml",
    pluginKeys: ["yaml"],
    highlightLanguage: "yaml",
    extensions: [".yaml", ".yml"],
    sample: "name: Example\nitems:\n  - one\n  - two\n",
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
  graphql: {
    label: "GraphQL",
    parser: "graphql",
    pluginKeys: ["graphql"],
    highlightLanguage: "graphql",
    extensions: [".graphql", ".gql", ".graphqls"],
    sample:
      "query User($id: ID!) {\n  user(id: $id) {\n    id\n    name\n  }\n}\n",
    supportsSemi: false,
    supportsSingleQuote: false,
    supportsTrailingComma: false,
  },
}

export { PRETTIER_LANGUAGE_CONFIGS }
