<template>
  <slot :labels="labels" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n({ useScope: 'local' })

const labels = computed(() => ({
  alphaQualityLabel: t('alphaQualityLabel'),
  denoiseLevelLabel: t('denoiseLevelLabel'),
  sharpnessLabel: t('sharpnessLabel'),
  subsampleLabel: t('subsampleLabel'),
  subsample420Label: t('subsample420Label'),
  subsample422Label: t('subsample422Label'),
  subsample444Label: t('subsample444Label'),
  tuneLabel: t('tuneLabel'),
  tuneAutoLabel: t('tuneAutoLabel'),
  tunePsnrLabel: t('tunePsnrLabel'),
  tuneSsimLabel: t('tuneSsimLabel'),
  sharpYuvLabel: t('sharpYuvLabel'),
}))
</script>

<i18n lang="json">
{
  "en": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "zh": {
    "alphaQualityLabel": "透明通道质量",
    "denoiseLevelLabel": "降噪级别",
    "sharpnessLabel": "锐度",
    "subsampleLabel": "色度子采样",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "调优目标",
    "tuneAutoLabel": "自动",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "启用 Sharp YUV"
  },
  "zh-CN": {
    "alphaQualityLabel": "透明通道质量",
    "denoiseLevelLabel": "降噪级别",
    "sharpnessLabel": "锐度",
    "subsampleLabel": "色度子采样",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "调优目标",
    "tuneAutoLabel": "自动",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "启用 Sharp YUV"
  },
  "zh-TW": {
    "alphaQualityLabel": "透明通道品質",
    "denoiseLevelLabel": "降噪等級",
    "sharpnessLabel": "銳度",
    "subsampleLabel": "色度子採樣",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "調校目標",
    "tuneAutoLabel": "自動",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "啟用 Sharp YUV"
  },
  "zh-HK": {
    "alphaQualityLabel": "透明通道品質",
    "denoiseLevelLabel": "降噪等級",
    "sharpnessLabel": "銳度",
    "subsampleLabel": "色度子採樣",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "調校目標",
    "tuneAutoLabel": "自動",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "啟用 Sharp YUV"
  },
  "es": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "fr": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "de": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "it": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "ja": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "ko": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "ru": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "pt": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "ar": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "hi": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "tr": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "nl": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "sv": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "pl": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "vi": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "th": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "id": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "he": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "ms": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  },
  "no": {
    "alphaQualityLabel": "Alpha quality",
    "denoiseLevelLabel": "Denoise level",
    "sharpnessLabel": "Sharpness",
    "subsampleLabel": "Chroma subsampling",
    "subsample420Label": "4:2:0",
    "subsample422Label": "4:2:2",
    "subsample444Label": "4:4:4",
    "tuneLabel": "Tune",
    "tuneAutoLabel": "Auto",
    "tunePsnrLabel": "PSNR",
    "tuneSsimLabel": "SSIM",
    "sharpYuvLabel": "Enable Sharp YUV"
  }
}
</i18n>
