<template>
  <slot :labels="labels" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n({ useScope: 'local' })

const labels = computed(() => ({
  title: t('optionsTitle'),
  scaleLabel: t('scaleLabel'),
  scaleHint: t('scaleHint'),
  qualityLabel: t('qualityLabel'),
  qualityHint: t('qualityHint'),
  speedLabel: t('speedLabel'),
  speedHint: t('speedHint'),
  losslessLabel: t('losslessLabel'),
  advancedLabel: t('advancedLabel'),
  convertLabel: t('convert'),
  convertingLabel: t('converting'),
}))
</script>

<i18n lang="json">
{
  "en": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "zh": {
    "optionsTitle": "转换选项",
    "scaleLabel": "缩放 (%)",
    "scaleHint": "在编码前调整输出尺寸。",
    "qualityLabel": "质量",
    "qualityHint": "数值越高通常保留更多细节。",
    "speedLabel": "速度",
    "speedHint": "0 最慢，10 最快。",
    "losslessLabel": "无损",
    "advancedLabel": "高级选项",
    "convert": "转换为 AVIF",
    "converting": "转换中..."
  },
  "zh-CN": {
    "optionsTitle": "转换选项",
    "scaleLabel": "缩放 (%)",
    "scaleHint": "在编码前调整输出尺寸。",
    "qualityLabel": "质量",
    "qualityHint": "数值越高通常保留更多细节。",
    "speedLabel": "速度",
    "speedHint": "0 最慢，10 最快。",
    "losslessLabel": "无损",
    "advancedLabel": "高级选项",
    "convert": "转换为 AVIF",
    "converting": "转换中..."
  },
  "zh-TW": {
    "optionsTitle": "轉換選項",
    "scaleLabel": "縮放 (%)",
    "scaleHint": "在編碼前調整輸出尺寸。",
    "qualityLabel": "品質",
    "qualityHint": "數值越高通常保留更多細節。",
    "speedLabel": "速度",
    "speedHint": "0 最慢，10 最快。",
    "losslessLabel": "無損",
    "advancedLabel": "進階選項",
    "convert": "轉換為 AVIF",
    "converting": "轉換中..."
  },
  "zh-HK": {
    "optionsTitle": "轉換選項",
    "scaleLabel": "縮放 (%)",
    "scaleHint": "在編碼前調整輸出尺寸。",
    "qualityLabel": "品質",
    "qualityHint": "數值越高通常保留更多細節。",
    "speedLabel": "速度",
    "speedHint": "0 最慢，10 最快。",
    "losslessLabel": "無損",
    "advancedLabel": "進階選項",
    "convert": "轉換為 AVIF",
    "converting": "轉換中..."
  },
  "es": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "fr": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "de": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "it": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "ja": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "ko": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "ru": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "pt": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "ar": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "hi": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "tr": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "nl": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "sv": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "pl": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "vi": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "th": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "id": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "he": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "ms": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  },
  "no": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize the output before encoding.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values usually keep more detail.",
    "speedLabel": "Speed",
    "speedHint": "0 is slowest, 10 is fastest.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to AVIF",
    "converting": "Converting..."
  }
}
</i18n>
