<template>
  <n-grid cols="1 l:2" responsive="screen" :x-gap="24" :y-gap="24">
    <n-gi>
      <ToolSectionHeader>{{ t('inputTitle') }}</ToolSectionHeader>
      <ToolSection>
        <n-form-item :label="t('codeInputLabel')" :show-feedback="false">
          <n-input
            v-model:value="code"
            type="textarea"
            class="code-input"
            :autosize="{ minRows: 12, maxRows: 28 }"
            :placeholder="t('codePlaceholder')"
          />
        </n-form-item>
      </ToolSection>

      <ToolSectionHeader>{{ t('styleTitle') }}</ToolSectionHeader>
      <ToolSection>
        <n-grid cols="1 s:2" responsive="screen" :x-gap="12" :y-gap="12">
          <n-form-item-gi :label="t('language')" :show-feedback="false">
            <n-select v-model:value="language" :options="languageSelectOptions" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('renderMode')" :show-feedback="false">
            <n-select v-model:value="renderMode" :options="renderModeOptions" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('theme')" :show-feedback="false">
            <n-select v-model:value="themeId" :options="themeOptions" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('backgroundType')" :show-feedback="false">
            <n-select
              v-model:value="backgroundType"
              :options="backgroundTypeOptions"
              size="small"
            />
          </n-form-item-gi>
          <n-form-item-gi
            v-if="backgroundType === 'preset'"
            :label="t('backgroundPreset')"
            :show-feedback="false"
          >
            <n-select
              v-model:value="backgroundPresetId"
              :options="backgroundPresetOptions"
              size="small"
            />
          </n-form-item-gi>
          <n-form-item-gi
            v-if="backgroundType === 'solid'"
            :label="t('backgroundColor')"
            :show-feedback="false"
          >
            <n-color-picker v-model:value="backgroundColor" :modes="['hex']" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('windowStyle')" :show-feedback="false">
            <n-select v-model:value="windowStyle" :options="windowStyleOptions" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('lineNumbers')" :show-feedback="false">
            <n-switch v-model:value="showLineNumbers" />
          </n-form-item-gi>
        </n-grid>
      </ToolSection>

      <ToolSectionHeader>{{ t('layoutTitle') }}</ToolSectionHeader>
      <ToolSection>
        <n-grid cols="1 s:2" responsive="screen" :x-gap="12" :y-gap="12">
          <n-form-item-gi :label="t('fontSize')" :show-feedback="false">
            <n-input-number v-model:value="fontSize" :min="12" :max="28" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('lineHeight')" :show-feedback="false">
            <n-input-number
              v-model:value="lineHeight"
              :min="1.2"
              :max="2"
              :step="0.05"
              size="small"
            />
          </n-form-item-gi>
          <n-form-item-gi :label="t('cardPadding')" :show-feedback="false">
            <n-input-number v-model:value="cardPadding" :min="12" :max="60" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('framePadding')" :show-feedback="false">
            <n-input-number v-model:value="framePadding" :min="16" :max="120" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('radius')" :show-feedback="false">
            <n-input-number v-model:value="radius" :min="6" :max="40" size="small" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('shadow')" :show-feedback="false">
            <n-switch v-model:value="shadow" />
          </n-form-item-gi>
          <n-form-item-gi :label="t('tabSize')" :show-feedback="false">
            <n-input-number v-model:value="tabSize" :min="2" :max="8" size="small" />
          </n-form-item-gi>
        </n-grid>
      </ToolSection>
    </n-gi>

    <n-gi>
      <ToolSectionHeader>{{ t('previewTitle') }}</ToolSectionHeader>
      <ToolSection>
        <CodeShotPreview
          :lines="styledLines"
          :line-numbers="lineNumbers"
          :layout="layoutConfig"
          :theme="activeTheme"
          :background="backgroundConfig"
        />
      </ToolSection>

      <ToolSectionHeader>{{ t('exportTitle') }}</ToolSectionHeader>
      <ToolSection>
        <CodeShotExportPanel
          v-model:filename="fileName"
          :svg-markup="svgOutput.svg"
          :svg-width="svgOutput.width"
          :svg-height="svgOutput.height"
          :html-snippet="htmlSnippet"
          :html-document="htmlDocument"
          :jpg-background="jpgBackground"
          :labels="exportLabels"
        />
      </ToolSection>
    </n-gi>
  </n-grid>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useDebounce, useStorage } from '@vueuse/core'
import { useI18n } from 'vue-i18n'
import {
  NColorPicker,
  NFormItem,
  NFormItemGi,
  NGrid,
  NGi,
  NInput,
  NInputNumber,
  NSelect,
  NSwitch,
} from 'naive-ui'
import { ToolSection, ToolSectionHeader } from '@shared/ui/tool'
import hljs from 'highlight.js/lib/core'
import { registerHighlightLanguages, languageOptions } from '../utils/languages'
import {
  backgroundPresets,
  DEFAULT_MONO_FONT,
  getBackgroundPreset,
  getThemeById,
  themes,
} from '../utils/themes'
import {
  applyTokenStyles,
  buildCodeShotSvg,
  buildHtmlDocument,
  buildHtmlSnippet,
  buildLineNumbers,
  highlightToTokens,
  normalizeCode,
  tokensToLines,
  type BackgroundConfig,
  type RenderMode,
  type WindowStyle,
} from '../utils/render'
import CodeShotPreview from './CodeShotPreview.vue'
import CodeShotExportPanel from './CodeShotExportPanel.vue'

registerHighlightLanguages(hljs)

const { t } = useI18n()

const defaultCode = `const palette = [
  { name: 'Aurora', hex: '#0ea5e9' },
  { name: 'Meadow', hex: '#22c55e' },
  { name: 'Sun', hex: '#f59e0b' },
]

export const createShot = (code, theme) => {
  return { code, theme, format: ['svg', 'png', 'jpg', 'html'] }
}`

const code = useStorage<string>('tools:code-shot:code', defaultCode)
const language = useStorage<string>('tools:code-shot:language', 'auto')
const renderMode = useStorage<RenderMode>('tools:code-shot:renderMode', 'highlight')
const themeId = useStorage<string>('tools:code-shot:theme', 'nebula')
const backgroundType = useStorage<'preset' | 'solid' | 'transparent' | 'none'>(
  'tools:code-shot:backgroundType',
  'preset',
)
const backgroundPresetId = useStorage<string>('tools:code-shot:backgroundPreset', 'aurora')
const backgroundColor = useStorage<string>('tools:code-shot:backgroundColor', '#0f172a')
const windowStyle = useStorage<WindowStyle>('tools:code-shot:windowStyle', 'mac')
const showLineNumbers = useStorage<boolean>('tools:code-shot:lineNumbers', true)
const fontSize = useStorage<number>('tools:code-shot:fontSize', 16)
const lineHeight = useStorage<number>('tools:code-shot:lineHeight', 1.6)
const cardPadding = useStorage<number>('tools:code-shot:cardPadding', 24)
const framePadding = useStorage<number>('tools:code-shot:framePadding', 48)
const radius = useStorage<number>('tools:code-shot:radius', 18)
const shadow = useStorage<boolean>('tools:code-shot:shadow', true)
const tabSize = useStorage<number>('tools:code-shot:tabSize', 2)
const fileName = useStorage<string>('tools:code-shot:fileName', 'code-shot')

const debouncedCode = useDebounce(code, 180)

const normalizedCode = computed(() => normalizeCode(debouncedCode.value ?? ''))
const activeTheme = computed(() => getThemeById(themeId.value))

const backgroundConfig = computed<BackgroundConfig>(() => {
  if (backgroundType.value === 'transparent') {
    return { type: 'transparent' }
  }
  if (backgroundType.value === 'none') {
    return { type: 'none' }
  }
  if (backgroundType.value === 'solid') {
    return { type: 'solid', color: backgroundColor.value }
  }
  return {
    type: 'preset',
    preset: getBackgroundPreset(backgroundPresetId.value),
  }
})

const layoutConfig = computed(() => ({
  fontSize: fontSize.value,
  lineHeight: lineHeight.value,
  padding: cardPadding.value,
  framePadding: framePadding.value,
  radius: radius.value,
  shadow: shadow.value,
  windowStyle: windowStyle.value,
  showLineNumbers: showLineNumbers.value,
  tabSize: tabSize.value,
  fontFamily: DEFAULT_MONO_FONT,
}))

const highlightedTokens = computed(() =>
  highlightToTokens(hljs, normalizedCode.value, language.value, renderMode.value),
)
const styledTokens = computed(() =>
  applyTokenStyles(highlightedTokens.value, activeTheme.value, tabSize.value),
)
const styledLines = computed(() => tokensToLines(styledTokens.value))
const lineNumbers = computed(() => buildLineNumbers(styledLines.value.length))

const svgOutput = computed(() =>
  buildCodeShotSvg(
    styledLines.value,
    layoutConfig.value,
    activeTheme.value,
    backgroundConfig.value,
  ),
)
const htmlSnippet = computed(() =>
  buildHtmlSnippet(
    styledLines.value,
    layoutConfig.value,
    activeTheme.value,
    backgroundConfig.value,
  ),
)
const htmlDocument = computed(() => buildHtmlDocument(htmlSnippet.value, backgroundConfig.value))

const jpgBackground = computed(() =>
  backgroundConfig.value.type === 'transparent' ? activeTheme.value.background : '',
)

const languageSelectOptions = computed(() =>
  languageOptions.map((option) => ({
    label: option.value === 'auto' ? t('languageAuto') : option.label,
    value: option.value,
  })),
)

const renderModeOptions = computed(() => [
  { label: t('renderModeHighlight'), value: 'highlight' },
  { label: t('renderModePlain'), value: 'plain' },
])

const themeOptions = computed(() =>
  themes.map((theme) => ({
    // eslint-disable-next-line @intlify/vue-i18n/no-dynamic-keys
    label: t(theme.labelKey),
    value: theme.id,
  })),
)

const backgroundTypeOptions = computed(() => [
  { label: t('backgroundPreset'), value: 'preset' },
  { label: t('backgroundSolid'), value: 'solid' },
  { label: t('backgroundTransparent'), value: 'transparent' },
  { label: t('backgroundNone'), value: 'none' },
])

const backgroundPresetOptions = computed(() =>
  backgroundPresets.map((preset) => ({
    // eslint-disable-next-line @intlify/vue-i18n/no-dynamic-keys
    label: t(preset.labelKey),
    value: preset.id,
  })),
)

const windowStyleOptions = computed(() => [
  { label: t('windowMac'), value: 'mac' },
  { label: t('windowWindows'), value: 'windows' },
  { label: t('windowNone'), value: 'none' },
])

const exportLabels = computed(() => ({
  fileName: t('exportFileName'),
  scale: t('exportScale'),
  quality: t('exportQuality'),
  rendering: t('exportRendering'),
  png: t('exportPng'),
  jpg: t('exportJpg'),
  svg: t('exportSvg'),
  html: t('exportHtml'),
  copySvg: t('exportCopySvg'),
  copyHtml: t('exportCopyHtml'),
  exportError: t('exportError'),
}))
</script>

<style scoped>
.code-input {
  font-family:
    'JetBrains Mono', 'Fira Code', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas',
    'Liberation Mono', 'Courier New', monospace;
}
</style>

<!-- eslint-disable @intlify/vue-i18n/no-unused-keys -->
<i18n lang="json">
{
  "en": {
    "inputTitle": "Code",
    "styleTitle": "Style",
    "layoutTitle": "Layout",
    "previewTitle": "Preview",
    "exportTitle": "Export",
    "codeInputLabel": "Code input",
    "codePlaceholder": "Paste or type your snippet here...",
    "language": "Language",
    "languageAuto": "Auto",
    "renderMode": "Render mode",
    "renderModeHighlight": "Syntax highlight",
    "renderModePlain": "Plain text",
    "theme": "Theme",
    "backgroundType": "Background",
    "backgroundPreset": "Gradient",
    "backgroundSolid": "Solid color",
    "backgroundTransparent": "Transparent",
    "backgroundColor": "Background color",
    "backgroundPresetLabel": "Background preset",
    "windowStyle": "Window style",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "None",
    "lineNumbers": "Line numbers",
    "fontSize": "Font size",
    "lineHeight": "Line height",
    "cardPadding": "Card padding",
    "framePadding": "Canvas padding",
    "radius": "Corner radius",
    "shadow": "Shadow",
    "tabSize": "Tab size",
    "exportFileName": "File name",
    "exportScale": "Scale",
    "exportQuality": "JPG quality",
    "exportRendering": "Rendering preview...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Copy HTML",
    "exportError": "Export failed",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Sunrise",
    "theme.paper": "Paper",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Sunset",
    "background.ocean": "Ocean",
    "background.ember": "Ember",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "zh": {
    "inputTitle": "代码",
    "styleTitle": "样式",
    "layoutTitle": "布局",
    "previewTitle": "预览",
    "exportTitle": "导出",
    "codeInputLabel": "代码输入",
    "codePlaceholder": "在这里粘贴或输入代码...",
    "language": "语言",
    "languageAuto": "自动",
    "renderMode": "渲染模式",
    "renderModeHighlight": "语法高亮",
    "renderModePlain": "纯文本",
    "theme": "主题",
    "backgroundType": "背景",
    "backgroundPreset": "渐变",
    "backgroundSolid": "纯色",
    "backgroundTransparent": "透明",
    "backgroundColor": "背景颜色",
    "backgroundPresetLabel": "背景预设",
    "windowStyle": "窗口样式",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "无",
    "lineNumbers": "行号",
    "fontSize": "字号",
    "lineHeight": "行高",
    "cardPadding": "卡片内边距",
    "framePadding": "画布边距",
    "radius": "圆角",
    "shadow": "阴影",
    "tabSize": "Tab 宽度",
    "exportFileName": "文件名",
    "exportScale": "倍率",
    "exportQuality": "JPG 质量",
    "exportRendering": "正在渲染预览...",
    "exportPng": "下载PNG",
    "exportJpg": "下载JPG",
    "exportSvg": "下载SVG",
    "exportHtml": "下载HTML",
    "exportCopyHtml": "复制 HTML",
    "exportError": "导出失败",
    "theme.nebula": "星云",
    "theme.sunrise": "朝霞",
    "theme.paper": "纸感",
    "theme.terminal": "终端",
    "background.aurora": "极光",
    "background.sunset": "日落",
    "background.ocean": "海岸",
    "background.ember": "余烬",
    "background.noir": "暗影",
    "exportCopySvg": "复制SVG",
    "backgroundNone": "无"
  },
  "zh-CN": {
    "inputTitle": "代码",
    "styleTitle": "样式",
    "layoutTitle": "布局",
    "previewTitle": "预览",
    "exportTitle": "导出",
    "codeInputLabel": "代码输入",
    "codePlaceholder": "在这里粘贴或输入代码...",
    "language": "语言",
    "languageAuto": "自动",
    "renderMode": "渲染模式",
    "renderModeHighlight": "语法高亮",
    "renderModePlain": "纯文本",
    "theme": "主题",
    "backgroundType": "背景",
    "backgroundPreset": "渐变",
    "backgroundSolid": "纯色",
    "backgroundTransparent": "透明",
    "backgroundColor": "背景颜色",
    "backgroundPresetLabel": "背景预设",
    "windowStyle": "窗口样式",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "无",
    "lineNumbers": "行号",
    "fontSize": "字号",
    "lineHeight": "行高",
    "cardPadding": "卡片内边距",
    "framePadding": "画布边距",
    "radius": "圆角",
    "shadow": "阴影",
    "tabSize": "Tab 宽度",
    "exportFileName": "文件名",
    "exportScale": "倍率",
    "exportQuality": "JPG 质量",
    "exportRendering": "正在渲染预览...",
    "exportPng": "下载PNG",
    "exportJpg": "下载JPG",
    "exportSvg": "下载SVG",
    "exportHtml": "下载HTML",
    "exportCopyHtml": "复制 HTML",
    "exportError": "导出失败",
    "theme.nebula": "星云",
    "theme.sunrise": "朝霞",
    "theme.paper": "纸感",
    "theme.terminal": "终端",
    "background.aurora": "极光",
    "background.sunset": "日落",
    "background.ocean": "海岸",
    "background.ember": "余烬",
    "background.noir": "暗影",
    "exportCopySvg": "复制SVG",
    "backgroundNone": "无"
  },
  "zh-TW": {
    "inputTitle": "程式碼",
    "styleTitle": "樣式",
    "layoutTitle": "版面",
    "previewTitle": "預覽",
    "exportTitle": "匯出",
    "codeInputLabel": "程式碼輸入",
    "codePlaceholder": "在此貼上或輸入程式碼...",
    "language": "語言",
    "languageAuto": "自動",
    "renderMode": "渲染模式",
    "renderModeHighlight": "語法高亮",
    "renderModePlain": "純文字",
    "theme": "主題",
    "backgroundType": "背景",
    "backgroundPreset": "漸層",
    "backgroundSolid": "純色",
    "backgroundTransparent": "透明",
    "backgroundColor": "背景顏色",
    "backgroundPresetLabel": "背景預設",
    "windowStyle": "視窗樣式",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "無",
    "lineNumbers": "行號",
    "fontSize": "字級",
    "lineHeight": "行高",
    "cardPadding": "卡片內距",
    "framePadding": "畫布邊距",
    "radius": "圓角",
    "shadow": "陰影",
    "tabSize": "Tab 寬度",
    "exportFileName": "檔案名稱",
    "exportScale": "倍率",
    "exportQuality": "JPG 品質",
    "exportRendering": "正在渲染預覽...",
    "exportPng": "下載PNG",
    "exportJpg": "下載JPG",
    "exportSvg": "下載SVG",
    "exportHtml": "下載HTML",
    "exportCopyHtml": "複製 HTML",
    "exportError": "匯出失敗",
    "theme.nebula": "星雲",
    "theme.sunrise": "朝霞",
    "theme.paper": "紙感",
    "theme.terminal": "終端機",
    "background.aurora": "極光",
    "background.sunset": "日落",
    "background.ocean": "海岸",
    "background.ember": "餘燼",
    "background.noir": "暗影",
    "exportCopySvg": "複製SVG",
    "backgroundNone": "無"
  },
  "zh-HK": {
    "inputTitle": "程式碼",
    "styleTitle": "樣式",
    "layoutTitle": "版面",
    "previewTitle": "預覽",
    "exportTitle": "匯出",
    "codeInputLabel": "程式碼輸入",
    "codePlaceholder": "在此貼上或輸入程式碼...",
    "language": "語言",
    "languageAuto": "自動",
    "renderMode": "渲染模式",
    "renderModeHighlight": "語法高亮",
    "renderModePlain": "純文字",
    "theme": "主題",
    "backgroundType": "背景",
    "backgroundPreset": "漸層",
    "backgroundSolid": "純色",
    "backgroundTransparent": "透明",
    "backgroundColor": "背景顏色",
    "backgroundPresetLabel": "背景預設",
    "windowStyle": "視窗樣式",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "無",
    "lineNumbers": "行號",
    "fontSize": "字級",
    "lineHeight": "行高",
    "cardPadding": "卡片內距",
    "framePadding": "畫布邊距",
    "radius": "圓角",
    "shadow": "陰影",
    "tabSize": "Tab 寬度",
    "exportFileName": "檔案名稱",
    "exportScale": "倍率",
    "exportQuality": "JPG 品質",
    "exportRendering": "正在渲染預覽...",
    "exportPng": "下載PNG",
    "exportJpg": "下載JPG",
    "exportSvg": "下載SVG",
    "exportHtml": "下載HTML",
    "exportCopyHtml": "複製 HTML",
    "exportError": "匯出失敗",
    "theme.nebula": "星雲",
    "theme.sunrise": "朝霞",
    "theme.paper": "紙感",
    "theme.terminal": "終端機",
    "background.aurora": "極光",
    "background.sunset": "日落",
    "background.ocean": "海岸",
    "background.ember": "餘燼",
    "background.noir": "暗影",
    "exportCopySvg": "複製SVG",
    "backgroundNone": "無"
  },
  "es": {
    "inputTitle": "Código",
    "styleTitle": "Estilo",
    "layoutTitle": "Disposición",
    "previewTitle": "Vista previa",
    "exportTitle": "Exportar",
    "codeInputLabel": "Entrada de código",
    "codePlaceholder": "Pega o escribe tu fragmento aquí...",
    "language": "Idioma",
    "languageAuto": "Automático",
    "renderMode": "Modo de renderizado",
    "renderModeHighlight": "Resaltado de sintaxis",
    "renderModePlain": "Texto sin formato",
    "theme": "Tema",
    "backgroundType": "Fondo",
    "backgroundPreset": "Degradado",
    "backgroundSolid": "Color sólido",
    "backgroundTransparent": "Transparente",
    "backgroundColor": "Color de fondo",
    "backgroundPresetLabel": "Preajuste de fondo",
    "windowStyle": "Estilo de ventana",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Ninguno",
    "lineNumbers": "Números de línea",
    "fontSize": "Tamaño de fuente",
    "lineHeight": "Altura de línea",
    "cardPadding": "Relleno de tarjeta",
    "framePadding": "Relleno del lienzo",
    "radius": "Radio",
    "shadow": "Sombra",
    "tabSize": "Tamaño de tabulación",
    "exportFileName": "Nombre de archivo",
    "exportScale": "Escala",
    "exportQuality": "Calidad JPG",
    "exportRendering": "Renderizando vista previa...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Copiar HTML",
    "exportError": "Error al exportar",
    "theme.nebula": "Nébula",
    "theme.sunrise": "Amanecer",
    "theme.paper": "Papel",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Atardecer",
    "background.ocean": "Océano",
    "background.ember": "Ascua",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "fr": {
    "inputTitle": "Code",
    "styleTitle": "Style",
    "layoutTitle": "Mise en page",
    "previewTitle": "Aperçu",
    "exportTitle": "Exporter",
    "codeInputLabel": "Entrée du code",
    "codePlaceholder": "Collez ou tapez votre extrait ici...",
    "language": "Langue",
    "languageAuto": "Auto",
    "renderMode": "Mode de rendu",
    "renderModeHighlight": "Surlignage syntaxique",
    "renderModePlain": "Texte brut",
    "theme": "Thème",
    "backgroundType": "Arrière-plan",
    "backgroundPreset": "Dégradé",
    "backgroundSolid": "Couleur unie",
    "backgroundTransparent": "Transparent",
    "backgroundColor": "Couleur de fond",
    "backgroundPresetLabel": "Préréglage de fond",
    "windowStyle": "Style de fenêtre",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Aucun",
    "lineNumbers": "Numéros de ligne",
    "fontSize": "Taille de police",
    "lineHeight": "Hauteur de ligne",
    "cardPadding": "Marge interne",
    "framePadding": "Marge du canevas",
    "radius": "Rayon",
    "shadow": "Ombre",
    "tabSize": "Taille de tabulation",
    "exportFileName": "Nom du fichier",
    "exportScale": "Échelle",
    "exportQuality": "Qualité JPG",
    "exportRendering": "Rendu de l'aperçu...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Copier HTML",
    "exportError": "Échec de l'export",
    "theme.nebula": "Nébuleuse",
    "theme.sunrise": "Aurore",
    "theme.paper": "Papier",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurore",
    "background.sunset": "Coucher de soleil",
    "background.ocean": "Océan",
    "background.ember": "Braise",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "de": {
    "inputTitle": "Code",
    "styleTitle": "Stil",
    "layoutTitle": "Layout",
    "previewTitle": "Vorschau",
    "exportTitle": "Export",
    "codeInputLabel": "Code-Eingabe",
    "codePlaceholder": "Füge deinen Code hier ein oder tippe ihn ein...",
    "language": "Sprache",
    "languageAuto": "Auto",
    "renderMode": "Render-Modus",
    "renderModeHighlight": "Syntax-Highlighting",
    "renderModePlain": "Klartext",
    "theme": "Thema",
    "backgroundType": "Hintergrund",
    "backgroundPreset": "Verlauf",
    "backgroundSolid": "Einfarbig",
    "backgroundTransparent": "Transparent",
    "backgroundColor": "Hintergrundfarbe",
    "backgroundPresetLabel": "Hintergrund-Preset",
    "windowStyle": "Fensterstil",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Keiner",
    "lineNumbers": "Zeilennummern",
    "fontSize": "Schriftgröße",
    "lineHeight": "Zeilenhöhe",
    "cardPadding": "Innenabstand",
    "framePadding": "Canvas-Abstand",
    "radius": "Radius",
    "shadow": "Schatten",
    "tabSize": "Tabulatorgröße",
    "exportFileName": "Dateiname",
    "exportScale": "Skalierung",
    "exportQuality": "JPG-Qualität",
    "exportRendering": "Vorschau wird gerendert...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML kopieren",
    "exportError": "Export fehlgeschlagen",
    "theme.nebula": "Nebel",
    "theme.sunrise": "Sonnenaufgang",
    "theme.paper": "Papier",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Sonnenuntergang",
    "background.ocean": "Ozean",
    "background.ember": "Glut",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "it": {
    "inputTitle": "Codice",
    "styleTitle": "Stile",
    "layoutTitle": "Layout",
    "previewTitle": "Anteprima",
    "exportTitle": "Esporta",
    "codeInputLabel": "Input codice",
    "codePlaceholder": "Incolla o digita il tuo snippet qui...",
    "language": "Lingua",
    "languageAuto": "Auto",
    "renderMode": "Modalità di rendering",
    "renderModeHighlight": "Evidenziazione sintassi",
    "renderModePlain": "Testo semplice",
    "theme": "Tema",
    "backgroundType": "Sfondo",
    "backgroundPreset": "Gradiente",
    "backgroundSolid": "Colore pieno",
    "backgroundTransparent": "Trasparente",
    "backgroundColor": "Colore di sfondo",
    "backgroundPresetLabel": "Preset sfondo",
    "windowStyle": "Stile finestra",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Nessuno",
    "lineNumbers": "Numeri di riga",
    "fontSize": "Dimensione font",
    "lineHeight": "Interlinea",
    "cardPadding": "Padding scheda",
    "framePadding": "Padding canvas",
    "radius": "Raggio",
    "shadow": "Ombra",
    "tabSize": "Dimensione tab",
    "exportFileName": "Nome file",
    "exportScale": "Scala",
    "exportQuality": "Qualità JPG",
    "exportRendering": "Rendering anteprima...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Copia HTML",
    "exportError": "Esportazione non riuscita",
    "theme.nebula": "Nebulosa",
    "theme.sunrise": "Alba",
    "theme.paper": "Carta",
    "theme.terminal": "Terminale",
    "background.aurora": "Aurora",
    "background.sunset": "Tramonto",
    "background.ocean": "Oceano",
    "background.ember": "Brace",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "ja": {
    "inputTitle": "コード",
    "styleTitle": "スタイル",
    "layoutTitle": "レイアウト",
    "previewTitle": "プレビュー",
    "exportTitle": "書き出し",
    "codeInputLabel": "コード入力",
    "codePlaceholder": "ここにコードを貼り付けるか入力してください...",
    "language": "言語",
    "languageAuto": "自動",
    "renderMode": "描画モード",
    "renderModeHighlight": "シンタックスハイライト",
    "renderModePlain": "プレーンテキスト",
    "theme": "テーマ",
    "backgroundType": "背景",
    "backgroundPreset": "グラデーション",
    "backgroundSolid": "単色",
    "backgroundTransparent": "透明",
    "backgroundColor": "背景色",
    "backgroundPresetLabel": "背景プリセット",
    "windowStyle": "ウィンドウスタイル",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "なし",
    "lineNumbers": "行番号",
    "fontSize": "フォントサイズ",
    "lineHeight": "行間",
    "cardPadding": "カード余白",
    "framePadding": "キャンバス余白",
    "radius": "角丸",
    "shadow": "影",
    "tabSize": "タブ幅",
    "exportFileName": "ファイル名",
    "exportScale": "倍率",
    "exportQuality": "JPG 品質",
    "exportRendering": "プレビューを生成中...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML をコピー",
    "exportError": "書き出しに失敗しました",
    "theme.nebula": "星雲",
    "theme.sunrise": "朝焼け",
    "theme.paper": "紙",
    "theme.terminal": "ターミナル",
    "background.aurora": "オーロラ",
    "background.sunset": "サンセット",
    "background.ocean": "オーシャン",
    "background.ember": "アンバー",
    "background.noir": "ノワール",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "ko": {
    "inputTitle": "코드",
    "styleTitle": "스타일",
    "layoutTitle": "레이아웃",
    "previewTitle": "미리보기",
    "exportTitle": "내보내기",
    "codeInputLabel": "코드 입력",
    "codePlaceholder": "여기에 코드를 붙여넣거나 입력하세요...",
    "language": "언어",
    "languageAuto": "자동",
    "renderMode": "렌더링 모드",
    "renderModeHighlight": "구문 강조",
    "renderModePlain": "일반 텍스트",
    "theme": "테마",
    "backgroundType": "배경",
    "backgroundPreset": "그라디언트",
    "backgroundSolid": "단색",
    "backgroundTransparent": "투명",
    "backgroundColor": "배경색",
    "backgroundPresetLabel": "배경 프리셋",
    "windowStyle": "창 스타일",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "없음",
    "lineNumbers": "줄 번호",
    "fontSize": "글꼴 크기",
    "lineHeight": "줄 간격",
    "cardPadding": "카드 여백",
    "framePadding": "캔버스 여백",
    "radius": "모서리 반경",
    "shadow": "그림자",
    "tabSize": "탭 크기",
    "exportFileName": "파일 이름",
    "exportScale": "배율",
    "exportQuality": "JPG 품질",
    "exportRendering": "미리보기를 렌더링 중...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML 복사",
    "exportError": "내보내기 실패",
    "theme.nebula": "네뷸라",
    "theme.sunrise": "선라이즈",
    "theme.paper": "페이퍼",
    "theme.terminal": "터미널",
    "background.aurora": "오로라",
    "background.sunset": "선셋",
    "background.ocean": "오션",
    "background.ember": "엠버",
    "background.noir": "누아르",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "ru": {
    "inputTitle": "Код",
    "styleTitle": "Стиль",
    "layoutTitle": "Макет",
    "previewTitle": "Предпросмотр",
    "exportTitle": "Экспорт",
    "codeInputLabel": "Ввод кода",
    "codePlaceholder": "Вставьте или введите фрагмент здесь...",
    "language": "Язык",
    "languageAuto": "Авто",
    "renderMode": "Режим рендеринга",
    "renderModeHighlight": "Подсветка синтаксиса",
    "renderModePlain": "Обычный текст",
    "theme": "Тема",
    "backgroundType": "Фон",
    "backgroundPreset": "Градиент",
    "backgroundSolid": "Сплошной цвет",
    "backgroundTransparent": "Прозрачный",
    "backgroundColor": "Цвет фона",
    "backgroundPresetLabel": "Пресет фона",
    "windowStyle": "Стиль окна",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Нет",
    "lineNumbers": "Номера строк",
    "fontSize": "Размер шрифта",
    "lineHeight": "Высота строки",
    "cardPadding": "Внутренние поля",
    "framePadding": "Поля холста",
    "radius": "Радиус",
    "shadow": "Тень",
    "tabSize": "Размер табуляции",
    "exportFileName": "Имя файла",
    "exportScale": "Масштаб",
    "exportQuality": "Качество JPG",
    "exportRendering": "Рендеринг предпросмотра...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Копировать HTML",
    "exportError": "Ошибка экспорта",
    "theme.nebula": "Туманность",
    "theme.sunrise": "Рассвет",
    "theme.paper": "Бумага",
    "theme.terminal": "Терминал",
    "background.aurora": "Аврора",
    "background.sunset": "Закат",
    "background.ocean": "Океан",
    "background.ember": "Уголь",
    "background.noir": "Нуар",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "pt": {
    "inputTitle": "Código",
    "styleTitle": "Estilo",
    "layoutTitle": "Layout",
    "previewTitle": "Pré-visualização",
    "exportTitle": "Exportar",
    "codeInputLabel": "Entrada de código",
    "codePlaceholder": "Cole ou digite seu trecho aqui...",
    "language": "Idioma",
    "languageAuto": "Auto",
    "renderMode": "Modo de renderização",
    "renderModeHighlight": "Realce de sintaxe",
    "renderModePlain": "Texto simples",
    "theme": "Tema",
    "backgroundType": "Fundo",
    "backgroundPreset": "Gradiente",
    "backgroundSolid": "Cor sólida",
    "backgroundTransparent": "Transparente",
    "backgroundColor": "Cor de fundo",
    "backgroundPresetLabel": "Predefinição de fundo",
    "windowStyle": "Estilo da janela",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Nenhum",
    "lineNumbers": "Números de linha",
    "fontSize": "Tamanho da fonte",
    "lineHeight": "Altura da linha",
    "cardPadding": "Padding do cartão",
    "framePadding": "Padding do canvas",
    "radius": "Raio",
    "shadow": "Sombra",
    "tabSize": "Tamanho da tabulação",
    "exportFileName": "Nome do arquivo",
    "exportScale": "Escala",
    "exportQuality": "Qualidade JPG",
    "exportRendering": "Renderizando prévia...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Copiar HTML",
    "exportError": "Falha ao exportar",
    "theme.nebula": "Nebulosa",
    "theme.sunrise": "Nascer do sol",
    "theme.paper": "Papel",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Pôr do sol",
    "background.ocean": "Oceano",
    "background.ember": "Brasa",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "ar": {
    "inputTitle": "الكود",
    "styleTitle": "النمط",
    "layoutTitle": "التخطيط",
    "previewTitle": "المعاينة",
    "exportTitle": "تصدير",
    "codeInputLabel": "إدخال الكود",
    "codePlaceholder": "الصق أو اكتب المقتطف هنا...",
    "language": "اللغة",
    "languageAuto": "تلقائي",
    "renderMode": "وضع العرض",
    "renderModeHighlight": "تمييز الصياغة",
    "renderModePlain": "نص عادي",
    "theme": "السمة",
    "backgroundType": "الخلفية",
    "backgroundPreset": "تدرج",
    "backgroundSolid": "لون ثابت",
    "backgroundTransparent": "شفاف",
    "backgroundColor": "لون الخلفية",
    "backgroundPresetLabel": "إعداد الخلفية",
    "windowStyle": "نمط النافذة",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "بدون",
    "lineNumbers": "أرقام الأسطر",
    "fontSize": "حجم الخط",
    "lineHeight": "ارتفاع السطر",
    "cardPadding": "حشو البطاقة",
    "framePadding": "حشو اللوحة",
    "radius": "نصف القطر",
    "shadow": "الظل",
    "tabSize": "حجم التبويب",
    "exportFileName": "اسم الملف",
    "exportScale": "المقياس",
    "exportQuality": "جودة JPG",
    "exportRendering": "جارٍ إنشاء المعاينة...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "نسخ HTML",
    "exportError": "فشل التصدير",
    "theme.nebula": "سديم",
    "theme.sunrise": "شروق",
    "theme.paper": "ورق",
    "theme.terminal": "طرفية",
    "background.aurora": "شفق",
    "background.sunset": "غروب",
    "background.ocean": "محيط",
    "background.ember": "جمر",
    "background.noir": "نوار",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "hi": {
    "inputTitle": "कोड",
    "styleTitle": "स्टाइल",
    "layoutTitle": "लेआउट",
    "previewTitle": "प्रीव्यू",
    "exportTitle": "निर्यात",
    "codeInputLabel": "कोड इनपुट",
    "codePlaceholder": "अपना स्निपेट यहां पेस्ट या टाइप करें...",
    "language": "भाषा",
    "languageAuto": "स्वचालित",
    "renderMode": "रेंडर मोड",
    "renderModeHighlight": "सिंटैक्स हाइलाइट",
    "renderModePlain": "सादा टेक्स्ट",
    "theme": "थीम",
    "backgroundType": "पृष्ठभूमि",
    "backgroundPreset": "ग्रेडिएंट",
    "backgroundSolid": "एकरंगी",
    "backgroundTransparent": "पारदर्शी",
    "backgroundColor": "पृष्ठभूमि रंग",
    "backgroundPresetLabel": "पृष्ठभूमि प्रीसेट",
    "windowStyle": "विंडो शैली",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "कोई नहीं",
    "lineNumbers": "लाइन नंबर",
    "fontSize": "फ़ॉन्ट आकार",
    "lineHeight": "लाइन ऊंचाई",
    "cardPadding": "कार्ड पैडिंग",
    "framePadding": "कैनवास पैडिंग",
    "radius": "रेडियस",
    "shadow": "छाया",
    "tabSize": "टैब आकार",
    "exportFileName": "फ़ाइल नाम",
    "exportScale": "स्केल",
    "exportQuality": "JPG गुणवत्ता",
    "exportRendering": "प्रीव्यू रेंडर हो रहा है...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML कॉपी करें",
    "exportError": "निर्यात विफल",
    "theme.nebula": "नेबुला",
    "theme.sunrise": "सनराइज़",
    "theme.paper": "पेपर",
    "theme.terminal": "टर्मिनल",
    "background.aurora": "ऑरोरा",
    "background.sunset": "सनसेट",
    "background.ocean": "ओशन",
    "background.ember": "एंबर",
    "background.noir": "नोयर",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "tr": {
    "inputTitle": "Kod",
    "styleTitle": "Stil",
    "layoutTitle": "Düzen",
    "previewTitle": "Önizleme",
    "exportTitle": "Dışa aktar",
    "codeInputLabel": "Kod girişi",
    "codePlaceholder": "Parçayı buraya yapıştırın veya yazın...",
    "language": "Dil",
    "languageAuto": "Otomatik",
    "renderMode": "Render modu",
    "renderModeHighlight": "Sözdizimi vurgusu",
    "renderModePlain": "Düz metin",
    "theme": "Tema",
    "backgroundType": "Arka plan",
    "backgroundPreset": "Gradyan",
    "backgroundSolid": "Düz renk",
    "backgroundTransparent": "Şeffaf",
    "backgroundColor": "Arka plan rengi",
    "backgroundPresetLabel": "Arka plan ön ayarı",
    "windowStyle": "Pencere stili",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Yok",
    "lineNumbers": "Satır numaraları",
    "fontSize": "Yazı tipi boyutu",
    "lineHeight": "Satır yüksekliği",
    "cardPadding": "Kart dolgusu",
    "framePadding": "Tuval dolgusu",
    "radius": "Yarıçap",
    "shadow": "Gölge",
    "tabSize": "Sekme boyutu",
    "exportFileName": "Dosya adı",
    "exportScale": "Ölçek",
    "exportQuality": "JPG kalitesi",
    "exportRendering": "Önizleme oluşturuluyor...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML kopyala",
    "exportError": "Dışa aktarma başarısız",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Gündoğumu",
    "theme.paper": "Kağıt",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Gün batımı",
    "background.ocean": "Okyanus",
    "background.ember": "Kızıl",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "nl": {
    "inputTitle": "Code",
    "styleTitle": "Stijl",
    "layoutTitle": "Lay-out",
    "previewTitle": "Voorbeeld",
    "exportTitle": "Exporteren",
    "codeInputLabel": "Code-invoer",
    "codePlaceholder": "Plak of typ je snippet hier...",
    "language": "Taal",
    "languageAuto": "Automatisch",
    "renderMode": "Render-modus",
    "renderModeHighlight": "Syntaxmarkering",
    "renderModePlain": "Platte tekst",
    "theme": "Thema",
    "backgroundType": "Achtergrond",
    "backgroundPreset": "Verloop",
    "backgroundSolid": "Effen kleur",
    "backgroundTransparent": "Transparant",
    "backgroundColor": "Achtergrondkleur",
    "backgroundPresetLabel": "Achtergrondpreset",
    "windowStyle": "Vensterstijl",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Geen",
    "lineNumbers": "Regelnummers",
    "fontSize": "Lettergrootte",
    "lineHeight": "Regelhoogte",
    "cardPadding": "Kaartopvulling",
    "framePadding": "Canvas-opvulling",
    "radius": "Radius",
    "shadow": "Schaduw",
    "tabSize": "Tabgrootte",
    "exportFileName": "Bestandsnaam",
    "exportScale": "Schaal",
    "exportQuality": "JPG-kwaliteit",
    "exportRendering": "Voorbeeld wordt gerenderd...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "HTML kopiëren",
    "exportError": "Export mislukt",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Zonsopkomst",
    "theme.paper": "Papier",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Zonsondergang",
    "background.ocean": "Oceaan",
    "background.ember": "Gloed",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "sv": {
    "inputTitle": "Kod",
    "styleTitle": "Stil",
    "layoutTitle": "Layout",
    "previewTitle": "Förhandsvisning",
    "exportTitle": "Exportera",
    "codeInputLabel": "Kodindata",
    "codePlaceholder": "Klistra in eller skriv ditt kodstycke här...",
    "language": "Språk",
    "languageAuto": "Auto",
    "renderMode": "Renderingsläge",
    "renderModeHighlight": "Syntaxmarkering",
    "renderModePlain": "Ren text",
    "theme": "Tema",
    "backgroundType": "Bakgrund",
    "backgroundPreset": "Gradient",
    "backgroundSolid": "Enfärgad",
    "backgroundTransparent": "Transparent",
    "backgroundColor": "Bakgrundsfärg",
    "backgroundPresetLabel": "Bakgrundspreset",
    "windowStyle": "Fönsterstil",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Ingen",
    "lineNumbers": "Radnummer",
    "fontSize": "Teckenstorlek",
    "lineHeight": "Radhöjd",
    "cardPadding": "Kortmarginal",
    "framePadding": "Canvas-marginal",
    "radius": "Radie",
    "shadow": "Skugga",
    "tabSize": "Tabbstorlek",
    "exportFileName": "Filnamn",
    "exportScale": "Skala",
    "exportQuality": "JPG-kvalitet",
    "exportRendering": "Renderar förhandsvisning...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Kopiera HTML",
    "exportError": "Export misslyckades",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Soluppgång",
    "theme.paper": "Papper",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Solnedgång",
    "background.ocean": "Hav",
    "background.ember": "Glöd",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "pl": {
    "inputTitle": "Kod",
    "styleTitle": "Styl",
    "layoutTitle": "Układ",
    "previewTitle": "Podgląd",
    "exportTitle": "Eksport",
    "codeInputLabel": "Wejście kodu",
    "codePlaceholder": "Wklej lub wpisz fragment tutaj...",
    "language": "Język",
    "languageAuto": "Auto",
    "renderMode": "Tryb renderowania",
    "renderModeHighlight": "Podświetlanie składni",
    "renderModePlain": "Zwykły tekst",
    "theme": "Motyw",
    "backgroundType": "Tło",
    "backgroundPreset": "Gradient",
    "backgroundSolid": "Jednolity kolor",
    "backgroundTransparent": "Przezroczyste",
    "backgroundColor": "Kolor tła",
    "backgroundPresetLabel": "Preset tła",
    "windowStyle": "Styl okna",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Brak",
    "lineNumbers": "Numery wierszy",
    "fontSize": "Rozmiar czcionki",
    "lineHeight": "Wysokość wiersza",
    "cardPadding": "Wypełnienie karty",
    "framePadding": "Wypełnienie płótna",
    "radius": "Promień",
    "shadow": "Cień",
    "tabSize": "Rozmiar tabulatora",
    "exportFileName": "Nazwa pliku",
    "exportScale": "Skala",
    "exportQuality": "Jakość JPG",
    "exportRendering": "Renderowanie podglądu...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Kopiuj HTML",
    "exportError": "Eksport nie powiódł się",
    "theme.nebula": "Mgławica",
    "theme.sunrise": "Wschód",
    "theme.paper": "Papier",
    "theme.terminal": "Terminal",
    "background.aurora": "Zorza",
    "background.sunset": "Zachód",
    "background.ocean": "Ocean",
    "background.ember": "Żar",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "vi": {
    "inputTitle": "Mã",
    "styleTitle": "Phong cách",
    "layoutTitle": "Bố cục",
    "previewTitle": "Xem trước",
    "exportTitle": "Xuất",
    "codeInputLabel": "Nhập mã",
    "codePlaceholder": "Dán hoặc nhập đoạn mã ở đây...",
    "language": "Ngôn ngữ",
    "languageAuto": "Tự động",
    "renderMode": "Chế độ hiển thị",
    "renderModeHighlight": "Tô sáng cú pháp",
    "renderModePlain": "Văn bản thuần",
    "theme": "Chủ đề",
    "backgroundType": "Nền",
    "backgroundPreset": "Chuyển sắc",
    "backgroundSolid": "Màu đơn",
    "backgroundTransparent": "Trong suốt",
    "backgroundColor": "Màu nền",
    "backgroundPresetLabel": "Thiết lập nền",
    "windowStyle": "Kiểu cửa sổ",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Không",
    "lineNumbers": "Số dòng",
    "fontSize": "Cỡ chữ",
    "lineHeight": "Chiều cao dòng",
    "cardPadding": "Lề trong thẻ",
    "framePadding": "Lề canvas",
    "radius": "Bo góc",
    "shadow": "Bóng",
    "tabSize": "Cỡ tab",
    "exportFileName": "Tên tệp",
    "exportScale": "Tỉ lệ",
    "exportQuality": "Chất lượng JPG",
    "exportRendering": "Đang kết xuất xem trước...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Sao chép HTML",
    "exportError": "Xuất thất bại",
    "theme.nebula": "Tinh vân",
    "theme.sunrise": "Bình minh",
    "theme.paper": "Giấy",
    "theme.terminal": "Terminal",
    "background.aurora": "Cực quang",
    "background.sunset": "Hoàng hôn",
    "background.ocean": "Đại dương",
    "background.ember": "Tàn lửa",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "th": {
    "inputTitle": "โค้ด",
    "styleTitle": "สไตล์",
    "layoutTitle": "เลย์เอาต์",
    "previewTitle": "ตัวอย่าง",
    "exportTitle": "ส่งออก",
    "codeInputLabel": "ป้อนโค้ด",
    "codePlaceholder": "วางหรือพิมพ์โค้ดของคุณที่นี่...",
    "language": "ภาษา",
    "languageAuto": "อัตโนมัติ",
    "renderMode": "โหมดเรนเดอร์",
    "renderModeHighlight": "ไฮไลต์ไวยากรณ์",
    "renderModePlain": "ข้อความธรรมดา",
    "theme": "ธีม",
    "backgroundType": "พื้นหลัง",
    "backgroundPreset": "ไล่สี",
    "backgroundSolid": "สีทึบ",
    "backgroundTransparent": "โปร่งใส",
    "backgroundColor": "สีพื้นหลัง",
    "backgroundPresetLabel": "พรีเซ็ตพื้นหลัง",
    "windowStyle": "สไตล์หน้าต่าง",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "ไม่มี",
    "lineNumbers": "หมายเลขบรรทัด",
    "fontSize": "ขนาดตัวอักษร",
    "lineHeight": "ความสูงบรรทัด",
    "cardPadding": "ระยะขอบการ์ด",
    "framePadding": "ระยะขอบผ้าใบ",
    "radius": "รัศมี",
    "shadow": "เงา",
    "tabSize": "ขนาดแท็บ",
    "exportFileName": "ชื่อไฟล์",
    "exportScale": "สเกล",
    "exportQuality": "คุณภาพ JPG",
    "exportRendering": "กำลังเรนเดอร์ตัวอย่าง...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "คัดลอก HTML",
    "exportError": "ส่งออกล้มเหลว",
    "theme.nebula": "เนบิวลา",
    "theme.sunrise": "รุ่งอรุณ",
    "theme.paper": "กระดาษ",
    "theme.terminal": "เทอร์มินัล",
    "background.aurora": "ออโรรา",
    "background.sunset": "พระอาทิตย์ตก",
    "background.ocean": "มหาสมุทร",
    "background.ember": "ถ่านแดง",
    "background.noir": "นัวร์",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "id": {
    "inputTitle": "Kode",
    "styleTitle": "Gaya",
    "layoutTitle": "Tata letak",
    "previewTitle": "Pratinjau",
    "exportTitle": "Ekspor",
    "codeInputLabel": "Input kode",
    "codePlaceholder": "Tempel atau ketik potongan kode di sini...",
    "language": "Bahasa",
    "languageAuto": "Otomatis",
    "renderMode": "Mode render",
    "renderModeHighlight": "Sorotan sintaks",
    "renderModePlain": "Teks biasa",
    "theme": "Tema",
    "backgroundType": "Latar",
    "backgroundPreset": "Gradien",
    "backgroundSolid": "Warna solid",
    "backgroundTransparent": "Transparan",
    "backgroundColor": "Warna latar",
    "backgroundPresetLabel": "Preset latar",
    "windowStyle": "Gaya jendela",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Tidak ada",
    "lineNumbers": "Nomor baris",
    "fontSize": "Ukuran font",
    "lineHeight": "Tinggi baris",
    "cardPadding": "Padding kartu",
    "framePadding": "Padding kanvas",
    "radius": "Radius",
    "shadow": "Bayangan",
    "tabSize": "Ukuran tab",
    "exportFileName": "Nama file",
    "exportScale": "Skala",
    "exportQuality": "Kualitas JPG",
    "exportRendering": "Merender pratinjau...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Salin HTML",
    "exportError": "Ekspor gagal",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Sunrise",
    "theme.paper": "Kertas",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Sunset",
    "background.ocean": "Laut",
    "background.ember": "Bara",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "he": {
    "inputTitle": "קוד",
    "styleTitle": "סגנון",
    "layoutTitle": "פריסה",
    "previewTitle": "תצוגה מקדימה",
    "exportTitle": "ייצוא",
    "codeInputLabel": "קלט קוד",
    "codePlaceholder": "הדבק או הקלד את המקטע כאן...",
    "language": "שפה",
    "languageAuto": "אוטומטי",
    "renderMode": "מצב עיבוד",
    "renderModeHighlight": "הדגשת תחביר",
    "renderModePlain": "טקסט רגיל",
    "theme": "ערכת נושא",
    "backgroundType": "רקע",
    "backgroundPreset": "גרדיאנט",
    "backgroundSolid": "צבע אחיד",
    "backgroundTransparent": "שקוף",
    "backgroundColor": "צבע רקע",
    "backgroundPresetLabel": "ערכת רקע",
    "windowStyle": "סגנון חלון",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "ללא",
    "lineNumbers": "מספרי שורות",
    "fontSize": "גודל גופן",
    "lineHeight": "גובה שורה",
    "cardPadding": "ריפוד כרטיס",
    "framePadding": "ריפוד קנבס",
    "radius": "רדיוס",
    "shadow": "צל",
    "tabSize": "גודל טאב",
    "exportFileName": "שם קובץ",
    "exportScale": "קנה מידה",
    "exportQuality": "איכות JPG",
    "exportRendering": "מעבד תצוגה מקדימה...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "העתק HTML",
    "exportError": "הייצוא נכשל",
    "theme.nebula": "ערפילית",
    "theme.sunrise": "זריחה",
    "theme.paper": "נייר",
    "theme.terminal": "טרמינל",
    "background.aurora": "אורורה",
    "background.sunset": "שקיעה",
    "background.ocean": "אוקיינוס",
    "background.ember": "גחלת",
    "background.noir": "נואר",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "ms": {
    "inputTitle": "Kod",
    "styleTitle": "Gaya",
    "layoutTitle": "Susun atur",
    "previewTitle": "Pratonton",
    "exportTitle": "Eksport",
    "codeInputLabel": "Input kod",
    "codePlaceholder": "Tampal atau taip potongan kod di sini...",
    "language": "Bahasa",
    "languageAuto": "Auto",
    "renderMode": "Mod render",
    "renderModeHighlight": "Sorotan sintaks",
    "renderModePlain": "Teks biasa",
    "theme": "Tema",
    "backgroundType": "Latar belakang",
    "backgroundPreset": "Gradien",
    "backgroundSolid": "Warna pepejal",
    "backgroundTransparent": "Lutsinar",
    "backgroundColor": "Warna latar",
    "backgroundPresetLabel": "Pratetap latar",
    "windowStyle": "Gaya tetingkap",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Tiada",
    "lineNumbers": "Nombor baris",
    "fontSize": "Saiz fon",
    "lineHeight": "Ketinggian baris",
    "cardPadding": "Padding kad",
    "framePadding": "Padding kanvas",
    "radius": "Jejari",
    "shadow": "Bayang",
    "tabSize": "Saiz tab",
    "exportFileName": "Nama fail",
    "exportScale": "Skala",
    "exportQuality": "Kualiti JPG",
    "exportRendering": "Merender pratonton...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Salin HTML",
    "exportError": "Eksport gagal",
    "theme.nebula": "Nebula",
    "theme.sunrise": "Matahari terbit",
    "theme.paper": "Kertas",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Matahari terbenam",
    "background.ocean": "Lautan",
    "background.ember": "Bara",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  },
  "no": {
    "inputTitle": "Kode",
    "styleTitle": "Stil",
    "layoutTitle": "Oppsett",
    "previewTitle": "Forhåndsvisning",
    "exportTitle": "Eksport",
    "codeInputLabel": "Kodeinndata",
    "codePlaceholder": "Lim inn eller skriv utdraget her...",
    "language": "Språk",
    "languageAuto": "Auto",
    "renderMode": "Rendermodus",
    "renderModeHighlight": "Syntaksutheving",
    "renderModePlain": "Ren tekst",
    "theme": "Tema",
    "backgroundType": "Bakgrunn",
    "backgroundPreset": "Gradient",
    "backgroundSolid": "Heldekkende farge",
    "backgroundTransparent": "Gjennomsiktig",
    "backgroundColor": "Bakgrunnsfarge",
    "backgroundPresetLabel": "Bakgrunnspreset",
    "windowStyle": "Vindusstil",
    "windowMac": "macOS",
    "windowWindows": "Windows",
    "windowNone": "Ingen",
    "lineNumbers": "Linjenummer",
    "fontSize": "Skriftstørrelse",
    "lineHeight": "Linjehøyde",
    "cardPadding": "Kortpadding",
    "framePadding": "Canvas-padding",
    "radius": "Radius",
    "shadow": "Skygge",
    "tabSize": "Tabbstørrelse",
    "exportFileName": "Filnavn",
    "exportScale": "Skala",
    "exportQuality": "JPG-kvalitet",
    "exportRendering": "Rendrer forhåndsvisning...",
    "exportPng": "Download PNG",
    "exportJpg": "Download JPG",
    "exportSvg": "Download SVG",
    "exportHtml": "Download HTML",
    "exportCopyHtml": "Kopier HTML",
    "exportError": "Eksport mislyktes",
    "theme.nebula": "Tåke",
    "theme.sunrise": "Soloppgang",
    "theme.paper": "Papir",
    "theme.terminal": "Terminal",
    "background.aurora": "Aurora",
    "background.sunset": "Solnedgang",
    "background.ocean": "Hav",
    "background.ember": "Glør",
    "background.noir": "Noir",
    "exportCopySvg": "Copy SVG",
    "backgroundNone": "None"
  }
}
</i18n>
