<template>
  <slot :labels="labels" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n({ useScope: 'local' })
const labels = computed(() => ({
  targetSizeLabel: t('targetSizeLabel'),
  targetPsnrLabel: t('targetPsnrLabel'),
  nearLosslessLabel: t('nearLosslessLabel'),
  alphaQualityLabel: t('alphaQualityLabel'),
  snsStrengthLabel: t('snsStrengthLabel'),
  filterStrengthLabel: t('filterStrengthLabel'),
  filterSharpnessLabel: t('filterSharpnessLabel'),
  filterTypeLabel: t('filterTypeLabel'),
  partitionsLabel: t('partitionsLabel'),
  segmentsLabel: t('segmentsLabel'),
  passLabel: t('passLabel'),
  exactLabel: t('exactLabel'),
  useSharpYuvLabel: t('useSharpYuvLabel'),
  optionDefault: t('optionDefault'),
  optionOn: t('optionOn'),
  optionOff: t('optionOff'),
}))
</script>

<i18n lang="json">
{
  "en": {
    "targetSizeLabel": "Target size (KB)",
    "targetPsnrLabel": "Target PSNR",
    "nearLosslessLabel": "Near lossless",
    "alphaQualityLabel": "Alpha quality",
    "snsStrengthLabel": "SNS strength",
    "filterStrengthLabel": "Filter strength",
    "filterSharpnessLabel": "Filter sharpness",
    "filterTypeLabel": "Filter type",
    "partitionsLabel": "Partitions",
    "segmentsLabel": "Segments",
    "passLabel": "Passes",
    "exactLabel": "Exact",
    "useSharpYuvLabel": "Sharp YUV",
    "optionDefault": "Default",
    "optionOn": "On",
    "optionOff": "Off"
  },
  "zh": {
    "targetSizeLabel": "目标大小 (KB)",
    "targetPsnrLabel": "目标 PSNR",
    "nearLosslessLabel": "近无损",
    "alphaQualityLabel": "透明度质量",
    "snsStrengthLabel": "SNS 强度",
    "filterStrengthLabel": "滤镜强度",
    "filterSharpnessLabel": "滤镜锐度",
    "filterTypeLabel": "滤镜类型",
    "partitionsLabel": "分区数",
    "segmentsLabel": "分段数",
    "passLabel": "遍数",
    "exactLabel": "精确透明",
    "useSharpYuvLabel": "锐化 YUV",
    "optionDefault": "默认",
    "optionOn": "开启",
    "optionOff": "关闭"
  },
  "zh-CN": {
    "targetSizeLabel": "目标大小 (KB)",
    "targetPsnrLabel": "目标 PSNR",
    "nearLosslessLabel": "近无损",
    "alphaQualityLabel": "透明度质量",
    "snsStrengthLabel": "SNS 强度",
    "filterStrengthLabel": "滤镜强度",
    "filterSharpnessLabel": "滤镜锐度",
    "filterTypeLabel": "滤镜类型",
    "partitionsLabel": "分区数",
    "segmentsLabel": "分段数",
    "passLabel": "遍数",
    "exactLabel": "精确透明",
    "useSharpYuvLabel": "锐化 YUV",
    "optionDefault": "默认",
    "optionOn": "开启",
    "optionOff": "关闭"
  },
  "zh-TW": {
    "targetSizeLabel": "目標大小 (KB)",
    "targetPsnrLabel": "目標 PSNR",
    "nearLosslessLabel": "近無損",
    "alphaQualityLabel": "透明度品質",
    "snsStrengthLabel": "SNS 強度",
    "filterStrengthLabel": "濾鏡強度",
    "filterSharpnessLabel": "濾鏡銳度",
    "filterTypeLabel": "濾鏡類型",
    "partitionsLabel": "分區數",
    "segmentsLabel": "分段數",
    "passLabel": "次數",
    "exactLabel": "精確透明",
    "useSharpYuvLabel": "銳化 YUV",
    "optionDefault": "預設",
    "optionOn": "開啟",
    "optionOff": "關閉"
  },
  "zh-HK": {
    "targetSizeLabel": "目標大小 (KB)",
    "targetPsnrLabel": "目標 PSNR",
    "nearLosslessLabel": "近無損",
    "alphaQualityLabel": "透明度品質",
    "snsStrengthLabel": "SNS 強度",
    "filterStrengthLabel": "濾鏡強度",
    "filterSharpnessLabel": "濾鏡銳度",
    "filterTypeLabel": "濾鏡類型",
    "partitionsLabel": "分區數",
    "segmentsLabel": "分段數",
    "passLabel": "次數",
    "exactLabel": "精確透明",
    "useSharpYuvLabel": "銳化 YUV",
    "optionDefault": "預設",
    "optionOn": "開啟",
    "optionOff": "關閉"
  },
  "es": {
    "targetSizeLabel": "Tamaño objetivo (KB)",
    "targetPsnrLabel": "PSNR objetivo",
    "nearLosslessLabel": "Casi sin pérdidas",
    "alphaQualityLabel": "Calidad alfa",
    "snsStrengthLabel": "Fuerza SNS",
    "filterStrengthLabel": "Fuerza del filtro",
    "filterSharpnessLabel": "Nitidez del filtro",
    "filterTypeLabel": "Tipo de filtro",
    "partitionsLabel": "Particiones",
    "segmentsLabel": "Segmentos",
    "passLabel": "Pasadas",
    "exactLabel": "Exacto",
    "useSharpYuvLabel": "YUV nítido",
    "optionDefault": "Predeterminado",
    "optionOn": "Activado",
    "optionOff": "Desactivado"
  },
  "fr": {
    "targetSizeLabel": "Taille cible (KB)",
    "targetPsnrLabel": "PSNR cible",
    "nearLosslessLabel": "Presque sans perte",
    "alphaQualityLabel": "Qualité alpha",
    "snsStrengthLabel": "Force SNS",
    "filterStrengthLabel": "Force du filtre",
    "filterSharpnessLabel": "Netteté du filtre",
    "filterTypeLabel": "Type de filtre",
    "partitionsLabel": "Partitions",
    "segmentsLabel": "Segments",
    "passLabel": "Passes",
    "exactLabel": "Exact",
    "useSharpYuvLabel": "YUV net",
    "optionDefault": "Par défaut",
    "optionOn": "Activé",
    "optionOff": "Désactivé"
  },
  "de": {
    "targetSizeLabel": "Zielgröße (KB)",
    "targetPsnrLabel": "Ziel-PSNR",
    "nearLosslessLabel": "Nahezu verlustfrei",
    "alphaQualityLabel": "Alpha-Qualität",
    "snsStrengthLabel": "SNS-Stärke",
    "filterStrengthLabel": "Filterstärke",
    "filterSharpnessLabel": "Filter-Schärfe",
    "filterTypeLabel": "Filtertyp",
    "partitionsLabel": "Partitionen",
    "segmentsLabel": "Segmente",
    "passLabel": "Durchläufe",
    "exactLabel": "Exakt",
    "useSharpYuvLabel": "Scharfes YUV",
    "optionDefault": "Standard",
    "optionOn": "An",
    "optionOff": "Aus"
  },
  "it": {
    "targetSizeLabel": "Dimensione obiettivo (KB)",
    "targetPsnrLabel": "PSNR obiettivo",
    "nearLosslessLabel": "Quasi lossless",
    "alphaQualityLabel": "Qualità alpha",
    "snsStrengthLabel": "Intensità SNS",
    "filterStrengthLabel": "Intensità filtro",
    "filterSharpnessLabel": "Nitidezza filtro",
    "filterTypeLabel": "Tipo filtro",
    "partitionsLabel": "Partizioni",
    "segmentsLabel": "Segmenti",
    "passLabel": "Passaggi",
    "exactLabel": "Esatto",
    "useSharpYuvLabel": "YUV nitido",
    "optionDefault": "Predefinito",
    "optionOn": "Attivo",
    "optionOff": "Disattivo"
  },
  "ja": {
    "targetSizeLabel": "目標サイズ (KB)",
    "targetPsnrLabel": "目標 PSNR",
    "nearLosslessLabel": "準ロスレス",
    "alphaQualityLabel": "アルファ品質",
    "snsStrengthLabel": "SNS 強度",
    "filterStrengthLabel": "フィルター強度",
    "filterSharpnessLabel": "フィルターシャープネス",
    "filterTypeLabel": "フィルター種類",
    "partitionsLabel": "パーティション",
    "segmentsLabel": "セグメント",
    "passLabel": "パス",
    "exactLabel": "厳密",
    "useSharpYuvLabel": "シャープ YUV",
    "optionDefault": "デフォルト",
    "optionOn": "オン",
    "optionOff": "オフ"
  },
  "ko": {
    "targetSizeLabel": "목표 크기 (KB)",
    "targetPsnrLabel": "목표 PSNR",
    "nearLosslessLabel": "준 무손실",
    "alphaQualityLabel": "알파 품질",
    "snsStrengthLabel": "SNS 강도",
    "filterStrengthLabel": "필터 강도",
    "filterSharpnessLabel": "필터 선명도",
    "filterTypeLabel": "필터 유형",
    "partitionsLabel": "파티션",
    "segmentsLabel": "세그먼트",
    "passLabel": "패스",
    "exactLabel": "정확",
    "useSharpYuvLabel": "선명 YUV",
    "optionDefault": "기본값",
    "optionOn": "켜기",
    "optionOff": "끄기"
  },
  "ru": {
    "targetSizeLabel": "Целевой размер (КБ)",
    "targetPsnrLabel": "Целевой PSNR",
    "nearLosslessLabel": "Почти без потерь",
    "alphaQualityLabel": "Качество альфа",
    "snsStrengthLabel": "Сила SNS",
    "filterStrengthLabel": "Сила фильтра",
    "filterSharpnessLabel": "Резкость фильтра",
    "filterTypeLabel": "Тип фильтра",
    "partitionsLabel": "Разделы",
    "segmentsLabel": "Сегменты",
    "passLabel": "Проходы",
    "exactLabel": "Точно",
    "useSharpYuvLabel": "Резкий YUV",
    "optionDefault": "По умолчанию",
    "optionOn": "Вкл",
    "optionOff": "Выкл"
  },
  "pt": {
    "targetSizeLabel": "Tamanho alvo (KB)",
    "targetPsnrLabel": "PSNR alvo",
    "nearLosslessLabel": "Quase sem perdas",
    "alphaQualityLabel": "Qualidade alfa",
    "snsStrengthLabel": "Força SNS",
    "filterStrengthLabel": "Força do filtro",
    "filterSharpnessLabel": "Nitidez do filtro",
    "filterTypeLabel": "Tipo de filtro",
    "partitionsLabel": "Partições",
    "segmentsLabel": "Segmentos",
    "passLabel": "Passes",
    "exactLabel": "Exato",
    "useSharpYuvLabel": "YUV nítido",
    "optionDefault": "Padrão",
    "optionOn": "Ligado",
    "optionOff": "Desligado"
  },
  "ar": {
    "targetSizeLabel": "الحجم المستهدف (KB)",
    "targetPsnrLabel": "PSNR مستهدف",
    "nearLosslessLabel": "قريب من بدون فقدان",
    "alphaQualityLabel": "جودة ألفا",
    "snsStrengthLabel": "قوة SNS",
    "filterStrengthLabel": "قوة المرشح",
    "filterSharpnessLabel": "حدة المرشح",
    "filterTypeLabel": "نوع المرشح",
    "partitionsLabel": "الأقسام",
    "segmentsLabel": "المقاطع",
    "passLabel": "عدد التمريرات",
    "exactLabel": "دقيق",
    "useSharpYuvLabel": "YUV حاد",
    "optionDefault": "افتراضي",
    "optionOn": "تشغيل",
    "optionOff": "إيقاف"
  },
  "hi": {
    "targetSizeLabel": "लक्ष्य आकार (KB)",
    "targetPsnrLabel": "लक्ष्य PSNR",
    "nearLosslessLabel": "लगभग लॉसलेस",
    "alphaQualityLabel": "अल्फ़ा गुणवत्ता",
    "snsStrengthLabel": "SNS शक्ति",
    "filterStrengthLabel": "फ़िल्टर शक्ति",
    "filterSharpnessLabel": "फ़िल्टर तीक्ष्णता",
    "filterTypeLabel": "फ़िल्टर प्रकार",
    "partitionsLabel": "पार्टिशन",
    "segmentsLabel": "सेगमेंट",
    "passLabel": "पास",
    "exactLabel": "सटीक",
    "useSharpYuvLabel": "शार्प YUV",
    "optionDefault": "डिफ़ॉल्ट",
    "optionOn": "चालू",
    "optionOff": "बंद"
  },
  "tr": {
    "targetSizeLabel": "Hedef boyut (KB)",
    "targetPsnrLabel": "Hedef PSNR",
    "nearLosslessLabel": "Neredeyse kayıpsız",
    "alphaQualityLabel": "Alfa kalitesi",
    "snsStrengthLabel": "SNS gücü",
    "filterStrengthLabel": "Filtre gücü",
    "filterSharpnessLabel": "Filtre keskinliği",
    "filterTypeLabel": "Filtre türü",
    "partitionsLabel": "Bölümler",
    "segmentsLabel": "Segmentler",
    "passLabel": "Geçişler",
    "exactLabel": "Kesin",
    "useSharpYuvLabel": "Keskin YUV",
    "optionDefault": "Varsayılan",
    "optionOn": "Açık",
    "optionOff": "Kapalı"
  },
  "nl": {
    "targetSizeLabel": "Doelgrootte (KB)",
    "targetPsnrLabel": "Doel-PSNR",
    "nearLosslessLabel": "Bijna verliesvrij",
    "alphaQualityLabel": "Alfa-kwaliteit",
    "snsStrengthLabel": "SNS-sterkte",
    "filterStrengthLabel": "Filtersterkte",
    "filterSharpnessLabel": "Filterscherpte",
    "filterTypeLabel": "Filtertype",
    "partitionsLabel": "Partities",
    "segmentsLabel": "Segmenten",
    "passLabel": "Passes",
    "exactLabel": "Exact",
    "useSharpYuvLabel": "Scherpe YUV",
    "optionDefault": "Standaard",
    "optionOn": "Aan",
    "optionOff": "Uit"
  },
  "sv": {
    "targetSizeLabel": "Målstorlek (KB)",
    "targetPsnrLabel": "Mål-PSNR",
    "nearLosslessLabel": "Nästan förlustfri",
    "alphaQualityLabel": "Alfa-kvalitet",
    "snsStrengthLabel": "SNS-styrka",
    "filterStrengthLabel": "Filterstyrka",
    "filterSharpnessLabel": "Filterskärpa",
    "filterTypeLabel": "Filtertyp",
    "partitionsLabel": "Partitioner",
    "segmentsLabel": "Segment",
    "passLabel": "Pass",
    "exactLabel": "Exakt",
    "useSharpYuvLabel": "Skärpt YUV",
    "optionDefault": "Standard",
    "optionOn": "På",
    "optionOff": "Av"
  },
  "pl": {
    "targetSizeLabel": "Rozmiar docelowy (KB)",
    "targetPsnrLabel": "Docelowy PSNR",
    "nearLosslessLabel": "Prawie bezstratny",
    "alphaQualityLabel": "Jakość alfa",
    "snsStrengthLabel": "Siła SNS",
    "filterStrengthLabel": "Siła filtra",
    "filterSharpnessLabel": "Ostrość filtra",
    "filterTypeLabel": "Typ filtra",
    "partitionsLabel": "Partycje",
    "segmentsLabel": "Segmenty",
    "passLabel": "Przebiegi",
    "exactLabel": "Dokładny",
    "useSharpYuvLabel": "Ostry YUV",
    "optionDefault": "Domyślny",
    "optionOn": "Włącz",
    "optionOff": "Wyłącz"
  },
  "vi": {
    "targetSizeLabel": "Kích thước mục tiêu (KB)",
    "targetPsnrLabel": "PSNR mục tiêu",
    "nearLosslessLabel": "Gần như không mất dữ liệu",
    "alphaQualityLabel": "Chất lượng alpha",
    "snsStrengthLabel": "Cường độ SNS",
    "filterStrengthLabel": "Cường độ bộ lọc",
    "filterSharpnessLabel": "Độ sắc nét bộ lọc",
    "filterTypeLabel": "Loại bộ lọc",
    "partitionsLabel": "Phân vùng",
    "segmentsLabel": "Đoạn",
    "passLabel": "Lượt",
    "exactLabel": "Chính xác",
    "useSharpYuvLabel": "YUV sắc nét",
    "optionDefault": "Mặc định",
    "optionOn": "Bật",
    "optionOff": "Tắt"
  },
  "th": {
    "targetSizeLabel": "ขนาดเป้าหมาย (KB)",
    "targetPsnrLabel": "PSNR เป้าหมาย",
    "nearLosslessLabel": "เกือบไม่สูญเสีย",
    "alphaQualityLabel": "คุณภาพอัลฟา",
    "snsStrengthLabel": "ความแรง SNS",
    "filterStrengthLabel": "ความแรงฟิลเตอร์",
    "filterSharpnessLabel": "ความคมฟิลเตอร์",
    "filterTypeLabel": "ชนิดฟิลเตอร์",
    "partitionsLabel": "พาร์ทิชัน",
    "segmentsLabel": "เซ็กเมนต์",
    "passLabel": "จำนวนรอบ",
    "exactLabel": "แม่นยำ",
    "useSharpYuvLabel": "YUV คมชัด",
    "optionDefault": "ค่าเริ่มต้น",
    "optionOn": "เปิด",
    "optionOff": "ปิด"
  },
  "id": {
    "targetSizeLabel": "Ukuran target (KB)",
    "targetPsnrLabel": "PSNR target",
    "nearLosslessLabel": "Hampir tanpa kehilangan",
    "alphaQualityLabel": "Kualitas alfa",
    "snsStrengthLabel": "Kekuatan SNS",
    "filterStrengthLabel": "Kekuatan filter",
    "filterSharpnessLabel": "Ketajaman filter",
    "filterTypeLabel": "Jenis filter",
    "partitionsLabel": "Partisi",
    "segmentsLabel": "Segmen",
    "passLabel": "Putaran",
    "exactLabel": "Tepat",
    "useSharpYuvLabel": "YUV tajam",
    "optionDefault": "Default",
    "optionOn": "Aktif",
    "optionOff": "Nonaktif"
  },
  "he": {
    "targetSizeLabel": "גודל יעד (KB)",
    "targetPsnrLabel": "PSNR יעד",
    "nearLosslessLabel": "כמעט ללא אובדן",
    "alphaQualityLabel": "איכות אלפא",
    "snsStrengthLabel": "עוצמת SNS",
    "filterStrengthLabel": "עוצמת פילטר",
    "filterSharpnessLabel": "חדות פילטר",
    "filterTypeLabel": "סוג פילטר",
    "partitionsLabel": "מחיצות",
    "segmentsLabel": "מקטעים",
    "passLabel": "מעברים",
    "exactLabel": "מדויק",
    "useSharpYuvLabel": "YUV חד",
    "optionDefault": "ברירת מחדל",
    "optionOn": "מופעל",
    "optionOff": "כבוי"
  },
  "ms": {
    "targetSizeLabel": "Saiz sasaran (KB)",
    "targetPsnrLabel": "PSNR sasaran",
    "nearLosslessLabel": "Hampir tanpa kehilangan",
    "alphaQualityLabel": "Kualiti alfa",
    "snsStrengthLabel": "Kekuatan SNS",
    "filterStrengthLabel": "Kekuatan penapis",
    "filterSharpnessLabel": "Ketajaman penapis",
    "filterTypeLabel": "Jenis penapis",
    "partitionsLabel": "Partisi",
    "segmentsLabel": "Segmen",
    "passLabel": "Laluan",
    "exactLabel": "Tepat",
    "useSharpYuvLabel": "YUV tajam",
    "optionDefault": "Lalai",
    "optionOn": "Hidup",
    "optionOff": "Mati"
  },
  "no": {
    "targetSizeLabel": "Målstørrelse (KB)",
    "targetPsnrLabel": "Mål-PSNR",
    "nearLosslessLabel": "Nesten tapsfri",
    "alphaQualityLabel": "Alfakvalitet",
    "snsStrengthLabel": "SNS-styrke",
    "filterStrengthLabel": "Filterstyrke",
    "filterSharpnessLabel": "Filterskarphet",
    "filterTypeLabel": "Filtertype",
    "partitionsLabel": "Partisjoner",
    "segmentsLabel": "Segmenter",
    "passLabel": "Passeringer",
    "exactLabel": "Eksakt",
    "useSharpYuvLabel": "Skarp YUV",
    "optionDefault": "Standard",
    "optionOn": "På",
    "optionOff": "Av"
  }
}
</i18n>
