<template>
  <slot :labels="labels" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n({ useScope: 'local' })
const labels = computed(() => ({
  title: t('optionsTitle'),
  scaleLabel: t('scaleLabel'),
  scaleHint: t('scaleHint'),
  qualityLabel: t('qualityLabel'),
  qualityHint: t('qualityHint'),
  methodLabel: t('methodLabel'),
  methodHint: t('methodHint'),
  losslessLabel: t('losslessLabel'),
  advancedLabel: t('advancedLabel'),
  convertLabel: t('convert'),
  convertingLabel: t('converting'),
}))
</script>

<i18n lang="json">
{
  "en": {
    "optionsTitle": "Conversion Options",
    "scaleLabel": "Scale (%)",
    "scaleHint": "Resize all images by percentage.",
    "qualityLabel": "Quality",
    "qualityHint": "Higher values keep more detail but increase file size.",
    "methodLabel": "Compression effort",
    "methodHint": "0 = fastest, 6 = best compression.",
    "losslessLabel": "Lossless",
    "advancedLabel": "Advanced options",
    "convert": "Convert to WebP",
    "converting": "Converting..."
  },
  "zh": {
    "optionsTitle": "转换选项",
    "scaleLabel": "缩放比例 (%)",
    "scaleHint": "按比例调整所有图片大小。",
    "qualityLabel": "质量",
    "qualityHint": "数值越高细节越多，文件越大。",
    "methodLabel": "压缩强度",
    "methodHint": "0 最快，6 压缩最佳。",
    "losslessLabel": "无损",
    "advancedLabel": "高级选项",
    "convert": "转换为 WebP",
    "converting": "转换中..."
  },
  "zh-CN": {
    "optionsTitle": "转换选项",
    "scaleLabel": "缩放比例 (%)",
    "scaleHint": "按比例调整所有图片大小。",
    "qualityLabel": "质量",
    "qualityHint": "数值越高细节越多，文件越大。",
    "methodLabel": "压缩强度",
    "methodHint": "0 最快，6 压缩最佳。",
    "losslessLabel": "无损",
    "advancedLabel": "高级选项",
    "convert": "转换为 WebP",
    "converting": "转换中..."
  },
  "zh-TW": {
    "optionsTitle": "轉換選項",
    "scaleLabel": "縮放比例 (%)",
    "scaleHint": "依比例調整所有圖片大小。",
    "qualityLabel": "品質",
    "qualityHint": "數值越高細節越多，檔案越大。",
    "methodLabel": "壓縮強度",
    "methodHint": "0 最快，6 壓縮最佳。",
    "losslessLabel": "無損",
    "advancedLabel": "進階選項",
    "convert": "轉換為 WebP",
    "converting": "轉換中..."
  },
  "zh-HK": {
    "optionsTitle": "轉換選項",
    "scaleLabel": "縮放比例 (%)",
    "scaleHint": "依比例調整所有圖片大小。",
    "qualityLabel": "品質",
    "qualityHint": "數值越高細節越多，檔案越大。",
    "methodLabel": "壓縮強度",
    "methodHint": "0 最快，6 壓縮最佳。",
    "losslessLabel": "無損",
    "advancedLabel": "進階選項",
    "convert": "轉換為 WebP",
    "converting": "轉換中..."
  },
  "es": {
    "optionsTitle": "Opciones de conversión",
    "scaleLabel": "Escala (%)",
    "scaleHint": "Redimensiona todas las imágenes por porcentaje.",
    "qualityLabel": "Calidad",
    "qualityHint": "Valores más altos conservan más detalle pero aumentan el tamaño.",
    "methodLabel": "Esfuerzo de compresión",
    "methodHint": "0 = más rápido, 6 = mejor compresión.",
    "losslessLabel": "Sin pérdidas",
    "advancedLabel": "Opciones avanzadas",
    "convert": "Convertir a WebP",
    "converting": "Convirtiendo..."
  },
  "fr": {
    "optionsTitle": "Options de conversion",
    "scaleLabel": "Échelle (%)",
    "scaleHint": "Redimensionne toutes les images par pourcentage.",
    "qualityLabel": "Qualité",
    "qualityHint": "Des valeurs plus élevées conservent plus de détails mais augmentent la taille.",
    "methodLabel": "Effort de compression",
    "methodHint": "0 = le plus rapide, 6 = la meilleure compression.",
    "losslessLabel": "Sans perte",
    "advancedLabel": "Options avancées",
    "convert": "Convertir en WebP",
    "converting": "Conversion..."
  },
  "de": {
    "optionsTitle": "Konvertierungsoptionen",
    "scaleLabel": "Skalierung (%)",
    "scaleHint": "Alle Bilder prozentual skalieren.",
    "qualityLabel": "Qualität",
    "qualityHint": "Höhere Werte behalten mehr Details, erhöhen aber die Dateigröße.",
    "methodLabel": "Kompressionsaufwand",
    "methodHint": "0 = am schnellsten, 6 = beste Kompression.",
    "losslessLabel": "Verlustfrei",
    "advancedLabel": "Erweiterte Optionen",
    "convert": "In WebP konvertieren",
    "converting": "Konvertieren..."
  },
  "it": {
    "optionsTitle": "Opzioni di conversione",
    "scaleLabel": "Scala (%)",
    "scaleHint": "Ridimensiona tutte le immagini in percentuale.",
    "qualityLabel": "Qualità",
    "qualityHint": "Valori più alti mantengono più dettagli ma aumentano la dimensione.",
    "methodLabel": "Sforzo di compressione",
    "methodHint": "0 = più veloce, 6 = migliore compressione.",
    "losslessLabel": "Senza perdita",
    "advancedLabel": "Opzioni avanzate",
    "convert": "Converti in WebP",
    "converting": "Conversione..."
  },
  "ja": {
    "optionsTitle": "変換オプション",
    "scaleLabel": "倍率 (%)",
    "scaleHint": "すべての画像を割合でリサイズします。",
    "qualityLabel": "品質",
    "qualityHint": "数値が高いほど詳細を保持しますがサイズが大きくなります。",
    "methodLabel": "圧縮強度",
    "methodHint": "0 = 最速、6 = 最高圧縮。",
    "losslessLabel": "可逆",
    "advancedLabel": "詳細オプション",
    "convert": "WebP に変換",
    "converting": "変換中..."
  },
  "ko": {
    "optionsTitle": "변환 옵션",
    "scaleLabel": "배율 (%)",
    "scaleHint": "모든 이미지를 백분율로 크기 조정합니다.",
    "qualityLabel": "품질",
    "qualityHint": "값이 높을수록 디테일을 유지하지만 파일이 커집니다.",
    "methodLabel": "압축 강도",
    "methodHint": "0 = 가장 빠름, 6 = 최고의 압축.",
    "losslessLabel": "무손실",
    "advancedLabel": "고급 옵션",
    "convert": "WebP로 변환",
    "converting": "변환 중..."
  },
  "ru": {
    "optionsTitle": "Параметры конвертации",
    "scaleLabel": "Масштаб (%)",
    "scaleHint": "Масштабируйте все изображения в процентах.",
    "qualityLabel": "Качество",
    "qualityHint": "Чем выше значение, тем больше деталей, но больше размер файла.",
    "methodLabel": "Интенсивность сжатия",
    "methodHint": "0 = быстрее всего, 6 = лучшее сжатие.",
    "losslessLabel": "Без потерь",
    "advancedLabel": "Расширенные параметры",
    "convert": "Конвертировать в WebP",
    "converting": "Конвертация..."
  },
  "pt": {
    "optionsTitle": "Opções de conversão",
    "scaleLabel": "Escala (%)",
    "scaleHint": "Redimensione todas as imagens por porcentagem.",
    "qualityLabel": "Qualidade",
    "qualityHint": "Valores mais altos preservam mais detalhes, mas aumentam o tamanho.",
    "methodLabel": "Esforço de compressão",
    "methodHint": "0 = mais rápido, 6 = melhor compressão.",
    "losslessLabel": "Sem perdas",
    "advancedLabel": "Opções avançadas",
    "convert": "Converter para WebP",
    "converting": "Convertendo..."
  },
  "ar": {
    "optionsTitle": "خيارات التحويل",
    "scaleLabel": "المقياس (%)",
    "scaleHint": "تغيير حجم جميع الصور بالنسبة المئوية.",
    "qualityLabel": "الجودة",
    "qualityHint": "القيم الأعلى تحتفظ بتفاصيل أكثر لكنها تزيد الحجم.",
    "methodLabel": "مستوى الضغط",
    "methodHint": "0 = الأسرع، 6 = أفضل ضغط.",
    "losslessLabel": "بدون فقدان",
    "advancedLabel": "خيارات متقدمة",
    "convert": "تحويل إلى WebP",
    "converting": "جارٍ التحويل..."
  },
  "hi": {
    "optionsTitle": "परिवर्तन विकल्प",
    "scaleLabel": "स्केल (%)",
    "scaleHint": "सभी इमेज को प्रतिशत के अनुसार रीसाइज़ करें।",
    "qualityLabel": "गुणवत्ता",
    "qualityHint": "ऊँचे मान अधिक विवरण रखते हैं लेकिन आकार बढ़ाते हैं।",
    "methodLabel": "कंप्रेशन स्तर",
    "methodHint": "0 = सबसे तेज़, 6 = सर्वोत्तम कंप्रेशन।",
    "losslessLabel": "लॉसलेस",
    "advancedLabel": "उन्नत विकल्प",
    "convert": "WebP में बदलें",
    "converting": "बदल रहा है..."
  },
  "tr": {
    "optionsTitle": "Dönüştürme seçenekleri",
    "scaleLabel": "Ölçek (%)",
    "scaleHint": "Tüm görselleri yüzdeye göre yeniden boyutlandırın.",
    "qualityLabel": "Kalite",
    "qualityHint": "Daha yüksek değerler daha fazla ayrıntı korur, ancak boyutu artırır.",
    "methodLabel": "Sıkıştırma düzeyi",
    "methodHint": "0 = en hızlı, 6 = en iyi sıkıştırma.",
    "losslessLabel": "Kayıpsız",
    "advancedLabel": "Gelişmiş seçenekler",
    "convert": "WebP'ye dönüştür",
    "converting": "Dönüştürülüyor..."
  },
  "nl": {
    "optionsTitle": "Conversie-opties",
    "scaleLabel": "Schaal (%)",
    "scaleHint": "Schaal alle afbeeldingen op basis van percentage.",
    "qualityLabel": "Kwaliteit",
    "qualityHint": "Hogere waarden behouden meer detail maar vergroten de bestandsgrootte.",
    "methodLabel": "Compressie-inspanning",
    "methodHint": "0 = snelst, 6 = beste compressie.",
    "losslessLabel": "Verliesvrij",
    "advancedLabel": "Geavanceerde opties",
    "convert": "Converteren naar WebP",
    "converting": "Converteren..."
  },
  "sv": {
    "optionsTitle": "Konverteringsalternativ",
    "scaleLabel": "Skala (%)",
    "scaleHint": "Ändra storlek på alla bilder i procent.",
    "qualityLabel": "Kvalitet",
    "qualityHint": "Högre värden behåller mer detalj men ökar filstorleken.",
    "methodLabel": "Komprimeringsinsats",
    "methodHint": "0 = snabbast, 6 = bästa komprimering.",
    "losslessLabel": "Förlustfri",
    "advancedLabel": "Avancerade alternativ",
    "convert": "Konvertera till WebP",
    "converting": "Konverterar..."
  },
  "pl": {
    "optionsTitle": "Opcje konwersji",
    "scaleLabel": "Skala (%)",
    "scaleHint": "Zmień rozmiar wszystkich obrazów procentowo.",
    "qualityLabel": "Jakość",
    "qualityHint": "Wyższe wartości zachowują więcej szczegółów, ale zwiększają rozmiar.",
    "methodLabel": "Wysiłek kompresji",
    "methodHint": "0 = najszybciej, 6 = najlepsza kompresja.",
    "losslessLabel": "Bezstratnie",
    "advancedLabel": "Zaawansowane opcje",
    "convert": "Konwertuj do WebP",
    "converting": "Konwertowanie..."
  },
  "vi": {
    "optionsTitle": "Tùy chọn chuyển đổi",
    "scaleLabel": "Tỷ lệ (%)",
    "scaleHint": "Đổi kích thước tất cả ảnh theo phần trăm.",
    "qualityLabel": "Chất lượng",
    "qualityHint": "Giá trị cao hơn giữ nhiều chi tiết hơn nhưng tăng dung lượng.",
    "methodLabel": "Mức nén",
    "methodHint": "0 = nhanh nhất, 6 = nén tốt nhất.",
    "losslessLabel": "Không mất dữ liệu",
    "advancedLabel": "Tùy chọn nâng cao",
    "convert": "Chuyển sang WebP",
    "converting": "Đang chuyển đổi..."
  },
  "th": {
    "optionsTitle": "ตัวเลือกการแปลง",
    "scaleLabel": "สเกล (%)",
    "scaleHint": "ปรับขนาดรูปทั้งหมดตามเปอร์เซ็นต์",
    "qualityLabel": "คุณภาพ",
    "qualityHint": "ค่าสูงขึ้นเก็บรายละเอียดมากขึ้นแต่ไฟล์ใหญ่ขึ้น",
    "methodLabel": "ระดับการบีบอัด",
    "methodHint": "0 = เร็วที่สุด, 6 = บีบอัดดีที่สุด",
    "losslessLabel": "ไม่สูญเสีย",
    "advancedLabel": "ตัวเลือกขั้นสูง",
    "convert": "แปลงเป็น WebP",
    "converting": "กำลังแปลง..."
  },
  "id": {
    "optionsTitle": "Opsi konversi",
    "scaleLabel": "Skala (%)",
    "scaleHint": "Ubah ukuran semua gambar berdasarkan persentase.",
    "qualityLabel": "Kualitas",
    "qualityHint": "Nilai lebih tinggi mempertahankan detail lebih banyak tetapi ukuran bertambah.",
    "methodLabel": "Tingkat kompresi",
    "methodHint": "0 = tercepat, 6 = kompresi terbaik.",
    "losslessLabel": "Tanpa kehilangan",
    "advancedLabel": "Opsi lanjutan",
    "convert": "Konversi ke WebP",
    "converting": "Mengonversi..."
  },
  "he": {
    "optionsTitle": "אפשרויות המרה",
    "scaleLabel": "קנה מידה (%)",
    "scaleHint": "שנה את גודל כל התמונות לפי אחוז.",
    "qualityLabel": "איכות",
    "qualityHint": "ערכים גבוהים שומרים על יותר פרטים אך מגדילים את הקובץ.",
    "methodLabel": "מאמץ דחיסה",
    "methodHint": "0 = המהיר ביותר, 6 = הדחיסה הטובה ביותר.",
    "losslessLabel": "ללא אובדן",
    "advancedLabel": "אפשרויות מתקדמות",
    "convert": "המר ל-WebP",
    "converting": "ממיר..."
  },
  "ms": {
    "optionsTitle": "Pilihan penukaran",
    "scaleLabel": "Skala (%)",
    "scaleHint": "Ubah saiz semua imej mengikut peratusan.",
    "qualityLabel": "Kualiti",
    "qualityHint": "Nilai lebih tinggi mengekalkan lebih banyak butiran tetapi saiz bertambah.",
    "methodLabel": "Usaha pemampatan",
    "methodHint": "0 = terpantas, 6 = pemampatan terbaik.",
    "losslessLabel": "Tanpa kehilangan",
    "advancedLabel": "Pilihan lanjutan",
    "convert": "Tukar ke WebP",
    "converting": "Menukar..."
  },
  "no": {
    "optionsTitle": "Konverteringsvalg",
    "scaleLabel": "Skala (%)",
    "scaleHint": "Endre størrelse på alle bilder i prosent.",
    "qualityLabel": "Kvalitet",
    "qualityHint": "Høyere verdier beholder mer detaljer, men øker filstørrelsen.",
    "methodLabel": "Kompresjonsnivå",
    "methodHint": "0 = raskest, 6 = best komprimering.",
    "losslessLabel": "Tapsfri",
    "advancedLabel": "Avanserte alternativer",
    "convert": "Konverter til WebP",
    "converting": "Konverterer..."
  }
}
</i18n>
