<template>
  <DescriptionMarkdown
    :title="t('what-is-sha512-224')"
    :description="t('what-is-sha512-224-description-markdown')"
  />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "zh": {
    "what-is-sha512-224": "什么是 SHA-512/224（FIPS 180-4）？",
    "what-is-sha512-224-description-markdown": "SHA-512/224（FIPS 180-4）是 SHA-2 家族的一种加密散列函数，输出 224 位（28 字节）的摘要，通常表示为 56 个字符的十六进制字符串。它基于 SHA-512，使用不同的初始值并截断输出，在保留 SHA-512 内部结构的同时提供更短的摘要。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **抗碰撞**：很难找到产生相同散列的两个不同输入\n\n**常见用途：**\n- 数字签名和证书\n- 完整性校验与校验和\n- HMAC 构造\n- 文件验证与数据流水线\n- 需要 224 位散列的协议"
  },
  "zh-CN": {
    "what-is-sha512-224": "什么是 SHA-512/224（FIPS 180-4）？",
    "what-is-sha512-224-description-markdown": "SHA-512/224（FIPS 180-4）是 SHA-2 家族的一种加密散列函数，输出 224 位（28 字节）的摘要，通常表示为 56 个字符的十六进制字符串。它基于 SHA-512，使用不同的初始值并截断输出，在保留 SHA-512 内部结构的同时提供更短的摘要。\n\n**主要特征：**\n- **确定性**：相同的输入总是产生相同的散列\n- **快速计算**：对于任何给定输入都能快速计算\n- **雪崩效应**：输入的微小变化会产生截然不同的输出\n- **不可逆**：从散列反推原始输入在计算上是不可行的\n- **抗碰撞**：很难找到产生相同散列的两个不同输入\n\n**常见用途：**\n- 数字签名和证书\n- 完整性校验与校验和\n- HMAC 构造\n- 文件验证与数据流水线\n- 需要 224 位散列的协议"
  },
  "zh-TW": {
    "what-is-sha512-224": "什麼是 SHA-512/224（FIPS 180-4）？",
    "what-is-sha512-224-description-markdown": "SHA-512/224（FIPS 180-4）是 SHA-2 家族的一種加密雜湊函數，輸出 224 位元（28 位元組）的摘要，通常表示為 56 個字元的十六進位字串。它基於 SHA-512，使用不同的初始值並截斷輸出，在保留 SHA-512 內部結構的同時提供更短的摘要。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n\n**常見用途：**\n- 數位簽章和憑證\n- 完整性校驗與檢查碼\n- HMAC 建構\n- 檔案驗證與資料流程\n- 需要 224 位元雜湊的協定"
  },
  "zh-HK": {
    "what-is-sha512-224": "什麼是 SHA-512/224（FIPS 180-4）？",
    "what-is-sha512-224-description-markdown": "SHA-512/224（FIPS 180-4）是 SHA-2 家族的一種加密雜湊函數，輸出 224 位元（28 位元組）的摘要，通常表示為 56 個字元的十六進位字串。它基於 SHA-512，使用不同的初始值並截斷輸出，在保留 SHA-512 內部結構的同時提供更短的摘要。\n\n**主要特徵：**\n- **確定性**：相同的輸入總是產生相同的雜湊\n- **快速計算**：對於任何給定輸入都能快速計算\n- **雪崩效應**：輸入的微小變化會產生截然不同的輸出\n- **不可逆**：從雜湊反推原始輸入在計算上是不可行的\n- **抗碰撞**：很難找到產生相同雜湊的兩個不同輸入\n\n**常見用途：**\n- 數碼簽署和證書\n- 完整性校驗與校驗和\n- HMAC 建構\n- 檔案驗證與資料流程\n- 需要 224 位元雜湊的協定"
  },
  "es": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "fr": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "de": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "it": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "ja": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "ko": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "ru": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "pt": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "ar": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "hi": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "tr": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "nl": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "sv": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "pl": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "vi": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "th": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "id": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "he": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "ms": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  },
  "no": {
    "what-is-sha512-224": "What is SHA-512/224 (FIPS 180-4)?",
    "what-is-sha512-224-description-markdown": "SHA-512/224 (FIPS 180-4) is a SHA-2 cryptographic hash function that outputs a 224-bit (28-byte) digest, typically rendered as a 56-character hexadecimal string. It is based on SHA-512 with different initial values and a truncated output, providing a shorter digest while keeping SHA-512's internal structure.\n\n**Key characteristics:**\n- **Deterministic**: The same input always produces the same hash\n- **Fast computation**: Quick to compute for any given input\n- **Avalanche effect**: Small changes in input produce drastically different outputs\n- **Irreversible**: Computationally infeasible to reverse the hash to find the original input\n- **Collision resistant**: Very difficult to find two different inputs that produce the same hash\n\n**Common uses:**\n- Digital signatures and certificates\n- Integrity checks and checksums\n- HMAC constructions\n- File verification and data pipelines\n- Protocols that require 224-bit hashes"
  }
}
</i18n>
