const MESSAGE_CATALOG_B = {
  nl: {
    configurationLabel: "Opties",
    configurationDescription:
      "Kies of de geplakte tekst als een Cookie-header of als Set-Cookie-headers moet worden geparseerd.",
    headerTypeLabel: "Header-type",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Invoer",
    inputDescription:
      "Plak hier ruwe HTTP-headertekst. Headervoorvoegsels zijn optioneel.",
    inputPlaceholder: "Plak Cookie- of Set-Cookie-headers hier...",
    outputLabel: "Geparseerde JSON",
    outputDescription:
      "Bekijk de gestructureerde cookiedata en kopieer of download daarna de JSON.",
    outputPlaceholder: "De geparseerde JSON verschijnt hier...",
    copyOutputLabel: "JSON kopiëren",
    downloadJsonLabel: "JSON downloaden",
    copiedLabel: "Gekopieerd",
    resetExampleLabel: "Voorbeeld resetten",
    noCookiesFoundLabel: "Geen cookies gevonden",
    invalidSegmentsLabel: "Ongeldige segmenten overgeslagen",
  },
  no: {
    configurationLabel: "Alternativer",
    configurationDescription:
      "Velg om den innlimte teksten skal tolkes som en Cookie-header eller som Set-Cookie-headere.",
    headerTypeLabel: "Header-type",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Inndata",
    inputDescription:
      "Lim inn rå HTTP-headertekst her. Header-prefikser er valgfrie.",
    inputPlaceholder: "Lim inn Cookie- eller Set-Cookie-headere her...",
    outputLabel: "Tolket JSON",
    outputDescription:
      "Gå gjennom de strukturerte cookiedataene og kopier eller last ned JSON etterpå.",
    outputPlaceholder: "Tolket JSON vises her...",
    copyOutputLabel: "Kopier JSON",
    downloadJsonLabel: "Last ned JSON",
    copiedLabel: "Kopiert",
    resetExampleLabel: "Tilbakestill eksempel",
    noCookiesFoundLabel: "Ingen cookies funnet",
    invalidSegmentsLabel: "Ugyldige segmenter ble hoppet over",
  },
  pl: {
    configurationLabel: "Opcje",
    configurationDescription:
      "Wybierz, czy wklejony tekst ma zostać sparsowany jako nagłówek Cookie czy jako nagłówki Set-Cookie.",
    headerTypeLabel: "Typ nagłówka",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Wejście",
    inputDescription:
      "Wklej tutaj surowy tekst nagłówków HTTP. Prefiksy nagłówków są opcjonalne.",
    inputPlaceholder: "Wklej tutaj nagłówki Cookie lub Set-Cookie...",
    outputLabel: "Sparsowany JSON",
    outputDescription:
      "Sprawdź uporządkowane dane ciasteczek, a następnie skopiuj lub pobierz JSON.",
    outputPlaceholder: "Sparsowany JSON pojawi się tutaj...",
    copyOutputLabel: "Kopiuj JSON",
    downloadJsonLabel: "Pobierz JSON",
    copiedLabel: "Skopiowano",
    resetExampleLabel: "Resetuj przykład",
    noCookiesFoundLabel: "Nie znaleziono ciasteczek",
    invalidSegmentsLabel: "Pominięto nieprawidłowe segmenty",
  },
  pt: {
    configurationLabel: "Opções",
    configurationDescription:
      "Escolha se o texto colado deve ser analisado como um cabeçalho Cookie ou como cabeçalhos Set-Cookie.",
    headerTypeLabel: "Tipo de cabeçalho",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Entrada",
    inputDescription:
      "Cole aqui o texto bruto de cabeçalhos HTTP. Os prefixos de cabeçalho são opcionais.",
    inputPlaceholder: "Cole os cabeçalhos Cookie ou Set-Cookie aqui...",
    outputLabel: "JSON analisado",
    outputDescription:
      "Revise os dados estruturados de cookies e depois copie ou baixe o JSON.",
    outputPlaceholder: "O JSON analisado aparecerá aqui...",
    copyOutputLabel: "Copiar JSON",
    downloadJsonLabel: "Baixar JSON",
    copiedLabel: "Copiado",
    resetExampleLabel: "Redefinir exemplo",
    noCookiesFoundLabel: "Nenhum cookie encontrado",
    invalidSegmentsLabel: "Segmentos inválidos ignorados",
  },
  ru: {
    configurationLabel: "Параметры",
    configurationDescription:
      "Выберите, нужно ли разбирать вставленный текст как заголовок Cookie или как заголовки Set-Cookie.",
    headerTypeLabel: "Тип заголовка",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Ввод",
    inputDescription:
      "Вставьте сюда сырой текст HTTP-заголовков. Префиксы заголовков необязательны.",
    inputPlaceholder: "Вставьте заголовки Cookie или Set-Cookie здесь...",
    outputLabel: "Разобранный JSON",
    outputDescription:
      "Проверьте структурированные данные cookie, затем скопируйте или скачайте JSON.",
    outputPlaceholder: "Разобранный JSON появится здесь...",
    copyOutputLabel: "Копировать JSON",
    downloadJsonLabel: "Скачать JSON",
    copiedLabel: "Скопировано",
    resetExampleLabel: "Сбросить пример",
    noCookiesFoundLabel: "Cookie не найдены",
    invalidSegmentsLabel: "Пропущены недопустимые сегменты",
  },
  sv: {
    configurationLabel: "Alternativ",
    configurationDescription:
      "Välj om den inklistrade texten ska tolkas som en Cookie-header eller som Set-Cookie-headers.",
    headerTypeLabel: "Header-typ",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Inmatning",
    inputDescription:
      "Klistra in rå HTTP-headertext här. Headerprefix är valfria.",
    inputPlaceholder: "Klistra in Cookie- eller Set-Cookie-headers här...",
    outputLabel: "Tolkad JSON",
    outputDescription:
      "Granska den strukturerade cookiedatan och kopiera eller ladda sedan ner JSON.",
    outputPlaceholder: "Tolkad JSON visas här...",
    copyOutputLabel: "Kopiera JSON",
    downloadJsonLabel: "Ladda ner JSON",
    copiedLabel: "Kopierad",
    resetExampleLabel: "Återställ exempel",
    noCookiesFoundLabel: "Inga cookies hittades",
    invalidSegmentsLabel: "Ogiltiga segment hoppades över",
  },
  th: {
    configurationLabel: "ตัวเลือก",
    configurationDescription:
      "เลือกว่าจะให้แยกข้อความที่วางมาเป็นส่วนหัว Cookie หรือเป็นส่วนหัว Set-Cookie",
    headerTypeLabel: "ประเภทส่วนหัว",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "อินพุต",
    inputDescription: "วางข้อความส่วนหัว HTTP แบบดิบที่นี่ โดยไม่จำเป็นต้องมีคำนำหน้าส่วนหัว",
    inputPlaceholder: "วางส่วนหัว Cookie หรือ Set-Cookie ที่นี่...",
    outputLabel: "JSON ที่แยกแล้ว",
    outputDescription: "ตรวจสอบข้อมูลคุกกี้ที่มีโครงสร้าง แล้วคัดลอกหรือดาวน์โหลด JSON",
    outputPlaceholder: "JSON ที่แยกแล้วจะแสดงที่นี่...",
    copyOutputLabel: "คัดลอก JSON",
    downloadJsonLabel: "ดาวน์โหลด JSON",
    copiedLabel: "คัดลอกแล้ว",
    resetExampleLabel: "รีเซ็ตตัวอย่าง",
    noCookiesFoundLabel: "ไม่พบคุกกี้",
    invalidSegmentsLabel: "ข้ามส่วนที่ไม่ถูกต้อง",
  },
  tr: {
    configurationLabel: "Seçenekler",
    configurationDescription:
      "Yapıştırılan metnin Cookie başlığı olarak mı yoksa Set-Cookie başlıkları olarak mı ayrıştırılacağını seçin.",
    headerTypeLabel: "Başlık Türü",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Girdi",
    inputDescription:
      "Ham HTTP başlık metnini buraya yapıştırın. Başlık önekleri isteğe bağlıdır.",
    inputPlaceholder:
      "Cookie veya Set-Cookie başlıklarını buraya yapıştırın...",
    outputLabel: "Ayrıştırılmış JSON",
    outputDescription:
      "Yapılandırılmış çerez verilerini gözden geçirin, ardından JSON'u kopyalayın veya indirin.",
    outputPlaceholder: "Ayrıştırılmış JSON burada görünecek...",
    copyOutputLabel: "JSON'u kopyala",
    downloadJsonLabel: "JSON indir",
    copiedLabel: "Kopyalandı",
    resetExampleLabel: "Örneği sıfırla",
    noCookiesFoundLabel: "Çerez bulunamadı",
    invalidSegmentsLabel: "Geçersiz bölümler atlandı",
  },
  vi: {
    configurationLabel: "Tùy chọn",
    configurationDescription:
      "Chọn xem văn bản đã dán cần được phân tích như header Cookie hay như các header Set-Cookie.",
    headerTypeLabel: "Loại header",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "Đầu vào",
    inputDescription:
      "Dán văn bản header HTTP thô vào đây. Tiền tố header là tùy chọn.",
    inputPlaceholder: "Dán header Cookie hoặc Set-Cookie vào đây...",
    outputLabel: "JSON đã phân tích",
    outputDescription:
      "Xem lại dữ liệu cookie có cấu trúc, sau đó sao chép hoặc tải xuống JSON.",
    outputPlaceholder: "JSON đã phân tích sẽ hiển thị ở đây...",
    copyOutputLabel: "Sao chép JSON",
    downloadJsonLabel: "Tải JSON",
    copiedLabel: "Đã sao chép",
    resetExampleLabel: "Đặt lại ví dụ",
    noCookiesFoundLabel: "Không tìm thấy cookie",
    invalidSegmentsLabel: "Đã bỏ qua các đoạn không hợp lệ",
  },
  "zh-CN": {
    configurationLabel: "选项",
    configurationDescription:
      "选择将粘贴的文本按 Cookie 标头还是按 Set-Cookie 标头进行解析。",
    headerTypeLabel: "头部类型",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "输入",
    inputDescription: "在此粘贴原始 HTTP 标头文本。标头前缀是可选的。",
    inputPlaceholder: "在此粘贴 Cookie 或 Set-Cookie 头...",
    outputLabel: "解析后的 JSON",
    outputDescription: "查看结构化的 Cookie 数据，然后复制或下载 JSON。",
    outputPlaceholder: "解析后的 JSON 将显示在这里...",
    copyOutputLabel: "复制 JSON",
    downloadJsonLabel: "下载 JSON",
    copiedLabel: "已复制",
    resetExampleLabel: "重置示例",
    noCookiesFoundLabel: "未找到 Cookie",
    invalidSegmentsLabel: "已跳过无效片段",
  },
  "zh-TW": {
    configurationLabel: "選項",
    configurationDescription:
      "選擇要將貼上的文字解析為 Cookie 標頭，還是解析為 Set-Cookie 標頭。",
    headerTypeLabel: "標頭類型",
    headerCookieLabel: "Cookie",
    headerSetCookieLabel: "Set-Cookie",
    inputLabel: "輸入",
    inputDescription: "在此貼上原始 HTTP 標頭文字。標頭前綴可省略。",
    inputPlaceholder: "在此貼上 Cookie 或 Set-Cookie 標頭...",
    outputLabel: "解析後的 JSON",
    outputDescription: "檢視結構化的 Cookie 資料，然後複製或下載 JSON。",
    outputPlaceholder: "解析後的 JSON 會顯示在這裡...",
    copyOutputLabel: "複製 JSON",
    downloadJsonLabel: "下載 JSON",
    copiedLabel: "已複製",
    resetExampleLabel: "重設範例",
    noCookiesFoundLabel: "找不到 Cookie",
    invalidSegmentsLabel: "已略過無效片段",
  },
} as const

export { MESSAGE_CATALOG_B }
