<template>
  <DescriptionMarkdown :title="t('title')" :description="t('description')" />
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { DescriptionMarkdown } from '@shared/ui/base'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "title": "What is an SSH Key?",
    "description": "**SSH (Secure Shell) keys** are cryptographic key pairs used for secure authentication when connecting to remote servers.\n\n### How SSH Keys Work\n\nAn SSH key pair consists of two keys:\n\n- **Public Key**: Stored on the server you want to access. Safe to share publicly.\n- **Private Key**: Stored on your local machine. Must be kept secret and secure.\n\nWhen you connect to a server, your SSH client uses the private key to prove your identity without sending a password over the network.\n\n### Key Types\n\n- **Ed25519**: Modern algorithm, recommended for most users. Faster, more secure, and produces smaller keys.\n- **RSA**: Traditional algorithm, widely compatible. Use 4096 bits for better security.\n\n### Usage\n\n1. Generate a key pair using this tool\n2. Copy the **public key** to your server's `{'~'}/.ssh/authorized_keys` file\n3. Store the **private key** in your `{'~'}/.ssh/` directory (e.g., `~/.ssh/id_ed25519`)\n4. Set proper permissions: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "zh": {
    "title": "什么是 SSH 密钥？",
    "description": "**SSH（安全外壳协议）密钥**是用于连接远程服务器时进行安全身份验证的加密密钥对。\n\n### SSH 密钥的工作原理\n\nSSH 密钥对由两个密钥组成：\n\n- **公钥**：存储在您要访问的服务器上。可以安全地公开分享。\n- **私钥**：存储在您的本地计算机上。必须保密和安全保存。\n\n当您连接到服务器时，SSH 客户端使用私钥来证明您的身份，而无需通过网络发送密码。\n\n### 密钥类型\n\n- **Ed25519**：现代算法，推荐大多数用户使用。更快、更安全，生成的密钥更小。\n- **RSA**：传统算法，兼容性广泛。建议使用 4096 位以获得更好的安全性。\n\n### 使用方法\n\n1. 使用此工具生成密钥对\n2. 将**公钥**复制到服务器的 `{'~'}/.ssh/authorized_keys` 文件中\n3. 将**私钥**存储在您的 `{'~'}/.ssh/` 目录中（例如 `~/.ssh/id_ed25519`）\n4. 设置正确的权限：`chmod 600 ~/.ssh/id_ed25519`"
  },
  "zh-CN": {
    "title": "什么是 SSH 密钥？",
    "description": "**SSH（安全外壳协议）密钥**是用于连接远程服务器时进行安全身份验证的加密密钥对。\n\n### SSH 密钥的工作原理\n\nSSH 密钥对由两个密钥组成：\n\n- **公钥**：存储在您要访问的服务器上。可以安全地公开分享。\n- **私钥**：存储在您的本地计算机上。必须保密和安全保存。\n\n当您连接到服务器时，SSH 客户端使用私钥来证明您的身份，而无需通过网络发送密码。\n\n### 密钥类型\n\n- **Ed25519**：现代算法，推荐大多数用户使用。更快、更安全，生成的密钥更小。\n- **RSA**：传统算法，兼容性广泛。建议使用 4096 位以获得更好的安全性。\n\n### 使用方法\n\n1. 使用此工具生成密钥对\n2. 将**公钥**复制到服务器的 `{'~'}/.ssh/authorized_keys` 文件中\n3. 将**私钥**存储在您的 `{'~'}/.ssh/` 目录中（例如 `~/.ssh/id_ed25519`）\n4. 设置正确的权限：`chmod 600 ~/.ssh/id_ed25519`"
  },
  "zh-TW": {
    "title": "什麼是 SSH 金鑰？",
    "description": "**SSH（安全外殼協議）金鑰**是用於連接遠端伺服器時進行安全身份驗證的加密金鑰對。\n\n### SSH 金鑰的工作原理\n\nSSH 金鑰對由兩個金鑰組成：\n\n- **公鑰**：儲存在您要存取的伺服器上。可以安全地公開分享。\n- **私鑰**：儲存在您的本機電腦上。必須保密和安全保存。\n\n當您連接到伺服器時，SSH 用戶端使用私鑰來證明您的身份，而無需通過網路發送密碼。\n\n### 金鑰類型\n\n- **Ed25519**：現代演算法，推薦大多數使用者使用。更快、更安全，產生的金鑰更小。\n- **RSA**：傳統演算法，相容性廣泛。建議使用 4096 位元以獲得更好的安全性。\n\n### 使用方法\n\n1. 使用此工具產生金鑰對\n2. 將**公鑰**複製到伺服器的 `{'~'}/.ssh/authorized_keys` 檔案中\n3. 將**私鑰**儲存在您的 `{'~'}/.ssh/` 目錄中（例如 `~/.ssh/id_ed25519`）\n4. 設定正確的權限：`chmod 600 ~/.ssh/id_ed25519`"
  },
  "zh-HK": {
    "title": "什麼是 SSH 密鑰？",
    "description": "**SSH（安全外殼協議）密鑰**是用於連接遠端伺服器時進行安全身份驗證的加密密鑰對。\n\n### SSH 密鑰的工作原理\n\nSSH 密鑰對由兩個密鑰組成：\n\n- **公鑰**：儲存在您要存取的伺服器上。可以安全地公開分享。\n- **私鑰**：儲存在您的本機電腦上。必須保密和安全保存。\n\n當您連接到伺服器時，SSH 用戶端使用私鑰來證明您的身份，而無需通過網路發送密碼。\n\n### 密鑰類型\n\n- **Ed25519**：現代演算法，推薦大多數用戶使用。更快、更安全，產生的密鑰更小。\n- **RSA**：傳統演算法，相容性廣泛。建議使用 4096 位元以獲得更好的安全性。\n\n### 使用方法\n\n1. 使用此工具產生密鑰對\n2. 將**公鑰**複製到伺服器的 `{'~'}/.ssh/authorized_keys` 檔案中\n3. 將**私鑰**儲存在您的 `{'~'}/.ssh/` 目錄中（例如 `~/.ssh/id_ed25519`）\n4. 設定正確的權限：`chmod 600 ~/.ssh/id_ed25519`"
  },
  "es": {
    "title": "¿Qué es una clave SSH?",
    "description": "**Las claves SSH (Secure Shell)** son pares de claves criptográficas utilizadas para la autenticación segura al conectarse a servidores remotos.\n\n### Cómo funcionan las claves SSH\n\nUn par de claves SSH consta de dos claves:\n\n- **Clave pública**: Se almacena en el servidor al que desea acceder. Es seguro compartirla públicamente.\n- **Clave privada**: Se almacena en su máquina local. Debe mantenerse secreta y segura.\n\nCuando se conecta a un servidor, su cliente SSH utiliza la clave privada para demostrar su identidad sin enviar una contraseña a través de la red.\n\n### Tipos de claves\n\n- **Ed25519**: Algoritmo moderno, recomendado para la mayoría de usuarios. Más rápido, más seguro y produce claves más pequeñas.\n- **RSA**: Algoritmo tradicional, ampliamente compatible. Use 4096 bits para mayor seguridad.\n\n### Uso\n\n1. Genere un par de claves usando esta herramienta\n2. Copie la **clave pública** al archivo `{'~'}/.ssh/authorized_keys` de su servidor\n3. Almacene la **clave privada** en su directorio `{'~'}/.ssh/` (ej. `~/.ssh/id_ed25519`)\n4. Establezca los permisos correctos: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "fr": {
    "title": "Qu'est-ce qu'une clé SSH ?",
    "description": "**Les clés SSH (Secure Shell)** sont des paires de clés cryptographiques utilisées pour l'authentification sécurisée lors de la connexion à des serveurs distants.\n\n### Comment fonctionnent les clés SSH\n\nUne paire de clés SSH se compose de deux clés :\n\n- **Clé publique** : Stockée sur le serveur auquel vous souhaitez accéder. Peut être partagée publiquement en toute sécurité.\n- **Clé privée** : Stockée sur votre machine locale. Doit être gardée secrète et sécurisée.\n\nLorsque vous vous connectez à un serveur, votre client SSH utilise la clé privée pour prouver votre identité sans envoyer de mot de passe sur le réseau.\n\n### Types de clés\n\n- **Ed25519** : Algorithme moderne, recommandé pour la plupart des utilisateurs. Plus rapide, plus sécurisé et produit des clés plus petites.\n- **RSA** : Algorithme traditionnel, largement compatible. Utilisez 4096 bits pour une meilleure sécurité.\n\n### Utilisation\n\n1. Générez une paire de clés avec cet outil\n2. Copiez la **clé publique** dans le fichier `{'~'}/.ssh/authorized_keys` de votre serveur\n3. Stockez la **clé privée** dans votre répertoire `{'~'}/.ssh/` (ex. `~/.ssh/id_ed25519`)\n4. Définissez les permissions correctes : `chmod 600 ~/.ssh/id_ed25519`"
  },
  "de": {
    "title": "Was ist ein SSH-Schlüssel?",
    "description": "**SSH (Secure Shell) Schlüssel** sind kryptografische Schlüsselpaare, die für die sichere Authentifizierung bei der Verbindung mit Remote-Servern verwendet werden.\n\n### Wie SSH-Schlüssel funktionieren\n\nEin SSH-Schlüsselpaar besteht aus zwei Schlüsseln:\n\n- **Öffentlicher Schlüssel**: Wird auf dem Server gespeichert, auf den Sie zugreifen möchten. Kann sicher öffentlich geteilt werden.\n- **Privater Schlüssel**: Wird auf Ihrem lokalen Computer gespeichert. Muss geheim und sicher aufbewahrt werden.\n\nWenn Sie sich mit einem Server verbinden, verwendet Ihr SSH-Client den privaten Schlüssel, um Ihre Identität zu beweisen, ohne ein Passwort über das Netzwerk zu senden.\n\n### Schlüsseltypen\n\n- **Ed25519**: Moderner Algorithmus, für die meisten Benutzer empfohlen. Schneller, sicherer und erzeugt kleinere Schlüssel.\n- **RSA**: Traditioneller Algorithmus, weitgehend kompatibel. Verwenden Sie 4096 Bits für bessere Sicherheit.\n\n### Verwendung\n\n1. Generieren Sie ein Schlüsselpaar mit diesem Tool\n2. Kopieren Sie den **öffentlichen Schlüssel** in die Datei `{'~'}/.ssh/authorized_keys` Ihres Servers\n3. Speichern Sie den **privaten Schlüssel** in Ihrem `{'~'}/.ssh/`-Verzeichnis (z.B. `~/.ssh/id_ed25519`)\n4. Setzen Sie die richtigen Berechtigungen: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "it": {
    "title": "Cos'è una chiave SSH?",
    "description": "**Le chiavi SSH (Secure Shell)** sono coppie di chiavi crittografiche utilizzate per l'autenticazione sicura quando ci si connette a server remoti.\n\n### Come funzionano le chiavi SSH\n\nUna coppia di chiavi SSH è composta da due chiavi:\n\n- **Chiave pubblica**: Memorizzata sul server a cui si desidera accedere. Può essere condivisa pubblicamente in sicurezza.\n- **Chiave privata**: Memorizzata sulla macchina locale. Deve essere mantenuta segreta e sicura.\n\nQuando ci si connette a un server, il client SSH utilizza la chiave privata per dimostrare la propria identità senza inviare una password attraverso la rete.\n\n### Tipi di chiavi\n\n- **Ed25519**: Algoritmo moderno, consigliato per la maggior parte degli utenti. Più veloce, più sicuro e produce chiavi più piccole.\n- **RSA**: Algoritmo tradizionale, ampiamente compatibile. Usa 4096 bit per una maggiore sicurezza.\n\n### Utilizzo\n\n1. Genera una coppia di chiavi usando questo strumento\n2. Copia la **chiave pubblica** nel file `{'~'}/.ssh/authorized_keys` del tuo server\n3. Memorizza la **chiave privata** nella directory `{'~'}/.ssh/` (es. `~/.ssh/id_ed25519`)\n4. Imposta i permessi corretti: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "ja": {
    "title": "SSH キーとは？",
    "description": "**SSH（セキュアシェル）キー**は、リモートサーバーに接続する際の安全な認証に使用される暗号鍵ペアです。\n\n### SSH キーの仕組み\n\nSSH キーペアは 2 つの鍵で構成されています：\n\n- **公開鍵**：アクセスしたいサーバーに保存します。公開しても安全です。\n- **秘密鍵**：ローカルマシンに保存します。秘密にして安全に保管する必要があります。\n\nサーバーに接続すると、SSH クライアントは秘密鍵を使用して、ネットワーク経由でパスワードを送信することなく身元を証明します。\n\n### キーの種類\n\n- **Ed25519**：モダンなアルゴリズム、ほとんどのユーザーに推奨。より高速で安全、小さいキーを生成します。\n- **RSA**：従来のアルゴリズム、広く互換性があります。より良いセキュリティのために 4096 ビットを使用してください。\n\n### 使用方法\n\n1. このツールでキーペアを生成します\n2. **公開鍵**をサーバーの `{'~'}/.ssh/authorized_keys` ファイルにコピーします\n3. **秘密鍵**を `{'~'}/.ssh/` ディレクトリに保存します（例：`~/.ssh/id_ed25519`）\n4. 適切な権限を設定します：`chmod 600 ~/.ssh/id_ed25519`"
  },
  "ko": {
    "title": "SSH 키란?",
    "description": "**SSH(Secure Shell) 키**는 원격 서버에 연결할 때 안전한 인증을 위해 사용되는 암호화 키 쌍입니다.\n\n### SSH 키 작동 방식\n\nSSH 키 쌍은 두 개의 키로 구성됩니다:\n\n- **공개 키**: 액세스하려는 서버에 저장됩니다. 공개적으로 공유해도 안전합니다.\n- **개인 키**: 로컬 컴퓨터에 저장됩니다. 비밀로 유지하고 안전하게 보관해야 합니다.\n\n서버에 연결하면 SSH 클라이언트가 개인 키를 사용하여 네트워크를 통해 비밀번호를 전송하지 않고 신원을 증명합니다.\n\n### 키 유형\n\n- **Ed25519**: 현대적인 알고리즘, 대부분의 사용자에게 권장. 더 빠르고 안전하며 더 작은 키를 생성합니다.\n- **RSA**: 전통적인 알고리즘, 널리 호환됩니다. 더 나은 보안을 위해 4096 비트를 사용하세요.\n\n### 사용 방법\n\n1. 이 도구를 사용하여 키 쌍 생성\n2. **공개 키**를 서버의 `{'~'}/.ssh/authorized_keys` 파일에 복사\n3. **개인 키**를 `{'~'}/.ssh/` 디렉토리에 저장 (예: `~/.ssh/id_ed25519`)\n4. 올바른 권한 설정: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "ru": {
    "title": "Что такое SSH-ключ?",
    "description": "**SSH (Secure Shell) ключи** — это криптографические пары ключей, используемые для безопасной аутентификации при подключении к удалённым серверам.\n\n### Как работают SSH-ключи\n\nПара SSH-ключей состоит из двух ключей:\n\n- **Открытый ключ**: Хранится на сервере, к которому вы хотите получить доступ. Безопасно делиться публично.\n- **Закрытый ключ**: Хранится на вашем локальном компьютере. Должен храниться в секрете и безопасности.\n\nПри подключении к серверу ваш SSH-клиент использует закрытый ключ для подтверждения вашей личности без отправки пароля по сети.\n\n### Типы ключей\n\n- **Ed25519**: Современный алгоритм, рекомендуется для большинства пользователей. Быстрее, безопаснее и создаёт меньшие ключи.\n- **RSA**: Традиционный алгоритм, широко совместимый. Используйте 4096 бит для лучшей безопасности.\n\n### Использование\n\n1. Сгенерируйте пару ключей с помощью этого инструмента\n2. Скопируйте **открытый ключ** в файл `{'~'}/.ssh/authorized_keys` на сервере\n3. Сохраните **закрытый ключ** в директории `{'~'}/.ssh/` (например, `~/.ssh/id_ed25519`)\n4. Установите правильные разрешения: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "pt": {
    "title": "O que é uma chave SSH?",
    "description": "**Chaves SSH (Secure Shell)** são pares de chaves criptográficas usadas para autenticação segura ao conectar-se a servidores remotos.\n\n### Como as chaves SSH funcionam\n\nUm par de chaves SSH consiste em duas chaves:\n\n- **Chave pública**: Armazenada no servidor que você deseja acessar. Seguro para compartilhar publicamente.\n- **Chave privada**: Armazenada na sua máquina local. Deve ser mantida em segredo e segura.\n\nQuando você se conecta a um servidor, seu cliente SSH usa a chave privada para provar sua identidade sem enviar uma senha pela rede.\n\n### Tipos de chaves\n\n- **Ed25519**: Algoritmo moderno, recomendado para a maioria dos usuários. Mais rápido, mais seguro e produz chaves menores.\n- **RSA**: Algoritmo tradicional, amplamente compatível. Use 4096 bits para maior segurança.\n\n### Uso\n\n1. Gere um par de chaves usando esta ferramenta\n2. Copie a **chave pública** para o arquivo `{'~'}/.ssh/authorized_keys` do seu servidor\n3. Armazene a **chave privada** no seu diretório `{'~'}/.ssh/` (ex. `~/.ssh/id_ed25519`)\n4. Defina as permissões corretas: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "ar": {
    "title": "ما هو مفتاح SSH؟",
    "description": "**مفاتيح SSH (Secure Shell)** هي أزواج مفاتيح تشفيرية تُستخدم للمصادقة الآمنة عند الاتصال بالخوادم البعيدة.\n\n### كيف تعمل مفاتيح SSH\n\nيتكون زوج مفاتيح SSH من مفتاحين:\n\n- **المفتاح العام**: يُخزَّن على الخادم الذي تريد الوصول إليه. آمن للمشاركة العلنية.\n- **المفتاح الخاص**: يُخزَّن على جهازك المحلي. يجب الحفاظ عليه سريًا وآمنًا.\n\nعند الاتصال بخادم، يستخدم عميل SSH المفتاح الخاص لإثبات هويتك دون إرسال كلمة مرور عبر الشبكة.\n\n### أنواع المفاتيح\n\n- **Ed25519**: خوارزمية حديثة، موصى بها لمعظم المستخدمين. أسرع وأكثر أمانًا وتنتج مفاتيح أصغر.\n- **RSA**: خوارزمية تقليدية، متوافقة على نطاق واسع. استخدم 4096 بت لأمان أفضل.\n\n### الاستخدام\n\n1. قم بإنشاء زوج مفاتيح باستخدام هذه الأداة\n2. انسخ **المفتاح العام** إلى ملف `{'~'}/.ssh/authorized_keys` على خادمك\n3. احفظ **المفتاح الخاص** في مجلد `{'~'}/.ssh/` (مثل `~/.ssh/id_ed25519`)\n4. اضبط الأذونات الصحيحة: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "hi": {
    "title": "SSH कुंजी क्या है?",
    "description": "**SSH (सिक्योर शेल) कुंजियाँ** क्रिप्टोग्राफिक कुंजी जोड़े हैं जिनका उपयोग रिमोट सर्वर से कनेक्ट होते समय सुरक्षित प्रमाणीकरण के लिए किया जाता है।\n\n### SSH कुंजियाँ कैसे काम करती हैं\n\nएक SSH कुंजी जोड़ी में दो कुंजियाँ होती हैं:\n\n- **सार्वजनिक कुंजी**: उस सर्वर पर संग्रहीत जिसे आप एक्सेस करना चाहते हैं। सार्वजनिक रूप से साझा करना सुरक्षित है।\n- **निजी कुंजी**: आपकी स्थानीय मशीन पर संग्रहीत। इसे गुप्त और सुरक्षित रखना चाहिए।\n\nजब आप किसी सर्वर से कनेक्ट होते हैं, तो आपका SSH क्लाइंट नेटवर्क पर पासवर्ड भेजे बिना आपकी पहचान साबित करने के लिए निजी कुंजी का उपयोग करता है।\n\n### कुंजी प्रकार\n\n- **Ed25519**: आधुनिक एल्गोरिथम, अधिकांश उपयोगकर्ताओं के लिए अनुशंसित। तेज़, अधिक सुरक्षित और छोटी कुंजियाँ उत्पन्न करता है।\n- **RSA**: पारंपरिक एल्गोरिथम, व्यापक रूप से संगत। बेहतर सुरक्षा के लिए 4096 बिट्स का उपयोग करें।\n\n### उपयोग\n\n1. इस टूल का उपयोग करके एक कुंजी जोड़ी उत्पन्न करें\n2. **सार्वजनिक कुंजी** को अपने सर्वर की `{'~'}/.ssh/authorized_keys` फ़ाइल में कॉपी करें\n3. **निजी कुंजी** को अपनी `{'~'}/.ssh/` डायरेक्टरी में स्टोर करें (उदा. `~/.ssh/id_ed25519`)\n4. उचित अनुमतियाँ सेट करें: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "tr": {
    "title": "SSH Anahtarı Nedir?",
    "description": "**SSH (Secure Shell) anahtarları**, uzak sunuculara bağlanırken güvenli kimlik doğrulama için kullanılan kriptografik anahtar çiftleridir.\n\n### SSH Anahtarları Nasıl Çalışır\n\nBir SSH anahtar çifti iki anahtardan oluşur:\n\n- **Genel Anahtar**: Erişmek istediğiniz sunucuda saklanır. Herkesle paylaşılması güvenlidir.\n- **Özel Anahtar**: Yerel makinenizde saklanır. Gizli ve güvenli tutulmalıdır.\n\nBir sunucuya bağlandığınızda, SSH istemciniz ağ üzerinden şifre göndermeden kimliğinizi kanıtlamak için özel anahtarı kullanır.\n\n### Anahtar Türleri\n\n- **Ed25519**: Modern algoritma, çoğu kullanıcı için önerilir. Daha hızlı, daha güvenli ve daha küçük anahtarlar üretir.\n- **RSA**: Geleneksel algoritma, geniş uyumluluk. Daha iyi güvenlik için 4096 bit kullanın.\n\n### Kullanım\n\n1. Bu araçla bir anahtar çifti oluşturun\n2. **Genel anahtarı** sunucunuzun `{'~'}/.ssh/authorized_keys` dosyasına kopyalayın\n3. **Özel anahtarı** `{'~'}/.ssh/` dizininizde saklayın (ör. `~/.ssh/id_ed25519`)\n4. Doğru izinleri ayarlayın: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "nl": {
    "title": "Wat is een SSH-sleutel?",
    "description": "**SSH (Secure Shell) sleutels** zijn cryptografische sleutelparen die worden gebruikt voor veilige authenticatie bij het verbinden met externe servers.\n\n### Hoe SSH-sleutels werken\n\nEen SSH-sleutelpaar bestaat uit twee sleutels:\n\n- **Publieke sleutel**: Opgeslagen op de server waartoe u toegang wilt. Veilig om publiekelijk te delen.\n- **Privésleutel**: Opgeslagen op uw lokale machine. Moet geheim en veilig worden gehouden.\n\nWanneer u verbinding maakt met een server, gebruikt uw SSH-client de privésleutel om uw identiteit te bewijzen zonder een wachtwoord over het netwerk te verzenden.\n\n### Sleuteltypes\n\n- **Ed25519**: Modern algoritme, aanbevolen voor de meeste gebruikers. Sneller, veiliger en produceert kleinere sleutels.\n- **RSA**: Traditioneel algoritme, breed compatibel. Gebruik 4096 bits voor betere beveiliging.\n\n### Gebruik\n\n1. Genereer een sleutelpaar met deze tool\n2. Kopieer de **publieke sleutel** naar het `{'~'}/.ssh/authorized_keys` bestand van uw server\n3. Sla de **privésleutel** op in uw `{'~'}/.ssh/` map (bijv. `~/.ssh/id_ed25519`)\n4. Stel de juiste rechten in: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "sv": {
    "title": "Vad är en SSH-nyckel?",
    "description": "**SSH (Secure Shell) nycklar** är kryptografiska nyckelpar som används för säker autentisering vid anslutning till fjärrservrar.\n\n### Hur SSH-nycklar fungerar\n\nEtt SSH-nyckelpar består av två nycklar:\n\n- **Publik nyckel**: Lagras på servern du vill komma åt. Säker att dela offentligt.\n- **Privat nyckel**: Lagras på din lokala dator. Måste hållas hemlig och säker.\n\nNär du ansluter till en server använder din SSH-klient den privata nyckeln för att bevisa din identitet utan att skicka ett lösenord över nätverket.\n\n### Nyckeltyper\n\n- **Ed25519**: Modern algoritm, rekommenderas för de flesta användare. Snabbare, säkrare och producerar mindre nycklar.\n- **RSA**: Traditionell algoritm, brett kompatibel. Använd 4096 bitar för bättre säkerhet.\n\n### Användning\n\n1. Generera ett nyckelpar med detta verktyg\n2. Kopiera den **publika nyckeln** till din servers `{'~'}/.ssh/authorized_keys` fil\n3. Lagra den **privata nyckeln** i din `{'~'}/.ssh/` katalog (t.ex. `~/.ssh/id_ed25519`)\n4. Ställ in rätt behörigheter: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "pl": {
    "title": "Co to jest klucz SSH?",
    "description": "**Klucze SSH (Secure Shell)** to pary kluczy kryptograficznych używane do bezpiecznego uwierzytelniania podczas łączenia się z serwerami zdalnymi.\n\n### Jak działają klucze SSH\n\nPara kluczy SSH składa się z dwóch kluczy:\n\n- **Klucz publiczny**: Przechowywany na serwerze, do którego chcesz uzyskać dostęp. Bezpieczny do publicznego udostępniania.\n- **Klucz prywatny**: Przechowywany na Twojej lokalnej maszynie. Musi być trzymany w tajemnicy i bezpiecznie.\n\nPodczas łączenia się z serwerem, Twój klient SSH używa klucza prywatnego do potwierdzenia Twojej tożsamości bez wysyłania hasła przez sieć.\n\n### Typy kluczy\n\n- **Ed25519**: Nowoczesny algorytm, zalecany dla większości użytkowników. Szybszy, bezpieczniejszy i generuje mniejsze klucze.\n- **RSA**: Tradycyjny algorytm, szeroko kompatybilny. Użyj 4096 bitów dla lepszego bezpieczeństwa.\n\n### Użycie\n\n1. Wygeneruj parę kluczy za pomocą tego narzędzia\n2. Skopiuj **klucz publiczny** do pliku `{'~'}/.ssh/authorized_keys` na serwerze\n3. Przechowuj **klucz prywatny** w katalogu `{'~'}/.ssh/` (np. `~/.ssh/id_ed25519`)\n4. Ustaw odpowiednie uprawnienia: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "vi": {
    "title": "Khóa SSH là gì?",
    "description": "**Khóa SSH (Secure Shell)** là các cặp khóa mật mã được sử dụng để xác thực an toàn khi kết nối với máy chủ từ xa.\n\n### Cách khóa SSH hoạt động\n\nMột cặp khóa SSH bao gồm hai khóa:\n\n- **Khóa công khai**: Được lưu trữ trên máy chủ bạn muốn truy cập. An toàn để chia sẻ công khai.\n- **Khóa riêng tư**: Được lưu trữ trên máy tính cá nhân của bạn. Phải được giữ bí mật và an toàn.\n\nKhi bạn kết nối với máy chủ, SSH client sử dụng khóa riêng tư để chứng minh danh tính của bạn mà không cần gửi mật khẩu qua mạng.\n\n### Loại khóa\n\n- **Ed25519**: Thuật toán hiện đại, được khuyến nghị cho hầu hết người dùng. Nhanh hơn, an toàn hơn và tạo ra khóa nhỏ hơn.\n- **RSA**: Thuật toán truyền thống, tương thích rộng rãi. Sử dụng 4096 bit để bảo mật tốt hơn.\n\n### Sử dụng\n\n1. Tạo cặp khóa bằng công cụ này\n2. Sao chép **khóa công khai** vào tệp `{'~'}/.ssh/authorized_keys` trên máy chủ của bạn\n3. Lưu trữ **khóa riêng tư** trong thư mục `{'~'}/.ssh/` (ví dụ: `~/.ssh/id_ed25519`)\n4. Đặt quyền đúng: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "th": {
    "title": "คีย์ SSH คืออะไร?",
    "description": "**คีย์ SSH (Secure Shell)** คือคู่คีย์เข้ารหัสที่ใช้สำหรับการยืนยันตัวตนอย่างปลอดภัยเมื่อเชื่อมต่อกับเซิร์ฟเวอร์ระยะไกล\n\n### คีย์ SSH ทำงานอย่างไร\n\nคู่คีย์ SSH ประกอบด้วยสองคีย์:\n\n- **คีย์สาธารณะ**: เก็บไว้บนเซิร์ฟเวอร์ที่คุณต้องการเข้าถึง ปลอดภัยที่จะแชร์สาธารณะ\n- **คีย์ส่วนตัว**: เก็บไว้บนเครื่องคอมพิวเตอร์ของคุณ ต้องเก็บเป็นความลับและปลอดภัย\n\nเมื่อคุณเชื่อมต่อกับเซิร์ฟเวอร์ SSH client ใช้คีย์ส่วนตัวเพื่อพิสูจน์ตัวตนของคุณโดยไม่ต้องส่งรหัสผ่านผ่านเครือข่าย\n\n### ประเภทคีย์\n\n- **Ed25519**: อัลกอริทึมสมัยใหม่ แนะนำสำหรับผู้ใช้ส่วนใหญ่ เร็วกว่า ปลอดภัยกว่า และสร้างคีย์ขนาดเล็กกว่า\n- **RSA**: อัลกอริทึมดั้งเดิม เข้ากันได้กว้างขวาง ใช้ 4096 บิตเพื่อความปลอดภัยที่ดีขึ้น\n\n### การใช้งาน\n\n1. สร้างคู่คีย์โดยใช้เครื่องมือนี้\n2. คัดลอก**คีย์สาธารณะ**ไปยังไฟล์ `{'~'}/.ssh/authorized_keys` บนเซิร์ฟเวอร์ของคุณ\n3. เก็บ**คีย์ส่วนตัว**ในไดเรกทอรี `{'~'}/.ssh/` (เช่น `~/.ssh/id_ed25519`)\n4. ตั้งค่าสิทธิ์ที่ถูกต้อง: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "id": {
    "title": "Apa itu Kunci SSH?",
    "description": "**Kunci SSH (Secure Shell)** adalah pasangan kunci kriptografi yang digunakan untuk autentikasi aman saat menghubungkan ke server jarak jauh.\n\n### Cara Kerja Kunci SSH\n\nPasangan kunci SSH terdiri dari dua kunci:\n\n- **Kunci Publik**: Disimpan di server yang ingin Anda akses. Aman untuk dibagikan secara publik.\n- **Kunci Pribadi**: Disimpan di mesin lokal Anda. Harus dijaga kerahasiaannya dan aman.\n\nSaat Anda terhubung ke server, klien SSH Anda menggunakan kunci pribadi untuk membuktikan identitas Anda tanpa mengirim kata sandi melalui jaringan.\n\n### Jenis Kunci\n\n- **Ed25519**: Algoritma modern, direkomendasikan untuk sebagian besar pengguna. Lebih cepat, lebih aman, dan menghasilkan kunci yang lebih kecil.\n- **RSA**: Algoritma tradisional, kompatibel secara luas. Gunakan 4096 bit untuk keamanan yang lebih baik.\n\n### Penggunaan\n\n1. Buat pasangan kunci menggunakan alat ini\n2. Salin **kunci publik** ke file `{'~'}/.ssh/authorized_keys` di server Anda\n3. Simpan **kunci pribadi** di direktori `{'~'}/.ssh/` Anda (mis. `~/.ssh/id_ed25519`)\n4. Atur izin yang benar: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "he": {
    "title": "מהו מפתח SSH?",
    "description": "**מפתחות SSH (Secure Shell)** הם זוגות מפתחות קריפטוגרפיים המשמשים לאימות מאובטח בעת התחברות לשרתים מרוחקים.\n\n### כיצד מפתחות SSH עובדים\n\nזוג מפתחות SSH מורכב משני מפתחות:\n\n- **מפתח ציבורי**: מאוחסן בשרת אליו תרצה לגשת. בטוח לשיתוף פומבי.\n- **מפתח פרטי**: מאוחסן במחשב המקומי שלך. יש לשמור אותו בסוד ובאופן מאובטח.\n\nכאשר אתה מתחבר לשרת, לקוח ה-SSH שלך משתמש במפתח הפרטי כדי להוכיח את זהותך מבלי לשלוח סיסמה דרך הרשת.\n\n### סוגי מפתחות\n\n- **Ed25519**: אלגוריתם מודרני, מומלץ לרוב המשתמשים. מהיר יותר, מאובטח יותר ומייצר מפתחות קטנים יותר.\n- **RSA**: אלגוריתם מסורתי, תאימות רחבה. השתמש ב-4096 ביט לאבטחה טובה יותר.\n\n### שימוש\n\n1. צור זוג מפתחות באמצעות כלי זה\n2. העתק את **המפתח הציבורי** לקובץ `{'~'}/.ssh/authorized_keys` בשרת שלך\n3. אחסן את **המפתח הפרטי** בספריית `{'~'}/.ssh/` שלך (לדוגמה `~/.ssh/id_ed25519`)\n4. הגדר הרשאות נכונות: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "ms": {
    "title": "Apakah itu Kunci SSH?",
    "description": "**Kunci SSH (Secure Shell)** adalah pasangan kunci kriptografi yang digunakan untuk pengesahan selamat semasa menyambung ke pelayan jauh.\n\n### Cara Kunci SSH Berfungsi\n\nPasangan kunci SSH terdiri daripada dua kunci:\n\n- **Kunci Awam**: Disimpan di pelayan yang anda ingin akses. Selamat untuk dikongsi secara awam.\n- **Kunci Peribadi**: Disimpan di mesin tempatan anda. Mesti disimpan rahsia dan selamat.\n\nApabila anda menyambung ke pelayan, klien SSH anda menggunakan kunci peribadi untuk membuktikan identiti anda tanpa menghantar kata laluan melalui rangkaian.\n\n### Jenis Kunci\n\n- **Ed25519**: Algoritma moden, disyorkan untuk kebanyakan pengguna. Lebih pantas, lebih selamat dan menghasilkan kunci yang lebih kecil.\n- **RSA**: Algoritma tradisional, serasi secara meluas. Gunakan 4096 bit untuk keselamatan yang lebih baik.\n\n### Penggunaan\n\n1. Jana pasangan kunci menggunakan alat ini\n2. Salin **kunci awam** ke fail `{'~'}/.ssh/authorized_keys` pelayan anda\n3. Simpan **kunci peribadi** di direktori `{'~'}/.ssh/` anda (cth. `~/.ssh/id_ed25519`)\n4. Tetapkan kebenaran yang betul: `chmod 600 ~/.ssh/id_ed25519`"
  },
  "no": {
    "title": "Hva er en SSH-nøkkel?",
    "description": "**SSH (Secure Shell) nøkler** er kryptografiske nøkkelpar som brukes for sikker autentisering når du kobler til eksterne servere.\n\n### Hvordan SSH-nøkler fungerer\n\nEt SSH-nøkkelpar består av to nøkler:\n\n- **Offentlig nøkkel**: Lagres på serveren du vil ha tilgang til. Trygt å dele offentlig.\n- **Privat nøkkel**: Lagres på din lokale maskin. Må holdes hemmelig og sikker.\n\nNår du kobler til en server, bruker SSH-klienten din den private nøkkelen for å bevise din identitet uten å sende et passord over nettverket.\n\n### Nøkkeltyper\n\n- **Ed25519**: Moderne algoritme, anbefalt for de fleste brukere. Raskere, sikrere og produserer mindre nøkler.\n- **RSA**: Tradisjonell algoritme, bredt kompatibel. Bruk 4096 bits for bedre sikkerhet.\n\n### Bruk\n\n1. Generer et nøkkelpar med dette verktøyet\n2. Kopier den **offentlige nøkkelen** til serverens `{'~'}/.ssh/authorized_keys` fil\n3. Lagre den **private nøkkelen** i din `{'~'}/.ssh/` katalog (f.eks. `~/.ssh/id_ed25519`)\n4. Sett riktige tillatelser: `chmod 600 ~/.ssh/id_ed25519`"
  }
}
</i18n>
