<template>
  <DescriptionMarkdown :title="t('title')" :description="t('description')" />
</template>

<script setup lang="ts">
import { DescriptionMarkdown } from '@shared/ui/base'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

<i18n lang="json">
{
  "en": {
    "title": "What is a Certificate Signing Request (CSR)?",
    "description": "**A Certificate Signing Request (CSR)** is a PKCS#10 message that contains your public key and identifying information, and is signed with your private key. You send it to a Certificate Authority (CA) to obtain an X.509 certificate. A CSR proves you control the private key; it never includes the private key itself.\n\n### What a CSR contains\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Public key**: The key and algorithm that will appear in the certificate.\n- **Extensions**: Most commonly Subject Alternative Name (SAN) for DNS names, IP addresses, email addresses, or URIs.\n- **Signature**: A signature over the request using your private key.\n\n### How to use this tool\n\n1. Generate a new key pair or import an existing PEM private key.\n2. Fill in Subject and SAN (SAN is required by most CAs).\n3. Generate the CSR and download it. Keep the private key secure.\n\n### Tips\n\n- Prefer modern algorithms such as Ed25519/Ed448 or ECDSA P-256/P-384, or RSA 2048+ for compatibility.\n- If you import a key, only the CSR is exported; your key stays local.\n- Everything runs locally in your browser."
  },
  "zh": {
    "title": "什么是证书签名请求（CSR）？",
    "description": "**证书签名请求（CSR）** 是一个 PKCS#10 消息，包含公钥和身份信息，并由私钥签名。您将其提交给证书颁发机构（CA）以获取 X.509 证书。CSR 用来证明您控制私钥，且不包含私钥本身。\n\n### CSR 包含的内容\n\n- **主体**：通用名称（CN）、组织（O）、组织单位（OU）、国家/地区、省/州、城市、邮箱。\n- **公钥**：将出现在证书中的密钥与算法。\n- **扩展**：最常见的是主题备用名称（SAN），用于 DNS、IP、邮箱或 URI。\n- **签名**：使用私钥对请求进行签名。\n\n### 如何使用此工具\n\n1. 生成新的密钥对，或导入已有 PEM 私钥。\n2. 填写主体与 SAN（多数 CA 要求 SAN）。\n3. 生成 CSR 并下载。请妥善保管私钥。\n\n### 提示\n\n- 优先使用 Ed25519/Ed448 或 ECDSA P-256/P-384；或为兼容性选择 RSA 2048+。\n- 若导入私钥，仅导出 CSR，私钥留在本地。\n- 全程在浏览器本地完成。"
  },
  "zh-CN": {
    "title": "什么是证书签名请求（CSR）？",
    "description": "**证书签名请求（CSR）** 是一个 PKCS#10 消息，包含公钥和身份信息，并由私钥签名。您将其提交给证书颁发机构（CA）以获取 X.509 证书。CSR 用来证明您控制私钥，且不包含私钥本身。\n\n### CSR 包含的内容\n\n- **主体**：通用名称（CN）、组织（O）、组织单位（OU）、国家/地区、省/州、城市、邮箱。\n- **公钥**：将出现在证书中的密钥与算法。\n- **扩展**：最常见的是主题备用名称（SAN），用于 DNS、IP、邮箱或 URI。\n- **签名**：使用私钥对请求进行签名。\n\n### 如何使用此工具\n\n1. 生成新的密钥对，或导入已有 PEM 私钥。\n2. 填写主体与 SAN（多数 CA 要求 SAN）。\n3. 生成 CSR 并下载。请妥善保管私钥。\n\n### 提示\n\n- 优先使用 Ed25519/Ed448 或 ECDSA P-256/P-384；或为兼容性选择 RSA 2048+。\n- 若导入私钥，仅导出 CSR，私钥留在本地。\n- 全程在浏览器本地完成。"
  },
  "zh-TW": {
    "title": "什麼是憑證簽章請求（CSR）？",
    "description": "**憑證簽章請求（CSR）** 是 PKCS#10 訊息，包含公開金鑰與身分資訊，並由私鑰簽章。您將它提交給憑證頒發機構（CA）以取得 X.509 憑證。CSR 用來證明您掌握私鑰，且不包含私鑰本身。\n\n### CSR 包含的內容\n\n- **主體**：一般名稱（CN）、組織（O）、組織單位（OU）、國家/地區、州/省、城市、電子郵件。\n- **公開金鑰**：將出現在憑證中的金鑰與演算法。\n- **擴充**：最常見的是主體替代名稱（SAN），用於 DNS、IP、電子郵件或 URI。\n- **簽章**：使用私鑰對請求進行簽章。\n\n### 如何使用此工具\n\n1. 產生新的金鑰對，或匯入既有 PEM 私鑰。\n2. 填寫主體與 SAN（多數 CA 要求 SAN）。\n3. 產生 CSR 並下載。請妥善保管私鑰。\n\n### 提示\n\n- 優先使用 Ed25519/Ed448 或 ECDSA P-256/P-384；或為相容性選擇 RSA 2048+。\n- 若匯入私鑰，僅輸出 CSR，私鑰留在本機。\n- 全程在瀏覽器本機完成。"
  },
  "zh-HK": {
    "title": "甚麼是證書簽名請求（CSR）？",
    "description": "**證書簽名請求（CSR）** 是一個 PKCS#10 訊息，包含公鑰與身分資訊，並由私鑰簽名。您將它提交給證書頒發機構（CA）以取得 X.509 證書。CSR 用來證明您掌握私鑰，且不包含私鑰本身。\n\n### CSR 包含的內容\n\n- **主體**：一般名稱（CN）、組織（O）、組織單位（OU）、國家/地區、州/省、城市、電子郵件。\n- **公鑰**：將出現在證書中的金鑰與演算法。\n- **擴展**：最常見的是主體替代名稱（SAN），用於 DNS、IP、電子郵件或 URI。\n- **簽名**：使用私鑰對請求進行簽名。\n\n### 如何使用此工具\n\n1. 產生新的金鑰對，或匯入既有 PEM 私鑰。\n2. 填寫主體與 SAN（多數 CA 要求 SAN）。\n3. 產生 CSR 並下載。請妥善保管私鑰。\n\n### 提示\n\n- 優先使用 Ed25519/Ed448 或 ECDSA P-256/P-384；或為相容性選擇 RSA 2048+。\n- 若匯入私鑰，僅輸出 CSR，私鑰留在本機。\n- 全程在瀏覽器本機完成。"
  },
  "es": {
    "title": "¿Qué es una solicitud de firma de certificado (CSR)?",
    "description": "**Una solicitud de firma de certificado (CSR)** es un mensaje PKCS#10 que contiene tu clave pública e información de identidad, y está firmada con tu clave privada. Se envía a una Autoridad de Certificación (CA) para obtener un certificado X.509. El CSR demuestra que controlas la clave privada; nunca incluye la clave privada.\n\n### Qué contiene un CSR\n\n- **Sujeto**: Nombre común (CN), Organización (O), Unidad organizativa (OU), País, Estado, Localidad, Correo electrónico.\n- **Clave pública**: La clave y el algoritmo que aparecerán en el certificado.\n- **Extensiones**: Principalmente Subject Alternative Name (SAN) para nombres DNS, direcciones IP, correos o URIs.\n- **Firma**: Una firma sobre la solicitud usando tu clave privada.\n\n### Cómo usar esta herramienta\n\n1. Genera un par de claves nuevo o importa una clave privada PEM existente.\n2. Completa el Subject y el SAN (la mayoría de las CAs requieren SAN).\n3. Genera el CSR y descárgalo. Mantén la clave privada segura.\n\n### Consejos\n\n- Prefiere algoritmos modernos como Ed25519/Ed448 o ECDSA P-256/P-384, o RSA 2048+ por compatibilidad.\n- Si importas una clave, solo se exporta el CSR; tu clave permanece local.\n- Todo se procesa localmente en tu navegador."
  },
  "fr": {
    "title": "Qu'est-ce qu'une demande de signature de certificat (CSR) ?",
    "description": "**Une demande de signature de certificat (CSR)** est un message PKCS#10 qui contient votre clé publique et des informations d'identité, et qui est signé avec votre clé privée. Vous l'envoyez à une autorité de certification (CA) pour obtenir un certificat X.509. Le CSR prouve que vous contrôlez la clé privée ; il ne contient jamais la clé privée elle-même.\n\n### Ce que contient un CSR\n\n- **Sujet** : Nom commun (CN), Organisation (O), Unité organisationnelle (OU), Pays, État, Localité, E-mail.\n- **Clé publique** : La clé et l'algorithme qui apparaîtront dans le certificat.\n- **Extensions** : Le plus souvent Subject Alternative Name (SAN) pour des noms DNS, adresses IP, e-mails ou URI.\n- **Signature** : Une signature de la demande avec votre clé privée.\n\n### Comment utiliser cet outil\n\n1. Générez une nouvelle paire de clés ou importez une clé privée PEM existante.\n2. Renseignez le Subject et le SAN (la plupart des CA exigent le SAN).\n3. Générez le CSR et téléchargez-le. Gardez la clé privée en sécurité.\n\n### Conseils\n\n- Privilégiez des algorithmes modernes tels que Ed25519/Ed448 ou ECDSA P-256/P-384, ou RSA 2048+ pour la compatibilité.\n- Si vous importez une clé, seul le CSR est exporté ; votre clé reste locale.\n- Tout est traité localement dans votre navigateur."
  },
  "de": {
    "title": "Was ist eine Certificate Signing Request (CSR)?",
    "description": "**Eine Certificate Signing Request (CSR)** ist eine PKCS#10-Nachricht, die Ihren öffentlichen Schlüssel und Identitätsangaben enthält und mit Ihrem privaten Schlüssel signiert ist. Sie senden sie an eine Zertifizierungsstelle (CA), um ein X.509-Zertifikat zu erhalten. Der CSR beweist, dass Sie den privaten Schlüssel kontrollieren; er enthält niemals den privaten Schlüssel selbst.\n\n### Was ein CSR enthält\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, E-Mail.\n- **Öffentlicher Schlüssel**: Der Schlüssel und Algorithmus, der im Zertifikat erscheint.\n- **Erweiterungen**: Meist Subject Alternative Name (SAN) für DNS-Namen, IP-Adressen, E-Mail-Adressen oder URIs.\n- **Signatur**: Eine Signatur über die Anfrage mit Ihrem privaten Schlüssel.\n\n### So verwenden Sie dieses Tool\n\n1. Erzeugen Sie ein neues Schlüsselpaar oder importieren Sie einen vorhandenen PEM-Privatschlüssel.\n2. Füllen Sie Subject und SAN aus (SAN wird von den meisten CAs verlangt).\n3. Erzeugen Sie den CSR und laden Sie ihn herunter. Bewahren Sie den privaten Schlüssel sicher auf.\n\n### Tipps\n\n- Bevorzugen Sie moderne Algorithmen wie Ed25519/Ed448 oder ECDSA P-256/P-384 oder RSA 2048+ für Kompatibilität.\n- Wenn Sie einen Schlüssel importieren, wird nur der CSR exportiert; Ihr Schlüssel bleibt lokal.\n- Alles läuft lokal in Ihrem Browser."
  },
  "it": {
    "title": "Che cos'è una richiesta di firma del certificato (CSR)?",
    "description": "**Una richiesta di firma del certificato (CSR)** è un messaggio PKCS#10 che contiene la tua chiave pubblica e informazioni di identità, ed è firmato con la tua chiave privata. La invii a un'autorità di certificazione (CA) per ottenere un certificato X.509. Il CSR dimostra che controlli la chiave privata; non include mai la chiave privata stessa.\n\n### Cosa contiene un CSR\n\n- **Soggetto**: Nome comune (CN), Organizzazione (O), Unità organizzativa (OU), Paese, Stato, Località, Email.\n- **Chiave pubblica**: La chiave e l'algoritmo che appariranno nel certificato.\n- **Estensioni**: Principalmente Subject Alternative Name (SAN) per nomi DNS, indirizzi IP, email o URI.\n- **Firma**: Una firma della richiesta con la tua chiave privata.\n\n### Come usare questo strumento\n\n1. Genera una nuova coppia di chiavi o importa una chiave privata PEM esistente.\n2. Compila Subject e SAN (la maggior parte delle CA richiede il SAN).\n3. Genera il CSR e scaricalo. Tieni la chiave privata al sicuro.\n\n### Suggerimenti\n\n- Preferisci algoritmi moderni come Ed25519/Ed448 o ECDSA P-256/P-384, oppure RSA 2048+ per compatibilità.\n- Se importi una chiave, viene esportato solo il CSR; la tua chiave resta locale.\n- Tutto avviene localmente nel tuo browser."
  },
  "ja": {
    "title": "CSR（証明書署名要求）とは？",
    "description": "**証明書署名要求（CSR）** は PKCS#10 メッセージで、公開鍵と識別情報を含み、秘密鍵で署名されています。認証局（CA）に送って X.509 証明書を取得します。CSR は秘密鍵の保有を証明し、秘密鍵そのものは含みません。\n\n### CSR に含まれるもの\n\n- **Subject**：Common Name（CN）、Organization（O）、Organizational Unit（OU）、Country、State、Locality、Email。\n- **公開鍵**：証明書に含まれる鍵とアルゴリズム。\n- **拡張**：最も一般的なのは Subject Alternative Name（SAN）で、DNS、IP、メール、URI に対応します。\n- **署名**：秘密鍵で要求に署名したもの。\n\n### このツールの使い方\n\n1. 新しい鍵ペアを生成するか、既存の PEM 秘密鍵をインポートします。\n2. Subject と SAN を入力します（多くの CA は SAN を必須とします）。\n3. CSR を生成してダウンロードします。秘密鍵は安全に保管してください。\n\n### ヒント\n\n- Ed25519/Ed448 または ECDSA P-256/P-384 などの最新アルゴリズム、または互換性のために RSA 2048+ を推奨します。\n- 鍵をインポートした場合、出力されるのは CSR のみで、鍵はローカルに残ります。\n- すべてブラウザ内でローカル処理されます。"
  },
  "ko": {
    "title": "CSR(인증서 서명 요청)이란?",
    "description": "**인증서 서명 요청(CSR)** 은 공개 키와 식별 정보를 담고 개인 키로 서명한 PKCS#10 메시지입니다. 인증 기관(CA)에 제출해 X.509 인증서를 발급받습니다. CSR은 개인 키를 소유하고 있음을 증명하며, 개인 키 자체는 포함하지 않습니다.\n\n### CSR에 포함되는 내용\n\n- **주체**: Common Name(CN), Organization(O), Organizational Unit(OU), Country, State, Locality, Email.\n- **공개 키**: 인증서에 포함될 키와 알고리즘.\n- **확장**: 보통 Subject Alternative Name(SAN)으로 DNS, IP, 이메일 또는 URI를 포함합니다.\n- **서명**: 개인 키로 요청을 서명한 값.\n\n### 이 도구 사용 방법\n\n1. 새 키 쌍을 생성하거나 기존 PEM 개인 키를 가져옵니다.\n2. Subject와 SAN을 입력합니다(SAN은 대부분의 CA에서 요구).\n3. CSR을 생성하고 다운로드합니다. 개인 키는 안전하게 보관하세요.\n\n### 팁\n\n- Ed25519/Ed448 또는 ECDSA P-256/P-384 같은 최신 알고리즘, 혹은 호환성을 위해 RSA 2048+를 권장합니다.\n- 키를 가져오면 CSR만 내보내며, 키는 로컬에 남습니다.\n- 모든 처리는 브라우저에서 로컬로 진행됩니다."
  },
  "ru": {
    "title": "Что такое запрос на подпись сертификата (CSR)?",
    "description": "**Запрос на подпись сертификата (CSR)** — это сообщение PKCS#10, содержащее ваш открытый ключ и информацию об идентичности, подписанное вашим закрытым ключом. Его отправляют в центр сертификации (CA), чтобы получить сертификат X.509. CSR подтверждает, что вы контролируете закрытый ключ, и никогда не включает сам закрытый ключ.\n\n### Что содержит CSR\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Открытый ключ**: Ключ и алгоритм, которые будут в сертификате.\n- **Расширения**: Чаще всего Subject Alternative Name (SAN) для DNS-имен, IP-адресов, email или URI.\n- **Подпись**: Подпись запроса вашим закрытым ключом.\n\n### Как пользоваться этим инструментом\n\n1. Сгенерируйте новую пару ключей или импортируйте существующий PEM‑закрытый ключ.\n2. Заполните Subject и SAN (SAN требуется большинством CA).\n3. Сгенерируйте CSR и скачайте его. Держите закрытый ключ в безопасности.\n\n### Советы\n\n- Предпочитайте современные алгоритмы Ed25519/Ed448 или ECDSA P-256/P-384, либо RSA 2048+ для совместимости.\n- Если вы импортируете ключ, экспортируется только CSR; ключ остаётся локально.\n- Всё выполняется локально в вашем браузере."
  },
  "pt": {
    "title": "O que é uma solicitação de assinatura de certificado (CSR)?",
    "description": "**Uma solicitação de assinatura de certificado (CSR)** é uma mensagem PKCS#10 que contém sua chave pública e informações de identidade, e é assinada com sua chave privada. Você a envia para uma Autoridade Certificadora (CA) para obter um certificado X.509. O CSR comprova que você controla a chave privada; ele nunca inclui a chave privada em si.\n\n### O que um CSR contém\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Chave pública**: A chave e o algoritmo que aparecerão no certificado.\n- **Extensões**: Principalmente Subject Alternative Name (SAN) para nomes DNS, endereços IP, emails ou URIs.\n- **Assinatura**: Uma assinatura da solicitação usando sua chave privada.\n\n### Como usar esta ferramenta\n\n1. Gere um novo par de chaves ou importe uma chave privada PEM existente.\n2. Preencha Subject e SAN (a maioria das CAs exige SAN).\n3. Gere o CSR e faça o download. Mantenha a chave privada segura.\n\n### Dicas\n\n- Prefira algoritmos modernos como Ed25519/Ed448 ou ECDSA P-256/P-384, ou RSA 2048+ por compatibilidade.\n- Se você importar uma chave, apenas o CSR é exportado; sua chave permanece local.\n- Tudo é processado localmente no seu navegador."
  },
  "ar": {
    "title": "ما هو طلب توقيع الشهادة (CSR)؟",
    "description": "**طلب توقيع الشهادة (CSR)** هو رسالة PKCS#10 تحتوي على مفتاحك العام ومعلومات التعريف، وموقّعة بمفتاحك الخاص. ترسله إلى جهة إصدار الشهادات (CA) للحصول على شهادة X.509. يثبت الـ CSR أنك تملك المفتاح الخاص، ولا يتضمن المفتاح الخاص نفسه.\n\n### ماذا يحتوي CSR\n\n- **الموضوع**: الاسم الشائع (CN)، المؤسسة (O)، الوحدة التنظيمية (OU)، البلد، الولاية، الموقع، البريد الإلكتروني.\n- **المفتاح العام**: المفتاح والخوارزمية اللذان سيظهران في الشهادة.\n- **الامتدادات**: غالباً Subject Alternative Name (SAN) لأسماء DNS وعناوين IP والبريد الإلكتروني أو URI.\n- **التوقيع**: توقيع للطلب باستخدام المفتاح الخاص.\n\n### كيفية استخدام هذه الأداة\n\n1. أنشئ زوج مفاتيح جديداً أو استورد مفتاحاً خاصاً PEM موجوداً.\n2. املأ Subject و SAN (معظم جهات الإصدار تتطلب SAN).\n3. أنشئ CSR وحمّله. احفظ المفتاح الخاص بأمان.\n\n### نصائح\n\n- يفضّل استخدام خوارزميات حديثة مثل Ed25519/Ed448 أو ECDSA P-256/P-384، أو RSA 2048+ للتوافق.\n- إذا استوردت مفتاحاً، فسيتم تصدير CSR فقط؛ يبقى المفتاح محلياً.\n- كل شيء يعمل محلياً داخل المتصفح."
  },
  "hi": {
    "title": "CSR (सर्टिफिकेट साइनिंग रिक्वेस्ट) क्या है?",
    "description": "**सर्टिफिकेट साइनिंग रिक्वेस्ट (CSR)** एक PKCS#10 संदेश है जिसमें आपकी सार्वजनिक कुंजी और पहचान की जानकारी होती है, और इसे आपकी निजी कुंजी से साइन किया जाता है। इसे X.509 प्रमाणपत्र पाने के लिए प्रमाणन प्राधिकरण (CA) को भेजा जाता है। CSR यह साबित करता है कि आप निजी कुंजी नियंत्रित करते हैं; इसमें निजी कुंजी शामिल नहीं होती।\n\n### CSR में क्या होता है\n\n- **Subject**: कॉमन नेम (CN), संगठन (O), संगठनात्मक इकाई (OU), देश, राज्य, शहर, ईमेल।\n- **पब्लिक की**: वह कुंजी और एल्गोरिथ्म जो प्रमाणपत्र में होगा।\n- **एक्सटेंशन्स**: आमतौर पर Subject Alternative Name (SAN) — DNS नाम, IP पते, ईमेल या URI के लिए।\n- **हस्ताक्षर**: आपकी निजी कुंजी से अनुरोध का साइन।\n\n### इस टूल का उपयोग कैसे करें\n\n1. नया की पेयर बनाएं या मौजूदा PEM निजी कुंजी आयात करें।\n2. Subject और SAN भरें (अधिकांश CA SAN मांगते हैं)।\n3. CSR बनाएं और डाउनलोड करें। निजी कुंजी को सुरक्षित रखें।\n\n### सुझाव\n\n- Ed25519/Ed448 या ECDSA P-256/P-384 जैसे आधुनिक एल्गोरिथ्म, या संगतता के लिए RSA 2048+ चुनें।\n- यदि आप कुंजी आयात करते हैं, तो केवल CSR निर्यात होता है; कुंजी स्थानीय रहती है।\n- सब कुछ आपके ब्राउज़र में स्थानीय रूप से चलता है।"
  },
  "tr": {
    "title": "CSR (Sertifika İmzalama İsteği) nedir?",
    "description": "**Sertifika İmzalama İsteği (CSR)**, açık anahtarınızı ve kimlik bilgilerini içeren ve özel anahtarınızla imzalanan bir PKCS#10 mesajıdır. X.509 sertifikası almak için bir Sertifika Otoritesine (CA) gönderilir. CSR, özel anahtarı kontrol ettiğinizi kanıtlar; özel anahtarın kendisini içermez.\n\n### CSR'nin içeriği\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Açık anahtar**: Sertifikada görünecek anahtar ve algoritma.\n- **Eklentiler**: Genellikle DNS adları, IP adresleri, e-postalar veya URI'ler için Subject Alternative Name (SAN).\n- **İmza**: İsteğin özel anahtarınızla imzalanması.\n\n### Bu aracı nasıl kullanılır\n\n1. Yeni bir anahtar çifti oluşturun veya mevcut bir PEM özel anahtarı içe aktarın.\n2. Subject ve SAN alanlarını doldurun (çoğu CA SAN ister).\n3. CSR'yi oluşturun ve indirin. Özel anahtarı güvenli tutun.\n\n### İpuçları\n\n- Ed25519/Ed448 veya ECDSA P-256/P-384 gibi modern algoritmaları, ya da uyumluluk için RSA 2048+ kullanmayı tercih edin.\n- Anahtar içe aktarılırsa yalnızca CSR dışa aktarılır; anahtar yerelde kalır.\n- Her şey tarayıcınızda yerel olarak çalışır."
  },
  "nl": {
    "title": "Wat is een Certificate Signing Request (CSR)?",
    "description": "**Een Certificate Signing Request (CSR)** is een PKCS#10-bericht dat je publieke sleutel en identiteitsinformatie bevat en is ondertekend met je privésleutel. Je stuurt het naar een certificaatautoriteit (CA) om een X.509-certificaat te verkrijgen. De CSR bewijst dat je de privésleutel beheert; de privésleutel zelf staat er nooit in.\n\n### Wat een CSR bevat\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Publieke sleutel**: De sleutel en het algoritme die in het certificaat komen.\n- **Extensies**: Meestal Subject Alternative Name (SAN) voor DNS-namen, IP-adressen, e-mailadressen of URI's.\n- **Handtekening**: Een handtekening over het verzoek met je privésleutel.\n\n### Hoe je deze tool gebruikt\n\n1. Genereer een nieuw sleutelpaar of importeer een bestaande PEM-privésleutel.\n2. Vul Subject en SAN in (SAN is vereist door de meeste CA's).\n3. Genereer de CSR en download die. Houd de privésleutel veilig.\n\n### Tips\n\n- Kies moderne algoritmen zoals Ed25519/Ed448 of ECDSA P-256/P-384, of RSA 2048+ voor compatibiliteit.\n- Als je een sleutel importeert, wordt alleen de CSR geëxporteerd; je sleutel blijft lokaal.\n- Alles draait lokaal in je browser."
  },
  "sv": {
    "title": "Vad är en Certificate Signing Request (CSR)?",
    "description": "**En Certificate Signing Request (CSR)** är ett PKCS#10-meddelande som innehåller din publika nyckel och identitetsinformation och är signerat med din privata nyckel. Du skickar det till en certifikatutfärdare (CA) för att få ett X.509-certifikat. CSR:n bevisar att du kontrollerar den privata nyckeln; den innehåller aldrig den privata nyckeln.\n\n### Vad en CSR innehåller\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Publik nyckel**: Nyckeln och algoritmen som visas i certifikatet.\n- **Tillägg**: Vanligen Subject Alternative Name (SAN) för DNS-namn, IP-adresser, e-postadresser eller URI:er.\n- **Signatur**: En signatur över begäran med din privata nyckel.\n\n### Så använder du detta verktyg\n\n1. Skapa ett nytt nyckelpar eller importera en befintlig PEM-privat nyckel.\n2. Fyll i Subject och SAN (SAN krävs av de flesta CA:er).\n3. Skapa CSR:n och ladda ner den. Förvara den privata nyckeln säkert.\n\n### Tips\n\n- Föredra moderna algoritmer som Ed25519/Ed448 eller ECDSA P-256/P-384, eller RSA 2048+ för kompatibilitet.\n- Om du importerar en nyckel exporteras endast CSR:n; nyckeln stannar lokalt.\n- Allt körs lokalt i din webbläsare."
  },
  "pl": {
    "title": "Czym jest żądanie podpisu certyfikatu (CSR)?",
    "description": "**Żądanie podpisu certyfikatu (CSR)** to komunikat PKCS#10 zawierający klucz publiczny i informacje identyfikacyjne, podpisany kluczem prywatnym. Wysyła się je do urzędu certyfikacji (CA), aby uzyskać certyfikat X.509. CSR potwierdza, że kontrolujesz klucz prywatny; nie zawiera samego klucza prywatnego.\n\n### Co zawiera CSR\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Klucz publiczny**: Klucz i algorytm, które pojawią się w certyfikacie.\n- **Rozszerzenia**: Najczęściej Subject Alternative Name (SAN) dla nazw DNS, adresów IP, e-maili lub URI.\n- **Podpis**: Podpis żądania przy użyciu klucza prywatnego.\n\n### Jak używać tego narzędzia\n\n1. Wygeneruj nową parę kluczy lub zaimportuj istniejący klucz prywatny PEM.\n2. Uzupełnij Subject i SAN (większość CA wymaga SAN).\n3. Wygeneruj CSR i pobierz go. Chroń klucz prywatny.\n\n### Wskazówki\n\n- Preferuj nowoczesne algorytmy, takie jak Ed25519/Ed448 lub ECDSA P-256/P-384, albo RSA 2048+ dla zgodności.\n- Jeśli importujesz klucz, eksportowany jest tylko CSR; klucz pozostaje lokalnie.\n- Wszystko działa lokalnie w przeglądarce."
  },
  "vi": {
    "title": "CSR (yêu cầu ký chứng chỉ) là gì?",
    "description": "**CSR (yêu cầu ký chứng chỉ)** là một thông điệp PKCS#10 chứa khóa công khai và thông tin định danh, được ký bằng khóa riêng. Bạn gửi nó đến cơ quan chứng thực (CA) để lấy chứng chỉ X.509. CSR chứng minh bạn kiểm soát khóa riêng; nó không bao giờ chứa khóa riêng.\n\n### CSR chứa gì\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Khóa công khai**: Khóa và thuật toán sẽ xuất hiện trong chứng chỉ.\n- **Phần mở rộng**: Thường là Subject Alternative Name (SAN) cho tên DNS, địa chỉ IP, email hoặc URI.\n- **Chữ ký**: Chữ ký trên yêu cầu bằng khóa riêng.\n\n### Cách dùng công cụ này\n\n1. Tạo cặp khóa mới hoặc nhập khóa riêng PEM hiện có.\n2. Điền Subject và SAN (hầu hết CA yêu cầu SAN).\n3. Tạo CSR và tải xuống. Giữ khóa riêng an toàn.\n\n### Mẹo\n\n- Ưu tiên thuật toán hiện đại như Ed25519/Ed448 hoặc ECDSA P-256/P-384, hoặc RSA 2048+ để tương thích.\n- Nếu nhập khóa, chỉ CSR được xuất; khóa vẫn ở máy của bạn.\n- Mọi thứ chạy cục bộ trong trình duyệt của bạn."
  },
  "th": {
    "title": "CSR (คำขอลงนามใบรับรอง) คืออะไร?",
    "description": "**CSR (คำขอลงนามใบรับรอง)** เป็นข้อความ PKCS#10 ที่มีคีย์สาธารณะและข้อมูลระบุตัวตน และถูกลงนามด้วยคีย์ส่วนตัว คุณส่งให้หน่วยงานออกใบรับรอง (CA) เพื่อรับใบรับรอง X.509 CSR ใช้ยืนยันว่าคุณครอบครองคีย์ส่วนตัว และไม่รวมคีย์ส่วนตัวไว้ด้วย\n\n### CSR มีอะไรบ้าง\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **คีย์สาธารณะ**: คีย์และอัลกอริทึมที่จะปรากฏในใบรับรอง\n- **ส่วนขยาย**: โดยมากคือ Subject Alternative Name (SAN) สำหรับชื่อ DNS, IP, อีเมล หรือ URI\n- **ลายเซ็น**: ลายเซ็นของคำขอด้วยคีย์ส่วนตัว\n\n### วิธีใช้เครื่องมือนี้\n\n1. สร้างคู่คีย์ใหม่หรือนำเข้าคีย์ส่วนตัว PEM ที่มีอยู่\n2. กรอก Subject และ SAN (CA ส่วนใหญ่ต้องการ SAN)\n3. สร้าง CSR แล้วดาวน์โหลด เก็บคีย์ส่วนตัวให้ปลอดภัย\n\n### เคล็ดลับ\n\n- เลือกอัลกอริทึมสมัยใหม่ เช่น Ed25519/Ed448 หรือ ECDSA P-256/P-384 หรือ RSA 2048+ เพื่อความเข้ากันได้\n- หากนำเข้าคีย์ จะส่งออกเฉพาะ CSR เท่านั้น คีย์ยังอยู่ในเครื่อง\n- ทุกอย่างทำงานแบบโลคัลในเบราว์เซอร์ของคุณ"
  },
  "id": {
    "title": "Apa itu Certificate Signing Request (CSR)?",
    "description": "**Certificate Signing Request (CSR)** adalah pesan PKCS#10 yang berisi kunci publik dan informasi identitas, serta ditandatangani dengan kunci privat. Anda mengirimkannya ke Certificate Authority (CA) untuk mendapatkan sertifikat X.509. CSR membuktikan bahwa Anda menguasai kunci privat; CSR tidak pernah menyertakan kunci privat itu sendiri.\n\n### Apa saja isi CSR\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Kunci publik**: Kunci dan algoritme yang akan muncul di sertifikat.\n- **Ekstensi**: Umumnya Subject Alternative Name (SAN) untuk nama DNS, alamat IP, email, atau URI.\n- **Tanda tangan**: Tanda tangan atas permintaan menggunakan kunci privat.\n\n### Cara menggunakan alat ini\n\n1. Buat pasangan kunci baru atau impor kunci privat PEM yang sudah ada.\n2. Isi Subject dan SAN (kebanyakan CA mewajibkan SAN).\n3. Buat CSR dan unduh. Jaga kunci privat tetap aman.\n\n### Tips\n\n- Pilih algoritme modern seperti Ed25519/Ed448 atau ECDSA P-256/P-384, atau RSA 2048+ untuk kompatibilitas.\n- Jika Anda mengimpor kunci, yang diekspor hanya CSR; kunci tetap lokal.\n- Semua proses berjalan lokal di browser Anda."
  },
  "he": {
    "title": "מהו בקשת חתימה על תעודה (CSR)?",
    "description": "**בקשת חתימה על תעודה (CSR)** היא הודעת PKCS#10 שמכילה את המפתח הציבורי שלך ומידע זיהוי, והיא חתומה במפתח הפרטי שלך. שולחים אותה לרשות מאשרת (CA) כדי לקבל תעודת X.509. ה‑CSR מוכיח שאתה שולט במפתח הפרטי; הוא לא כולל את המפתח הפרטי עצמו.\n\n### מה CSR כולל\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **מפתח ציבורי**: המפתח והאלגוריתם שיופיעו בתעודה.\n- **הרחבות**: לרוב Subject Alternative Name (SAN) לשמות DNS, כתובות IP, דוא״ל או URI.\n- **חתימה**: חתימה על הבקשה באמצעות המפתח הפרטי.\n\n### כיצד להשתמש בכלי זה\n\n1. צור זוג מפתחות חדש או ייבא מפתח פרטי PEM קיים.\n2. מלא Subject ו‑SAN (רוב ה‑CA דורשים SAN).\n3. צור את ה‑CSR והורד אותו. שמור על המפתח הפרטי מאובטח.\n\n### טיפים\n\n- העדף אלגוריתמים מודרניים כמו Ed25519/Ed448 או ECDSA P-256/P-384, או RSA 2048+ לתאימות.\n- אם מייבאים מפתח, מיוצא רק ה‑CSR; המפתח נשאר מקומי.\n- הכול רץ מקומית בדפדפן שלך."
  },
  "ms": {
    "title": "Apakah itu Certificate Signing Request (CSR)?",
    "description": "**Certificate Signing Request (CSR)** ialah mesej PKCS#10 yang mengandungi kunci awam dan maklumat identiti anda, serta ditandatangani dengan kunci peribadi. Anda menghantarnya kepada Pihak Berkuasa Pensijilan (CA) untuk mendapatkan sijil X.509. CSR membuktikan bahawa anda mengawal kunci peribadi; ia tidak pernah mengandungi kunci peribadi itu sendiri.\n\n### Apa yang terkandung dalam CSR\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Kunci awam**: Kunci dan algoritma yang akan muncul pada sijil.\n- **Sambungan**: Lazimnya Subject Alternative Name (SAN) untuk nama DNS, alamat IP, e-mel atau URI.\n- **Tandatangan**: Tandatangan pada permintaan menggunakan kunci peribadi.\n\n### Cara menggunakan alat ini\n\n1. Jana pasangan kunci baharu atau import kunci peribadi PEM sedia ada.\n2. Isi Subject dan SAN (kebanyakan CA memerlukan SAN).\n3. Jana CSR dan muat turun. Simpan kunci peribadi dengan selamat.\n\n### Petua\n\n- Utamakan algoritma moden seperti Ed25519/Ed448 atau ECDSA P-256/P-384, atau RSA 2048+ untuk keserasian.\n- Jika anda mengimport kunci, hanya CSR dieksport; kunci kekal setempat.\n- Semuanya berjalan secara tempatan dalam pelayar anda."
  },
  "no": {
    "title": "Hva er en Certificate Signing Request (CSR)?",
    "description": "**En Certificate Signing Request (CSR)** er en PKCS#10-melding som inneholder din offentlige nøkkel og identitetsinformasjon, og som er signert med din private nøkkel. Du sender den til en sertifiseringsinstans (CA) for å få et X.509-sertifikat. CSR-en beviser at du kontrollerer den private nøkkelen; den inneholder aldri selve private nøkkelen.\n\n### Hva en CSR inneholder\n\n- **Subject**: Common Name (CN), Organization (O), Organizational Unit (OU), Country, State, Locality, Email.\n- **Offentlig nøkkel**: Nøkkelen og algoritmen som vil vises i sertifikatet.\n- **Utvidelser**: Oftest Subject Alternative Name (SAN) for DNS-navn, IP-adresser, e-postadresser eller URI-er.\n- **Signatur**: En signatur over forespørselen med din private nøkkel.\n\n### Slik bruker du dette verktøyet\n\n1. Generer et nytt nøkkelpar eller importer en eksisterende PEM-privat nøkkel.\n2. Fyll inn Subject og SAN (SAN kreves av de fleste CA-er).\n3. Generer CSR-en og last den ned. Hold den private nøkkelen sikker.\n\n### Tips\n\n- Foretrekk moderne algoritmer som Ed25519/Ed448 eller ECDSA P-256/P-384, eller RSA 2048+ for kompatibilitet.\n- Hvis du importerer en nøkkel, eksporteres bare CSR-en; nøkkelen forblir lokal.\n- Alt kjører lokalt i nettleseren din."
  }
}
</i18n>
